"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0401_edit': {
        "description": ':e {file} Edit File',
        "keys": '::e config.py\r',
        "initial": '# Config\nDEBUG = True',
    },
    '0402_revert': {
        "description": ':e! Revert',
        "keys": 'jdddddd::e!\r',
        "initial": '# Perfect Code\nx = 1\ny = 2\nz = 3',
    },
    '0403_read_file': {
        "description": ':r {file} Read File',
        "keys": '::r header.py\r',
        "initial": '# Main\nprint("hello")',
    },
    '0404_read_command': {
        "description": ':r !{cmd} Read Command',
        "keys": 'j::r !date\r',
        "initial": 'Notes:\n',
    },
    '0405_substitute': {
        "description": ':s/old/new/ Substitute',
        "keys": 'j:s/old/new/\r',
        "initial": '# Demo\nold = "old old old"\nkeep = "safe"',
    },
    '0406_substitute_g': {
        "description": ':s/old/new/g Substitute All',
        "keys": 'j::s/foo/bar/g\r',
        "initial": '# Demo\nfoo = foo + foo * foo',
    },
    '0407_substitute_file': {
        "description": ':%s File-Wide Replace',
        "keys": '::%s/old/new/g\r',
        "initial": '# Demo\nold = 1\nold = 2\nold = 3\nold = 4',
    },
    '0408_substitute_confirm': {
        "description": ':%s///gc Confirm Each',
        "keys": ':%s/foo/X/gc\ryna',
        "initial": '# Demo\nfoo = 1\nbar = foo\nfoo = foo + 1\nbaz = 99',
    },
    '0409_substitute_range': {
        "description": ':s with Ranges',
        "keys": '::2,4s/old/new/g\r',
        "initial": '# Demo\nold = 1\nold = 2\nold = 3\nold = 4\nold = 5',
    },
    '0410_ls': {
        "description": ':ls List Buffers',
        "keys": ':ls\r\r',
        "initial": '# File C',
    },
    '0411_buffer_switch': {
        "description": ':b Switch Buffer',
        "keys": ':b 2\r:b util\r',
        "initial": '# Utils',
    },
    '0412_bn_bp': {
        "description": ':bn / :bp Cycle Buffers',
        "keys": ':bn\r:bn\r:bp\r',
        "initial": '# Charlie',
    },
    '0413_bd': {
        "description": ':bd Delete Buffer',
        "keys": ':ls\r\r:bd\r',
        "initial": '# C',
    },
    '0414_args': {
        "description": ':args Argument List',
        "keys": ':args\r\r',
        "initial": '# C',
    },
    '0415_tabnew': {
        "description": ':tabnew New Tab',
        "keys": ':tabnew\r',
        "initial": '# Demo\nprint("tab one")',
    },
    '0416_tabnext': {
        "description": ':tabnext / :tabprev Cycle Tabs',
        "keys": ':tabnext\r:tabnext\r:tabprev\r',
        "initial": '# Tab C',
    },
    '0417_tabclose': {
        "description": ':tabclose Close Tab',
        "keys": 'gt:tabclose\r',
        "initial": '# Tab B',
    },
    '0418_tabonly': {
        "description": ':tabonly Only Tab',
        "keys": 'gt:tabonly\r',
        "initial": '# C',
    },
    '0423_set_number': {
        "description": ':set number',
        "keys": ':set number\r:set nonumber\r:set nu\r:set nonu\r',
        "initial": '# Demo\ndef greet(name):\n    return f"Hello {name}"\n\nresult = greet("World")\nprint(result)',
    },
    '0424_set_relativenumber': {
        "description": ':set relativenumber',
        "keys": ':set relativenumber\r9j3k:set norelativenumber\r',
        "initial": '# Player module\nimport math\n\nMAX_HP = 100\nMAX_MP = 50\n\ndef greet(name):\n    return f"Hello {name}"\n\ndef heal(hp, amount):\n    return min(hp + amount, MAX_HP)\n\ndef damage(hp, hit):\n    return max(hp - hit, 0)\n\nresult = greet("World")\nprint(result)\n',
    },
    '0425_set_hlsearch': {
        "description": ':set hlsearch',
        "keys": ':set hlsearch\r/name\r:set nohlsearch\r',
        "initial": '# Demo\ndef greet(name):\n    return f"Hello {name}"\n\nresult = greet("World")\nprint(result)',
    },
    '0426_set_incsearch': {
        "description": ':set incsearch',
        "keys": '::set incsearch\r/ret\r',
        "initial": '# Demo\nred_alert = True\nready = False\nreturn_value = 42\nprint(return_value)',
    },
    '0427_set_ignorecase': {
        "description": ':set ignorecase / smartcase',
        "keys": ':set ignorecase\r/name\rnn:set smartcase\r/Name\r',
        "initial": '# Demo\ndef greet(Name):\n    return f"Hello {Name}"\n\nname = "World"\nprint(greet(name))',
    },
    '0428_set_wrap': {
        "description": ':set wrap / nowrap',
        "keys": '::set nowrap\rjj$::set wrap\r',
        "initial": '# Demo\ndef greet(name):\n    return f"Hello {name}, welcome to the world of Vim editing and text processing!"\n\nresult = greet("World")\nprint(result)',
    },
    '0429_noh': {
        "description": ':noh',
        "keys": ':set hlsearch\r/name\r:noh\r/greet\r',
        "initial": '# Demo\ndef greet(name):\n    return f"Hello {name}"\n\nresult = greet("World")\nprint(result)',
    },
    '0430_set_list': {
        "description": ':set list',
        "keys": ':set list\r:set nolist\r',
        "initial": 'Hello World\n\tindented with tab\n    indented with spaces\ntrailing spaces   \nend of file',
    },
    '0430a_set_split': {
        "description": ':set splitbelow / splitright',
        "keys": ':set splitbelow splitright\r:vsplit\r',
        "initial": '# Demo\nprint("hello")',
    },
    '0430b_set_spell': {
        "description": ':set spell Spell Check',
        "keys": ':set spell\r',
        "initial": 'The quik brown fox\njumps over the layz dog\nspeling is hard',
    },
    '0430c_set_fileformat': {
        "description": ':set fileformat',
        "keys": ':set ff?\r:set ff=unix\r',
        "initial": '# Demo\nprint("hi")',
    },
    '0430d_qa': {
        "description": ':qa Quit All',
        "keys": ':qa\r',
        "initial": '# File B',
    },
    '0430e_wa': {
        "description": ':wa Write All',
        "keys": 'jA\nx = 1\x1b:bn\rjA\ny = 2\x1b:wa\r',
        "initial": '# File B',
    },
    '0430f_wqa': {
        "description": ':wqa / :xa Write All + Quit',
        "keys": ':wqa\r',
        "initial": '# File B\ny = 2',
    },
    '0430g_new': {
        "description": ':new New Window',
        "keys": ':new\r',
        "initial": '# Demo\nprint("hello")\nprint("world")',
    },
    '0430h_enew': {
        "description": ':enew New Empty Buffer',
        "keys": ':enew\r',
        "initial": '# Demo\nprint("hello")',
    },
    '0430i_retab': {
        "description": ':retab Fix Tabs',
        "keys": '::set expandtab tabstop=4\r::retab\r',
        "initial": 'def hello():\n\tprint("hi")\n\tif True:\n\t\tprint("yes")',
    },
    '0430j_delmarks': {
        "description": ':delmarks Delete Marks',
        "keys": 'majjmbjjmc::marks\r\r::delmarks a\r::marks\r\r::delmarks!\r::marks\r\r',
        "initial": 'line 1\nline 2\nline 3\nline 4\nline 5',
    },
    '0430k_undolist': {
        "description": ':undolist Undo Info',
        "keys": 'oalpha\x1buobeta\x1b:undolist\r\r',
        "initial": '# Demo',
    },
    '0430l_pwd': {
        "description": ':pwd Print Directory',
        "keys": '::pwd\r',
        "initial": '# Demo\nprint("hello")',
    },
    '0430m_file_info': {
        "description": 'Ctrl-G / :file File Info',
        "keys": 'jj\x07::file\r',
        "initial": '# Demo\nprint("hello")\nprint("world")\nx = 42\ny = 99',
    },
    '0431_v_charwise': {
        "description": 'v — Charwise',
        "keys": 'j0vwe$j\x1b0v/ff\n\x1b',
        "initial": '# palette\nred = "#ff0000"\ngreen = "#00ff00"\nblue = "#0000ff"\nyellow = "#ffff00"\ncyan = "#00ffff"',
    },
    '0432_V_linewise': {
        "description": 'V — Linewise',
        "keys": '2jVjjdu',
        "initial": '# menu items\npizza = 12\nburger = 10\nsalad = 8\nsoup = 6\nbread = 3\ncake = 7',
    },
    '0433_ctrl_v_blockwise': {
        "description": 'Ctrl-V — Blockwise',
        "keys": 'j$b\x16jjjjldu',
        "initial": '# scores\nalice = 95\nbobby = 88\ncarol = 76\ndavid = 82\nelena = 91',
    },
    '0434_o_other_end': {
        "description": 'o — Other End',
        "keys": '2jVjjoko\x1bgg0jwveo\x1b',
        "initial": '# data range\nalpha = 10\nbeta = 20\ngamma = 30\ndelta = 40\nepsilon = 50',
    },
    '0435_O_other_corner_block': {
        "description": 'O — Other Corner (Block)',
        "keys": '2j012l\x16jlO4hok4loj\x1b',
        "initial": '# grid data\nrow1 = [10, 20, 30]\nrow2 = [40, 50, 60]\nrow3 = [70, 80, 90]\nrow4 = [11, 22, 33]',
    },
    '0436_gv_reselect': {
        "description": 'gv — Reselect',
        "keys": '2jVjj>gv>uugg0jwve\x1bgv\x1b',
        "initial": '# config\nhost = "localhost"\nport = 8080\ndebug = True\nlog = "info"\nretry = 3',
    },
    '0437_v_d_v_c': {
        "description": 'Visual Delete/Change',
        "keys": 'jwwwv/demo\recproduction backup\x1b',
        "initial": '# launch note\nPlease replace the old staging setup\nbefore the demo, then notify QA.',
    },
    '0438_v_y': {
        "description": 'Visual Yank',
        "keys": '/payment\rv/worker\reyG$A \x1bp',
        "initial": '# incident note\nImpact: payment webhooks were delayed\nfor EU merchants during deploy 42\nuntil the retry worker caught up.\n\nSummary:',
    },
    '0439_v_r': {
        "description": 'Visual Replace',
        "keys": 'jf"vi"r*ujf"vi"rxu',
        "initial": '# secrets\npassword = "hunter42"\napi_key = "abc123def"\ntoken = "xyz789"',
    },
    '0440_v_J': {
        "description": 'Visual Join',
        "keys": 'vipJ',
        "initial": 'The retry worker\ncaught up after the deploy\nand payment webhooks are current.\n\nKeep this line separate.',
    },
    '0441_v_u_U_tilde': {
        "description": 'v_u / v_U / v_~ — Case',
        "keys": 'jf"vi"Uujf"vi"uujf"vi"~u',
        "initial": '# team names\nalpha = "Red Team"\nbeta = "Blue Team"\ngamma = "Green Team"',
    },
    '0442_v_indent': {
        "description": 'v_> / v_< / v_= — Indent',
        "keys": 'jVjj>5jVj<uuggVG=',
        "initial": '{\n"name": "alice",\n"age": 30,\n"items": [\n"apple",\n"banana",\n            "cherry",\n            "date"\n]\n}',
    },
    '0442a_v_p': {
        "description": 'v_p — Replace Selection',
        "keys": 'jf"yi"jf"vi"pjf"vi"puu',
        "initial": '# colors\nfirst = "red"\nsecond = "blue"\nthird = "green"',
    },
    '0443_block_insert': {
        "description": 'Block Insert',
        "keys": 'j0\x164jIitem_\x1buj0\x164jI# \x1bu',
        "initial": '# items\nsword = 10\nshield = 15\npotion = 5\narrow = 2\nhelmet = 12',
    },
    '0444_block_append': {
        "description": 'Block Append',
        "keys": 'j0\x164j$A  # base\x1bu',
        "initial": '# stats\nhp = 100\nmp = 50\natk = 25\ndef_ = 30\nspd = 15',
    },
    '0444a_block_dollar': {
        "description": 'Block $ — Extend to EOL',
        "keys": 'j0\x164j$A  # ok\x1bu',
        "initial": '# data\nshort = 1\nmedium_var = 200\nlong_variable = 30000\nx = 5\ntiny = 99',
    },
    '0445_visual_range': {
        "description": ":'<,'> — Visual Range",
        "keys": '2jVjj:s/=/::/g\ru3j0Vj:sort\ru',
        "initial": '# fruit prices\napple = 1\nbanana = 2\ncherry = 3\ndate = 4\npear = 5\nfig = 6',
    },
    '0446_q_colon': {
        "description": 'q: — Command History Window',
        "keys": ':set number\r:%s/1/100/\r:set cursorline\rq:kk\r',
        "initial": '# colors\nred = 1\ngreen = 2\nblue = 3\nyellow = 4\npurple = 5',
    },
    '0447_q_slash': {
        "description": 'q/ q? — Search History',
        "keys": '/cat\r/bird\r/frog\rq/kk\r',
        "initial": '# animals\ncat = "meow"\ndog = "woof"\nbird = "chirp"\nfish = "blub"\ncow = "moo"\nfrog = "ribbit"',
    },
    '0448_ctrl_d_completions': {
        "description": 'Ctrl-D — Show Completions',
        "keys": ':se\x04\x1b:set nu\x04\x1b',
        "initial": '# demo\nprint("hello")\nprint("world")\nx = 42',
    },
    '0449_tab_complete': {
        "description": 'Tab — Complete Command',
        "keys": ':set\t nu\t\t\t\x1b:e \t\x1b',
        "initial": '# world\nprint("world")',
    },
    '0450_ctrl_r_register': {
        "description": 'Ctrl-R {reg} — Insert Register',
        "keys": 'j0"ayiw:%s/\x12a/new_name/g\r',
        "initial": '# data\nold_name = "alpha"\nold_name = "beta"\nold_name = "gamma"\nresult = old_name',
    },
    '0451_ctrl_r_ctrl_w': {
        "description": 'Ctrl-R Ctrl-W — Insert Word',
        "keys": 'j0:%s/\x12\x17/max_width/g\r',
        "initial": '# config\nwidth = 800\nheight = 600\ntimeout = 30\nwidth = 1024\nwidth = 640',
    },
    '0452_ctrl_b_ctrl_e': {
        "description": 'Ctrl-B / Ctrl-E — Start/End',
        "keys": ':s/foo/bar\x02%\x05/g\r',
        "initial": '# demo\nfoo = "foo"\nother = "foo"\nmessage = "foo foo"',
    },
    '0453_ctrl_u_clear': {
        "description": 'Ctrl-U — Clear Line',
        "keys": ':%s/alpha/omega/g\x15set number\r',
        "initial": '# demo\nalpha = 1\nbeta = 2\ngamma = 3',
    },
    '0454_ctrl_w_delete_word': {
        "description": 'Ctrl-W — Delete Word',
        "keys": ':set cursroline\x17cursorline\r:echo hello world oops\x17\x17\x1b',
        "initial": '# demo\none = 1\ntwo = 2\nthree = 3',
    },
    '0455_up_down_history': {
        "description": 'Up/Down — History',
        "keys": ':set number\r:%s/10/99/\r:set cursorline\r:%s/8/88/\r:upupupdown\x1b:setupup\x1b',
        "initial": '# items\nsword = 10\nshield = 8\npotion = 5\narrow = 2\nbow = 7',
    },
    '0456_at_colon': {
        "description": '@: — Repeat Last Command',
        "keys": ':$d\r@:@@@@',
        "initial": '# lines\na = 1\nb = 2\nc = 3\nd = 4\ne = 5\nf = 6',
    },
    '0457_norm': {
        "description": ':norm — Normal on Lines',
        "keys": ':%norm I# \ru:%norm A;\ru:2,4norm I# \r',
        "initial": 'x = 1\ny = 2\nz = 3\nw = 4\nv = 5',
    },
    '0458_global': {
        "description": ':g/{pattern}/{cmd} — Global',
        "keys": '::g/TODO/d\ru::g/TODO/p\r::g/TODO/norm IDONE \r',
        "initial": '# task list\nbuy milk\nTODO fix bug\nwalk dog\nTODO write tests\nclean desk\nTODO update docs\nread book',
    },
    '0459_inverse_global': {
        "description": ':v/{pattern}/{cmd} — Inverse Global',
        "keys": '::v/ERROR/d\ru::v/INFO/d\ru',
        "initial": 'INFO server started\nERROR disk full\nINFO user login\nWARN slow query\nINFO page loaded\nERROR timeout\nINFO task done',
    },
    '0460_ctrl_f_edit_command': {
        "description": 'Ctrl-F — Edit Command',
        "keys": ':%s/foo/bar/g\x06Fbciwbaz\x1b\r',
        "initial": '# sample\nfoo = 1\nbar = 2\nbaz = 3\nqux = 4',
    },
    '0461_xp_transpose': {
        "description": 'xp — Transpose Characters',
        "keys": 'lxpj0fsxpj0llxp',
        "initial": 'teh quick brown fox\njumsp over the fence\nwiht great speed',
    },
    '0462_deep': {
        "description": 'deep — A Vim Myth',
        "keys": 'deepyiwep',
        "initial": 'hello',
    },
    '0463_ddp_swap_lines_down': {
        "description": 'ddp — Swap Lines Down',
        "keys": 'ddp2u2jddp',
        "initial": 'first\nsecond\nthird\nfourth\nfifth',
    },
    '0464_ddP_swap_lines_up': {
        "description": 'ddkP — Swap Lines Up',
        "keys": '2jddkP2ujddkP',
        "initial": 'first\nsecond\nthird\nfourth\nfifth',
    },
    '0465_yyp_duplicate_line': {
        "description": 'yyp — Duplicate Line',
        "keys": 'yypciwname\x1bf"ci"myapp\x1b',
        "initial": 'host = "localhost"\nport = 8080\ndebug = True',
    },
    '0466_star_dot_pattern': {
        "description": 'Star-Dot Pattern',
        "keys": '*cwbar\x1bn.n.n.',
        "initial": 'foo = get_foo()\nprint(foo)\nif foo > 0:\n    save(foo)\nlog(foo)',
    },
    '0467_norm_comment': {
        "description": ':%norm I// — Comment All Lines',
        "keys": ':%norm I//\ru:2,4norm I//\r',
        "initial": 'let x = 1;\nlet y = 2;\nlet z = x + y;\nconsole.log(z);\nreturn z;',
    },
    '0468_norm_delete_first': {
        "description": ':%norm ^x — Delete First Char',
        "keys": ':%norm ^x\ru:%norm 0xx\r',
        "initial": '#alpha\n#beta\n#gamma\n#delta\n#epsilon',
    },
    '0469_visual_block_comment': {
        "description": 'Visual Block Comment',
        "keys": 'j\x16jjI//\x1b',
        "initial": 'let a = 1;\nlet b = 2;\nlet c = 3;\nlet d = 4;\nlet e = 5;',
    },
    '0470_ctrl_a_ctrl_x': {
        "description": 'Ctrl-A / Ctrl-X — Increment & Decrement',
        "keys": '\x01\x183j5\x01',
        "initial": 'item 1\nitem 10\nitem 100\nport 8080\nversion 3',
    },
    '0471_g_ctrl_a': {
        "description": 'g Ctrl-A / g Ctrl-X — Sequences',
        "keys": 'VGg\x01uVGg\x18',
        "initial": '0. apple\n0. banana\n0. cherry\n0. date\n0. elderberry',
    },
    '0472_align_with_norm': {
        "description": 'Align Text with Substitute',
        "keys": "VG:s/\\s*=/\\=repeat(' ',6-col('.')).'='/\r\r",
        "initial": 'name = Alice\nage = 30\ncity = Portland\nrole = engineer\nid = 42',
    },
    '0473_underscore_key': {
        "description": 'The Useless _ Key',
        "keys": 'j$_$^',
        "initial": 'def greet():\n    name = "world"\n    print(f"hello {name}")\n    return True',
    },
    '0474_record_apply_macro': {
        "description": 'Record-and-Apply Macro',
        "keys": 'qa0i"\x1bf,i"\x1bq2u::%norm @a\r',
        "initial": 'alice,30\nbob,25\ncharlie,35\ndiana,28\neve,32',
    },
    '0475_ctrl_o_insert': {
        "description": 'Ctrl-O in Insert Mode',
        "keys": 'A today\x0f2j\x0fdd',
        "initial": 'hello world\nthis is a test\nremove this line\nkeep typing here',
    },
    '0476_map_Y': {
        "description": 'Map Y to y$',
        "keys": 'wY:map Y y$\r0wYo\x1bp',
        "initial": 'hello beautiful world\nfoo bar baz\none two three',
    },
    '0477_gn_with_dot': {
        "description": 'gn with Dot',
        "keys": '/old\rcgnnew\x1b....',
        "initial": 'old = get_old()\nprint(old)\nif old > 0:\n    save(old)\nlog(old)',
    },
    '0478_numbered_register_put': {
        "description": 'Numbered Register Put',
        "keys": 'ddddddG"1pu.u.',
        "initial": 'alpha\nbravo\ncharlie\ndelta\necho\nfoxtrot',
    },
    '0479_do_dp_diff': {
        "description": 'do / dp — Diff Obtain & Put',
        "keys": 'jdo2jdp',
        "initial": 'alpha\nBRAVO\ncharlie\nDELTA',
    },
    '0480_external_filtering': {
        "description": 'External Filtering',
        "keys": '!ipsort\r}j!ipsort\r',
        "initial": 'cherry\napple\nbanana\ndate\nelderberry\n\ngrape\nfig\nkiwi',
    },
    '0481_undo_branches': {
        "description": 'Undo Branches',
        "keys": 'A one\x1bA two\x1buA three\x1bug-g+',
        "initial": 'hello world',
    },
    '0482_earlier_later': {
        "description": ':earlier / :later',
        "keys": 'ione\x07u two\x07u three\x1b::earlier 2\r\r\x0c::later 2\r\r\x0c',
        "initial": '',
    },
    '0483_dot_register': {
        "description": 'The . Register',
        "keys": 'A Alice\x1b:echo @.\rj$".p',
        "initial": 'Name:\nAddress:\nCity:',
    },
    '0484_colon_register': {
        "description": 'The : Register',
        "keys": '::%s/two/TWO/g\rGoLast command: \x12:\x1b',
        "initial": 'one\ntwo\nthree\nfour\nfive',
    },
    '0485_slash_register': {
        "description": 'The / Register',
        "keys": '/fox\r:echo @/\r:%s//wolf/g\r',
        "initial": 'The fox jumped over\nthe lazy dog and\nthe fox ran away',
    },
    '0487_hash_register': {
        "description": 'The # Register',
        "keys": ':edit second.txt\r:echo @#\r\x1e',
        "initial": 'I am the second file.',
    },
    '0488_equals_register': {
        "description": 'The = Register',
        "keys": 'A \x12=6*7\r\x1bjA \x12=12*5\r\x1b',
        "initial": 'The answer is:\nItems: 12 * 5 =',
    },
    '0489_operator_pending': {
        "description": 'Operator-Pending Mode',
        "keys": 'dwc\x1bjf[ci[replaced\x1b',
        "initial": 'delete this word here\nchange [inside] these\nyank (some parenthesized) text',
    },
    '0490_g_at_custom_operator': {
        "description": 'g@ — Custom Operator',
        "keys": ":function! Upcase(type)\r  '[,']s/.\\+/\\U&/g\rendfunction\r:set operatorfunc=Upcase\rg@iwjg@_",
        "initial": 'hello world\nfoo bar baz\nquick brown fox',
    },
    '0492_ga_g8_char_info': {
        "description": 'ga / g8 — Character Info',
        "keys": 'ga\rjga\rjga\rg8\r',
        "initial": 'A\n~\n€',
    },
    '0493_fold_by_indent': {
        "description": ':set fdm=indent — Fold by Indent',
        "keys": ':set foldmethod=indent\rjzozczRzM',
        "initial": 'def greet(name):\n    msg = f"Hello {name}"\n    print(msg)\n    return msg\n\ndef farewell(name):\n    msg = f"Bye {name}"\n    print(msg)\n    return msg\n\ndef main():\n    greet("Alice")\n    farewell("Bob")',
    },
    '0494_fold_by_syntax': {
        "description": ':set fdm=syntax — Fold by Syntax',
        "keys": ':set foldmethod=syntax\rzMgg2jzozR',
        "initial": '#include <stdio.h>\n\nint add(int a, int b) {\n    return a + b;\n}\n\nint main() {\n    int x = add(3, 4);\n    printf("%d\\n", x);\n    return 0;\n}',
    },
    '0495_mkview_loadview': {
        "description": ':mkview / :loadview — Save Folds',
        "keys": ':set foldmethod=indent shiftwidth=2\rzM3jzo:mkview\rzR:loadview\r',
        "initial": 'Section One\n  detail a\n  detail b\n  detail c\nSection Two\n  item x\n  item y\nSection Three\n  note 1\n  note 2\n  note 3',
    },
    '0496_gx_open_url': {
        "description": 'gx — Open URL',
        "keys": 'j0gx',
        "initial": 'Opened by gx\n\nThis is a local file.',
    },
    '0497_g_less_previous_output': {
        "description": 'g< — Previous Output',
        "keys": '::version\r\rg<\r',
        "initial": 'one\ntwo\nthree\nfour\nfive',
    },
    '0498_vimrc_init_lua': {
        "description": 'The vimrc / init.lua',
        "keys": '::edit init.lua\r::edit config.txt\r::luafile init.lua\r',
        "initial": 'vim.opt.number = true\nvim.opt.relativenumber = true\nvim.opt.cursorline = true',
    },
    '0499_help_system': {
        "description": ':help — The Help System',
        "keys": ':help\r:q\r:help dd\r',
        "initial": 'Learning Vim Help',
    },
}

SKIPPED = {
    '0419_shell_command': ['shell escape (:!)'],
    '0420_repeat_shell': ['shell escape (:!)'],
    '0421_filter': ['shell escape (:!)'],
    '0422_terminal': [':term'],
    '0486_percent_register': ['shell escape (:!)'],
    '0491_terminal_mode': [':term'],
}
