"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0601_useless_underscore': {
        "description": 'Useless Underscore Remap',
        "keys": '::nnoremap _ i <Esc>\rj0w__j0w_',
        "initial": 'name   Alice\nrole Dev\ncity  Paris',
    },
    '0700_what_is_surround': {
        "description": 'What Is Surround?',
        "keys": 'f"ds"ysiw\'jf(cs)]j0wwysiw)j0wwysiwtem>\r',
        "initial": 'title = "hello"\ncoords = (10, 20)\nflag = enabled\nlabel = important',
    },
}
