"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0201_the_paren_keys': {
        "description": 'The ( and ) Keys',
        "keys": ')))((',
        "initial": '# The hero woke up. The sun was\n# bright. Birds were singing.\n#\n# She grabbed her sword. The\n# quest was urgent. No time to\n# waste. She ran toward the gate.',
    },
    '0202_the_brace_keys': {
        "description": 'The { and } Keys',
        "keys": '}}}{{',
        "initial": 'hp = 100\nmp = 50\nspeed = 12\n\nsword = "iron"\nshield = "oak"\nhelm = "steel"\n\nquest = "dragon"\nreward = "gold"\nstatus = "active"',
    },
    '0203_the_bracket_keys': {
        "description": 'The [ and ] Keys',
        "keys": ']]]][[[[',
        "initial": 'void attack() {\n    int dmg = 10;\n}\n\nvoid defend() {\n    int armor = 5;\n}\n\nvoid heal() {\n    int hp = 20;\n}',
    },
    '0204_the_minus_plus_keys': {
        "description": 'The - and + Keys',
        "keys": '+++--',
        "initial": 'class Settings:\n    debug = True\n    volume = 80\n    lang = "en"\n    fps = 60\n    vsync = False',
    },
    '0205_the_underscore_key': {
        "description": 'The _ Key',
        "keys": '$_3_4_',
        "initial": 'inventory = [\n    "sword",\n    "shield",\n    "potion",\n    "scroll",\n    "ring",\n]',
    },
    '0206_the_equals_key': {
        "description": 'The = Key',
        "keys": 'j==gg=G',
        "initial": 'int main() {\nint x = 5;\nif (x > 0) {\nprintf("yes");\n}\nreturn 0;\n}',
    },
    '0207_the_angle_bracket_keys': {
        "description": 'The Angle Bracket Keys',
        "keys": 'j>><<>j',
        "initial": 'def attack(hero):\n    damage = hero.atk\n    crit = damage * 2\n    return crit',
    },
    '0208_the_pipe_key': {
        "description": 'The | Key',
        "keys": '12|21|28||',
        "initial": '# name     class    level  hp\n# ----     -----    -----  --\n# kai      warrior  12     340\n# luna     mage     15     180\n# rex      rogue    10     220',
    },
    '0209_the_backslash_key': {
        "description": 'The \\ Key (Leader)',
        "keys": ':nnoremap \\w :w<CR>\n\\w:nnoremap \\n :set nu!<CR>\n\\n\\n:nnoremap \\d dd\nj\\d',
        "initial": 'hero = "Knight"\nlevel = 12\nhp = 340\nweapon = "sword"\nshield = True',
    },
    '0210_the_colon_key': {
        "description": 'The : Key',
        "keys": ':set number\r:s/hero/knight\r:5\r',
        "initial": 'name = "hero"\nhp = 100\nmp = 50\nlevel = 1\nname = "hero"\ngold = 0',
    },
    '0211_the_semicolon_key': {
        "description": 'The ; Key',
        "keys": 'f/;;;',
        "initial": 'route = "/home/user/docs/work/notes"',
    },
    '0212_the_comma_key': {
        "description": 'The , Key',
        "keys": 'f/;;,,',
        "initial": 'route = "/home/user/docs/work/notes"',
    },
    '0213_the_quote_key': {
        "description": 'The " Key',
        "keys": '"ayyj"byy2j"ap"bp',
        "initial": 'sword = 10\nshield = 5\n\nloadout:',
    },
    '0214_the_dot_key': {
        "description": 'The . Key',
        "keys": 'f"ci"blue\x1b/red\r.n.',
        "initial": 'color = "red"\nsize = "big"\ntone = "red"\nmood = "calm"\ntint = "red"',
    },
    '0215_the_slash_key': {
        "description": 'The / Key',
        "keys": '/dragon\r/er\rnn',
        "initial": 'town = "haven"\nforest = "darkwood"\ncave = "crystal"\nriver = "silver"\npeak = "thunder"\nlake = "mirror"\nruins = "ancient"\nfort = "dragon"',
    },
    '0216_the_question_key': {
        "description": 'The ? Key',
        "keys": 'G?crystal\r?haven\r',
        "initial": 'town = "haven"\nforest = "darkwood"\ncave = "crystal"\nriver = "silver"\npeak = "thunder"\nlake = "mirror"\nruins = "ancient"\nfort = "dragon"',
    },
    '0217_the_space_key': {
        "description": 'The Space Key',
        "keys": '    ',
        "initial": 'spell = "fireball"',
    },
    '0218_the_backspace_key': {
        "description": 'The Backspace Key',
        "keys": '$\x7f\x7f\x7f\x7f',
        "initial": 'spell = "fireball"',
    },
    '0219_ctrl_a': {
        "description": 'Ctrl-A',
        "keys": '\x01j05\x01j0\x01',
        "initial": 'hp = 50\nlevel = 3\nspeed = 10',
    },
    '0220_ctrl_x': {
        "description": 'Ctrl-X',
        "keys": '\x18j05\x18j0\x18',
        "initial": 'lives = 9\narmor = 20\nround = 100',
    },
    '0221_ctrl_b': {
        "description": 'Ctrl-B',
        "keys": '\x02\x02\x06',
        "initial": '# Quest Log\n\nhero = "Aria"\nlevel = 12\nhp = 85\nmp = 40\nxp = 0\ngold = 100\n\ndef enter_forest():\n    print("Shadows close in")\n    enemies = ["wolf", "bat", "troll"]\n    for e in enemies:\n        print(f"A wild {e} appears!")\n    print("Forest cleared")\n\ndef enter_cave():\n    print("Dripping water echoes")\n    traps = ["spike pit", "falling rocks"]\n    for trap in traps:\n        print(f"Watch out: {trap}!")\n    print("Cave explored")\n\ndef find_treasure():\n    gold = 500\n    gems = ["ruby", "emerald", "diamond"]\n    print(f"Found {gold} gold")\n    for g in gems:\n        print(f"Found a {g}!")\n    print("Inventory full")\n\ndef boss_fight():\n    boss_hp = 200\n    boss_name = "Dragon King"\n    print(f"{boss_name} attacks!")\n    while boss_hp > 0:\n        boss_hp -= 25\n        print(f"{boss_name}: {boss_hp} HP")\n    print("Victory!")\n\ndef level_up(hero):\n    hero["level"] += 1\n    hero["hp"] += 20\n    hero["mp"] += 10\n    print(f"Level {hero[\'level\']}!")\n\ndef save_game():\n    data = {"hero": hero, "level": level}\n    print("Game saved.")\n    return True\n\ndef load_game():\n    print("Loading save...")\n    return {"hero": "Aria", "level": 12}',
    },
    '0222_ctrl_f': {
        "description": 'Ctrl-F',
        "keys": '\x06\x06\x02',
        "initial": '# Dungeon Crawler\n\nclass Room:\n    def __init__(self, name):\n        self.name = name\n        self.items = []\n        self.enemies = []\n\n    def describe(self):\n        print(f"You enter {self.name}")\n        for item in self.items:\n            print(f"  You see: {item}")\n\n    def add_enemy(self, enemy):\n        self.enemies.append(enemy)\n        print(f"{enemy} lurks here")\n\nclass Player:\n    def __init__(self):\n        self.hp = 100\n        self.inventory = []\n        self.position = (0, 0)\n\n    def take_damage(self, amount):\n        self.hp -= amount\n        print(f"Ouch! HP: {self.hp}")\n\n    def heal(self, amount):\n        self.hp += amount\n        print(f"Healed! HP: {self.hp}")\n\n    def pickup(self, item):\n        self.inventory.append(item)\n        print(f"Got {item}!")',
    },
    '0223_ctrl_u': {
        "description": 'Ctrl-U',
        "keys": '\x15\x15\x15',
        "initial": '# Spell Book\n\ndef fireball(target):\n    damage = 40\n    print(f"{target} takes {damage}")\n    return damage\n\ndef ice_wall(duration):\n    print(f"Wall lasts {duration}s")\n    return True\n\ndef heal(target, amount):\n    target.hp += amount\n    print(f"Healed {amount} HP")\n\ndef lightning(targets):\n    for t in targets:\n        print(f"Zap! {t} stunned")\n\ndef shield(caster):\n    caster.armor += 10\n    print("Shield up!")\n\ndef teleport(x, y):\n    print(f"Warped to ({x}, {y})")\n    return (x, y)\n\ndef summon(creature):\n    print(f"{creature} appears!")\n    return creature\n\ndef curse(target):\n    target.speed -= 5\n    print(f"{target} slowed!")',
    },
    '0224_ctrl_d': {
        "description": 'Ctrl-D',
        "keys": '\x04\x04\x04\x15',
        "initial": '# Loot Table\n\ncommon = [\n    "wooden sword",\n    "cloth hat",\n    "torn map",\n    "rusty key",\n]\n\nuncommon = [\n    "silver dagger",\n    "leather boots",\n    "health potion",\n    "fire scroll",\n]\n\nrare = [\n    "enchanted bow",\n    "mithril shield",\n    "dragon scale",\n    "void crystal",\n]\n\nlegendary = [\n    "excalibur",\n    "phoenix feather",\n    "time amulet",\n    "shadow cloak",\n]\n\ndef roll_loot(luck):\n    if luck > 90:\n        return legendary\n    if luck > 60:\n        return rare\n    return common',
    },
    '0225_ctrl_e': {
        "description": 'Ctrl-E',
        "keys": '9j\x05\x05\x055\x055\x19',
        "initial": '# Robot Controller\n\nname = "T-800"\nmodel = "Series 800"\ncpu = "Neural Net"\n\ndef boot():\n    print("Systems online")\n    calibrate_sensors()\n    load_mission()\n\ndef calibrate_sensors():\n    sensors = ["lidar", "camera"]\n    for s in sensors:\n        print(f"{s}: OK")\n\ndef load_mission():\n    target = "protect"\n    priority = "high"\n    print(f"Mission: {target}")\n\ndef patrol(area):\n    print(f"Scanning {area}")\n    threats = detect_threats()\n    return len(threats)\n\ndef detect_threats():\n    return ["intruder", "drone"]\n\ndef shutdown():\n    print("Powering down...")\n    save_state()\n\ndef save_state():\n    print("State saved.")',
    },
    '0226_ctrl_y': {
        "description": 'Ctrl-Y',
        "keys": '9k\x19\x19\x195\x19',
        "initial": '# Pizza Order System\n\ntoppings = [\n    "pepperoni",\n    "mushrooms",\n    "onions",\n    "sausage",\n    "bell pepper",\n    "olives",\n    "pineapple",\n]\n\nsizes = {\n    "small": 8.99,\n    "medium": 12.99,\n    "large": 15.99,\n    "xl": 19.99,\n}\n\ndef calculate_price(size, extras):\n    base = sizes[size]\n    extra_cost = len(extras) * 1.50\n    return base + extra_cost\n\ndef format_order(name, size, tops):\n    total = calculate_price(size, tops)\n    print(f"Order for {name}")\n    print(f"Size: {size}")\n    for t in tops:\n        print(f"  + {t}")\n    print(f"Total: ${total:.2f}")',
    },
    '0227_ctrl_o': {
        "description": 'Ctrl-O',
        "keys": 'G\x0f/play\r\x0f',
        "initial": '# Cat Behavior Simulator\n\nclass Cat:\n    def __init__(self, name):\n        self.name = name\n        self.mood = "sleepy"\n        self.hunger = 50\n\n    def feed(self, food):\n        self.hunger -= 10\n        print(f"{self.name} eats")\n\n    def pet(self):\n        if self.mood == "angry":\n            print("Hiss!")\n        else:\n            print("Purr...")\n\n    def nap(self):\n        self.mood = "sleepy"\n        print(f"{self.name} naps")\n\n    def play(self, toy):\n        self.mood = "happy"\n        self.hunger += 5\n        print(f"Chasing {toy}!")',
    },
    '0228_ctrl_i': {
        "description": 'Ctrl-I / Tab',
        "keys": 'G/Shields\r\x0f\x0f\t\t',
        "initial": '# Starship Control\n\nclass Engine:\n    def __init__(self):\n        self.fuel = 100\n        self.speed = 0\n\n    def throttle(self, pct):\n        self.speed = pct\n        self.fuel -= pct * 0.1\n\n    def brake(self):\n        self.speed = 0\n\nclass Shields:\n    def __init__(self):\n        self.power = 100\n\n    def absorb(self, damage):\n        self.power -= damage\n\n    def recharge(self):\n        self.power = 100\n\ndef launch(ship):\n    ship.throttle(50)\n    print("Launched!")',
    },
    '0229_ctrl_r': {
        "description": 'Ctrl-R',
        "keys": 'dddduu\x12\x12',
        "initial": 'score = 0\nlives = 3\nlevel = 1',
    },
    '0230_ctrl_g': {
        "description": 'Ctrl-G',
        "keys": '\x078G\x07G\x07',
        "initial": '# Weather Station\n\ntemp = 72\nhumidity = 45\nwind = 12\ncondition = "sunny"\n\ndef forecast():\n    if temp > 80:\n        return "hot"\n    if temp < 50:\n        return "cold"\n    return "nice"\n\ndef alert(msg):\n    print(f"ALERT: {msg}")',
    },
    '0231_ctrl_l': {
        "description": 'Ctrl-L',
        "keys": '\x0c\x0c',
        "initial": '# Display Manager\n\ndef refresh():\n    print("Redrawing screen")\n    clear_buffer()\n    render_frame()\n\ndef clear_buffer():\n    print("Buffer cleared")\n\ndef render_frame():\n    print("Frame rendered")',
    },
    '0232_ctrl_v': {
        "description": 'Ctrl-V',
        "keys": 'f"\x164j\x1bgg0f"\x164j$du',
        "initial": 'host  = "localhost"\nport  = "8080"\nmode  = "debug"\nlang  = "python"\nteam  = "alpha"',
    },
    '0233_ctrl_c': {
        "description": 'Ctrl-C',
        "keys": 'd\x03i# \x03:set number\x03',
        "initial": 'mission = "active"\nstatus = "go"\nalert = "none"',
    },
    '0235_ctrl_right_bracket': {
        "description": 'Ctrl-]',
        "keys": 'Gkw\x1d\x14',
        "initial": 'def start():\n    print("Engine started")\n\ndef stop():\n    print("Engine stopped")\n\ndef main():\n    start()\n    stop()',
    },
    '0236_ctrl_t': {
        "description": 'Ctrl-T',
        "keys": 'Gkw\x1dj^\x1d\x14\x14',
        "initial": 'def aim():\n    print("Targeting...")\n\ndef fire():\n    aim()\n    print("BOOM!")\n\ndef reload():\n    print("Reloading...")\n\ndef defend():\n    fire()\n    reload()',
    },
    '0237_ctrl_caret': {
        "description": 'Ctrl-^',
        "keys": '\x1e\x1e\x1e',
        "initial": 'name = "Malachar"\nrole = "sorcerer"\nhp = 80',
    },
    '0238_ctrl_w': {
        "description": 'Ctrl-W Prefix',
        "keys": '\x17s\x17w\x17c',
        "initial": '# Dashboard\n\ntitle = "Mission Control"\nstatus = "online"\nalerts = 0\nuptime = 99.9',
    },
    '0239_ctrl_n_p': {
        "description": 'Ctrl-N / Ctrl-P',
        "keys": '\x0e\x0e\x103\x0e',
        "initial": 'pilot = "Kai"\ngunner = "Rex"\nmedic = "Nova"\nengineer = "Bolt"\ncaptain = "Vex"',
    },
    '0240_ctrl_h': {
        "description": 'Ctrl-H',
        "keys": '$\x08\x08\x082jA\x08\x08\x1bu',
        "initial": 'row = "ABCDEFGH"\ncol = "12345678"\npos = "E4"',
    },
    '0241_ctrl_j_m': {
        "description": 'Ctrl-J / Ctrl-M',
        "keys": '\n\n\ngg\r\r\rgg$\nk\r',
        "initial": 'class Robot:\n    name = "Spark"\n    speed = 88\n    fuel = 100\n    armed = True\n\ndef launch(bot):\n    if bot.fuel > 0:\n        print("Go!")',
    },
    '0242_zz_center': {
        "description": 'zz Center Cursor',
        "keys": '15Gzz30Gzz',
        "initial": '# Tower Defense\nimport math\n\nclass Tower:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n        self.level = 1\n        self.range = 5\n        self.damage = 10\n\n    def upgrade(self):\n        self.level += 1\n        self.range += 2\n        self.damage *= 1.5\n\n    def can_hit(self, enemy):\n        dist = math.sqrt(\n            (self.x - enemy.x) ** 2 +\n            (self.y - enemy.y) ** 2\n        )\n        return dist <= self.range\n\n    def fire(self, enemy):\n        if self.can_hit(enemy):\n            enemy.hp -= self.damage\n            return True\n        return False\n\nclass Enemy:\n    def __init__(self, hp, speed):\n        self.hp = hp\n        self.speed = speed\n        self.x = 0\n        self.y = 0\n\n    def move(self, path):\n        self.x += self.speed\n\n    def is_alive(self):\n        return self.hp > 0',
    },
    '0243_zt_top': {
        "description": 'zt Cursor to Top',
        "keys": '18Gzt4Gzt',
        "initial": '# Battle Arena\nimport random\n\nclass Fighter:\n    def __init__(self, name, hp, atk):\n        self.name = name\n        self.hp = hp\n        self.atk = atk\n        self.alive = True\n\n    def attack(self, target):\n        dmg = random.randint(1, self.atk)\n        target.hp -= dmg\n        if target.hp <= 0:\n            target.alive = False\n        return dmg\n\nclass Arena:\n    def __init__(self):\n        self.fighters = []\n        self.round = 0\n\n    def add(self, fighter):\n        self.fighters.append(fighter)\n\n    def battle(self):\n        self.round += 1\n        alive = [f for f in self.fighters\n                 if f.alive]\n        if len(alive) < 2:\n            return alive[0] if alive else None\n        a, b = random.sample(alive, 2)\n        a.attack(b)\n        return None\n\n    def champion(self):\n        alive = [f for f in self.fighters\n                 if f.alive]\n        return alive[0].name if alive else None',
    },
    '0244_zb_bottom': {
        "description": 'zb Cursor to Bottom',
        "keys": '23Gzbzzztzb',
        "initial": "# Quest Tracker\nimport json\n\nclass Quest:\n    def __init__(self, name, reward):\n        self.name = name\n        self.reward = reward\n        self.done = False\n\n    def complete(self):\n        self.done = True\n        return self.reward\n\nclass Hero:\n    def __init__(self, name):\n        self.name = name\n        self.gold = 0\n        self.quests = []\n\n    def accept(self, quest):\n        self.quests.append(quest)\n\n    def finish(self, quest):\n        gold = quest.complete()\n        self.gold += gold\n\n    def active_quests(self):\n        return [q for q in self.quests\n                if not q.done]\n\n    def completed_quests(self):\n        return [q for q in self.quests\n                if q.done]\n\ndef load_quests(path):\n    with open(path) as f:\n        data = json.load(f)\n    return [Quest(q['name'], q['reward'])\n            for q in data]",
    },
    '0245_z_dot': {
        "description": 'z. Center First Non-Blank',
        "keys": '23G$z.34G$zzz.',
        "initial": '# Weapon Forge\nimport random\n\nclass Material:\n    def __init__(self, name, strength):\n        self.name = name\n        self.strength = strength\n\nclass Weapon:\n    def __init__(self, name, material):\n        self.name = name\n        self.material = material\n        self.enchant = None\n        self.durability = 100\n\n    def apply_enchant(self, spell):\n        self.enchant = spell\n        self.durability -= 10\n\n    def repair(self):\n        self.durability = 100\n\nclass Forge:\n    def __init__(self):\n        self.fuel = 100\n        self.queue = []\n\n    def smelt(self, material):\n        self.fuel -= 20\n        return material.strength * 2\n\n    def craft(self, name, material):\n        power = self.smelt(material)\n        weapon = Weapon(name, material)\n        return weapon\n\n    def batch_craft(self, orders):\n        results = []\n        for name, mat in orders:\n            w = self.craft(name, mat)\n            results.append(w)\n        return results',
    },
    '0246_z_plus': {
        "description": 'z+ Top First Non-Blank',
        "keys": '26G$z\r37G$ztz\r',
        "initial": '# Dungeon Generator\nimport random\n\nclass Room:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n        self.monsters = []\n        self.loot = []\n\n    def spawn_monster(self, name):\n        self.monsters.append(name)\n\n    def add_loot(self, item):\n        self.loot.append(item)\n\nclass Corridor:\n    def __init__(self, start, end):\n        self.start = start\n        self.end = end\n        self.trapped = False\n\n    def set_trap(self):\n        self.trapped = True\n\nclass Dungeon:\n    def __init__(self, depth):\n        self.depth = depth\n        self.rooms = []\n        self.corridors = []\n\n    def gen_room(self):\n        w = random.randint(3, 10)\n        h = random.randint(3, 8)\n        room = Room(w, h)\n        self.rooms.append(room)\n        return room\n\n    def connect(self, a, b):\n        c = Corridor(a, b)\n        self.corridors.append(c)\n        return c',
    },
    '0247_z_minus': {
        "description": 'z- Bottom First Non-Blank',
        "keys": '28G$z-22G$zbz-',
        "initial": '# Potion Brewery\nimport random\n\nclass Ingredient:\n    def __init__(self, name, potency):\n        self.name = name\n        self.potency = potency\n        self.toxic = False\n\nclass Recipe:\n    def __init__(self, name):\n        self.name = name\n        self.ingredients = []\n        self.brew_time = 0\n\n    def add(self, ingredient, qty):\n        self.ingredients.append(\n            (ingredient, qty))\n        self.brew_time += qty\n\n    def potency(self):\n        total = sum(\n            i.potency * q\n            for i, q in self.ingredients\n        )\n        return total\n\nclass Brewery:\n    def __init__(self):\n        self.recipes = {}\n        self.stock = []\n\n    def register(self, recipe):\n        self.recipes[recipe.name] = recipe\n\n    def brew(self, name):\n        recipe = self.recipes[name]\n        potion = recipe.potency()\n        self.stock.append(potion)\n        return potion',
    },
    '0248_z_height': {
        "description": 'z{height} Enter',
        "keys": '\x17sz12\rz4\r\x17=',
        "initial": "# Guild System\nimport json\n\nclass Member:\n    def __init__(self, name, rank):\n        self.name = name\n        self.rank = rank\n        self.xp = 0\n\n    def promote(self):\n        self.rank += 1\n\nclass Guild:\n    def __init__(self, name):\n        self.name = name\n        self.members = []\n        self.treasury = 0\n\n    def recruit(self, name):\n        m = Member(name, rank=1)\n        self.members.append(m)\n        return m\n\n    def deposit(self, amount):\n        self.treasury += amount\n\n    def top_members(self, n=5):\n        ranked = sorted(\n            self.members,\n            key=lambda m: m.xp,\n            reverse=True\n        )\n        return ranked[:n]\n\n    def save(self, path):\n        data = {\n            'name': self.name,\n            'treasury': self.treasury,\n            'members': len(self.members)\n        }\n        with open(path, 'w') as f:\n            json.dump(data, f)",
    },
    '0249_ga': {
        "description": 'ga ASCII Value',
        "keys": '7G13|ga\r4G12|ga\r3G11|ga\r8G$hga\r',
        "initial": '# Character Chart\nletters = "ABCXYZ"\ndigits = "0123456789"\nsymbols = "@#$%^&*"\nnewline = "\\n"\ntab_char = "\\t"\ngreeting = "Hello, World!"\nemoji = "☺"\npi = 3.14159',
    },
    '0250_gd': {
        "description": 'gd Go to Local Definition',
        "keys": '10G$bgd11Gwwgd',
        "initial": '# Calculator\n\ndef compute_total(items):\n    tax_rate = 0.08\n    subtotal = 0\n    for item in items:\n        price = item[\'price\']\n        qty = item[\'qty\']\n        subtotal += price * qty\n    tax = subtotal * tax_rate\n    total = subtotal + tax\n    return total\n\ndef format_receipt(items):\n    lines = []\n    for item in items:\n        name = item[\'name\']\n        cost = item[\'price\'] * item[\'qty\']\n        lines.append(f"{name}: ${cost}")\n    return \'\\n\'.join(lines)',
    },
    '0251_gD': {
        "description": 'gD Go to Global Definition',
        "keys": '8G$F_gD7GwwgD',
        "initial": '# App Config\nMAX_RETRIES = 3\nTIMEOUT = 30\nBASE_URL = "https://api.example.com"\n\ndef fetch(endpoint):\n    url = BASE_URL + endpoint\n    for attempt in range(MAX_RETRIES):\n        try:\n            resp = request(url, TIMEOUT)\n            return resp\n        except Exception:\n            pass\n    return None\n\ndef request(url, timeout):\n    print(f"GET {url} ({timeout}s)")\n    return {"status": 200}',
    },
    '0252_ge': {
        "description": 'ge End of Previous Word',
        "keys": '$gegegeeegege$3ge',
        "initial": 'the quick brown fox jumps\nover the lazy sleeping dog\nfast cars and slow trains\nred green blue yellow pink',
    },
    '0253_gE': {
        "description": 'gE End of Previous WORD',
        "keys": '$gegege$gE2G$gE',
        "initial": 'file: /usr/local/bin/python3\nurl: https://api.example.com/v2\nemail: user@mail.example.org\ncmd: grep -rn "pattern" src/',
    },
    '0254_gf': {
        "description": 'gf Go to File',
        "keys": '5Gwwgf\x0f',
        "initial": '# Main Application\nimport utils\nfrom utils import clamp\n\n# See utils.py for helpers\n\ndef run():\n    x = clamp(150, 0, 100)\n    print(f"Clamped: {x}")\n\nif __name__ == "__main__":\n    run()',
    },
    '0255_gF': {
        "description": 'gF Go to File at Line',
        "keys": '2Gf.gF\x0f3Gf.gF',
        "initial": 'Build errors:\n  helpers.py:15 ValueError\n  helpers.py:6  missing file\nAll done.',
    },
    '0256_gg': {
        "description": 'gg Go to Top',
        "keys": 'Ggg22gg10gggg',
        "initial": '# Spaceship Simulator\nimport math\n\nclass Ship:\n    def __init__(self, name):\n        self.name = name\n        self.x = 0\n        self.y = 0\n        self.fuel = 100\n        self.speed = 0\n\n    def thrust(self, power):\n        self.speed += power\n        self.fuel -= power * 0.1\n\n    def move(self):\n        self.x += self.speed\n\n    def brake(self):\n        self.speed = max(0, self.speed - 5)\n\nclass Fleet:\n    def __init__(self):\n        self.ships = []\n\n    def add(self, ship):\n        self.ships.append(ship)\n\n    def move_all(self):\n        for ship in self.ships:\n            ship.move()\n\n    def status(self):\n        for s in self.ships:\n            print(f"{s.name}: ({s.x},{s.y})")',
    },
    '0257_gj_gk': {
        "description": 'gj gk Screen Lines',
        "keys": 'jjgggjgjgjgkgk',
        "initial": 'Short line.\nThis is a much longer line that will definitely wrap around the screen because it has so many words in it that forty columns cannot contain it all on one row.\nAnother short line.\nHere is another very long line with lots of text that wraps around multiple times on the display because the terminal is narrow.',
    },
    '0258_gm_gM': {
        "description": 'gm gM Middle of Line',
        "keys": '3G0gmgM1G0gMgm',
        "initial": 'short\nthis is a medium length line here\nabcdefghijklmnopqrstuvwxyz0123456789!!\nhello\nthe quick brown fox jumps over dog',
    },
    '0259_gn_gN': {
        "description": 'gn gN Select Next Match',
        "keys": '/red\rgn\x1bcgncrimson\x1b..',
        "initial": '# Color Palette\nred = "#FF0000"\ngreen = "#00FF00"\nblue = "#0000FF"\nlight_red = "#FF6666"\ndark_red = "#990000"\nsky_blue = "#87CEEB"\nocean_blue = "#0077BE"\nforest_green = "#228B22"',
    },
    '0260_go': {
        "description": 'go Byte Offset',
        "keys": '1goga5go12go30go',
        "initial": 'ABCDEFGHIJ\nKLMNOPQRST\nUVWXYZ0123\n4567890!@#',
    },
    '0261_gp_gP': {
        "description": 'gp gP Put and Move',
        "keys": '3Gyypugpu/Score\ryiw/get\repugp',
        "initial": '# Task List\ntasks = [\n    "fix login bug",\n    "add dark mode",\n    "write tests",\n]\n\npriority = [\n    "deploy hotfix",\n]\n\next = "Score"\napi = "call get(x)"',
    },
    '0262_gq': {
        "description": 'gq Format Text',
        "keys": '3GgqqGgq$',
        "initial": '# Project Notes\n\nThis is a very long line that goes on and on and really should be wrapped to a reasonable width so that it is easy to read on any screen size.\n\nThis line is fine.\n\nAnother extremely long line of text that keeps going and going and nobody wants to scroll horizontally to read this kind of thing in a terminal.',
    },
    '0263_gw': {
        "description": 'gw Format Keep Cursor',
        "keys": '3G0gqqu3G0gww',
        "initial": '# Readme\n\nThis project is a small utility that helps developers manage their configuration files across multiple machines and keep everything in sync.\n\nFeatures:\n- Fast sync\n- Encrypted backup',
    },
    '0264_gr': {
        "description": 'gr Virtual Replace',
        "keys": '2Gf\tr-ugr-',
        "initial": '',
    },
    '0265_gs': {
        "description": 'gs Sleep',
        "keys": '2gs1gs',
        "initial": '# Nap Time\nimport time\n\ndef take_a_nap(seconds):\n    print("Sleeping...")\n    time.sleep(seconds)\n    print("Awake!")',
    },
    '0266_gt_gT': {
        "description": 'gt gT Tab Navigation',
        "keys": 'gtgtgtgT2gt',
        "initial": '# Tests\ndef test_run():\n    assert True',
    },
    '0267_gu': {
        "description": 'gu Lowercase',
        "keys": '2Gf"lguw3Gguu4Gf"gui"',
        "initial": '# Angry Code\nMESSAGE = "HELLO WORLD"\nSTATUS = "ALL SYSTEMS GO"\nERROR = "SOMETHING BROKE"\nprint(MESSAGE)',
    },
    '0268_gU': {
        "description": 'gU Uppercase',
        "keys": '2G0gUw3GgUU4Gf"gUi"',
        "initial": '# Quiet Code\nwarning = "disk almost full"\nerror = "connection lost"\nstatus = "all good"\nprint(warning)',
    },
    '0269_g_tilde': {
        "description": 'g~ Toggle Case',
        "keys": '2Gf"lg~w3Gg~~4G0~~',
        "initial": '# Case Flipper\nname = "Alice"\nMODE = "debug"\nTitle = "Hello World"\nprint(name)',
    },
    '0270_gv': {
        "description": 'gv Reselect Visual',
        "keys": '3GV3j\x1bgv>gv>',
        "initial": '# Inventory\nitems = [\n    "sword",\n    "shield",\n    "potion",\n    "scroll",\n]\nprint(items)',
    },
    '0271_gx': {
        "description": 'gx Open URL or File',
        "keys": '3G0gx',
        "initial": '# Bookmarks\n\nhttps://neovim.io\nhttps://vim.org\nhttps://github.com\n\nLocal: ~/vimfu/links.md',
    },
    '0272_gH': {
        "description": 'gH Select Line Mode',
        "keys": '2GgH- pears\r\x1bu2GgH\x1b[1;2B\x1b[1;2B- mixed fruit\r\x1b',
        "initial": '# shopping\n- apples\n- bananas\n- cherries\n- dates\n- eggs',
    },
    '0273_gh': {
        "description": 'gh Select Mode',
        "keys": '2Gf"lv2l\x07blue\x1b',
        "initial": '# Editor\ncolor = "red"\nsize = "large"\nshape = "circle"\nprint(color)',
    },
    '0274_gI': {
        "description": 'gI Insert at Column 1',
        "keys": '2GI\x1bgI# \x1b',
        "initial": 'def launch():\n    fuel = 100\n    speed = 0\n    altitude = 0\n    return True',
    },
    '0275_gi': {
        "description": 'gi Insert at Last Position',
        "keys": '4Go"eggs",\x1bGgi\r"butter",\x1b',
        "initial": '# Recipe Builder\ningredients = [\n    "flour",\n    "sugar",\n]\n\ndef bake():\n    print("mixing...")',
    },
    '0276_gJ': {
        "description": 'gJ Join Without Space',
        "keys": '2GJugJ4gJ',
        "initial": '# Path Builder\n/home\n/user\n/documents\n/projects\n/vim\n\nhttp://\nexample\n.com\n/page',
    },
    '0277_gQ': {
        "description": 'gQ Ex Mode',
        "keys": 'gQ1p\r%s/cherry/mango/\rvisual\r',
        "initial": 'apple\nbanana\ncherry\ndate\nelderberry',
    },
    '0278_gR': {
        "description": 'gR Virtual Replace Mode',
        "keys": '2G0RAlexander\x1bu2G0gRAlexander\x1b',
        "initial": '',
    },
    '0279_gV': {
        "description": 'gV Avoid Reselect',
        "keys": '2GV2j:s/alpha/omega/\r',
        "initial": '# Selection Demo\nalpha = 1\nbeta = 2\ngamma = 3\ndelta = 4\nepsilon = 5',
    },
    '0280_g_star': {
        "description": 'g* g# Partial Word Search',
        "keys": '2G0*2G0g*g#',
        "initial": '# Word Search\nlog = "start"\nlogger = get_logger()\nlog_file = "app.log"\nblog = "my blog"\ncatalog = load_catalog()\nlogging.info(log)',
    },
    '0281_g_dollar': {
        "description": 'g$ g0 g^ Display Line Edges',
        "keys": '2G0$2G0g$g0g^',
        "initial": 'Short line.\n    This is a very long indented line that wraps around the screen multiple times because it has so many words in it.\nAnother short line.',
    },
    '0282_g_ampersand': {
        "description": 'g& Repeat Substitution',
        "keys": '2G:s/red/orange/\rg&',
        "initial": '# Color Theme\nbg = "red"\nfg = "blue"\nborder = "red"\nhover = "red"\nactive = "green"',
    },
    '0283_g_semicolon': {
        "description": 'g; g, Change List',
        "keys": '2Gf0s10\x1b5Gf1s5\x1b7Gf1C50\x1bg;g;g,',
        "initial": '# Tracker\nx = 0\ny = 0\nz = 0\nspeed = 1\nangle = 90\npower = 100',
    },
    '0284_g_question': {
        "description": 'g? ROT13 Encoding',
        "keys": '2Gg??g??ggg?G',
        "initial": '# Spoiler Alert\nThe butler did it.\nThe cake is a lie.\nSoylent green is people.',
    },
    '0285_g_at': {
        "description": 'g@ Apply Operator',
        "keys": ":set inccommand=\r:function! Bracketize(type)\r:  '[,']s/.*$/[&]/\r:endfunction\r:set operatorfunc=Bracketize\r2Gg@j",
        "initial": '# Custom Ops\nhello world\nfoo bar baz\ntest data here\nfinal line',
    },
    '0286_zz_center': {
        "description": 'zz Center Screen',
        "keys": '20Gzz/main\rzz',
        "initial": '# Dungeon Crawler\nimport random\n\ndef gen_room():\n    w = random.randint(5, 15)\n    h = random.randint(5, 15)\n    return (w, h)\n\ndef gen_monster():\n    hp = random.randint(10, 50)\n    atk = random.randint(1, 10)\n    return {"hp": hp, "atk": atk}\n\ndef gen_loot():\n    gold = random.randint(1, 100)\n    gems = random.randint(0, 5)\n    return {"gold": gold, "gems": gems}\n\ndef gen_trap():\n    damage = random.randint(5, 20)\n    return {"dmg": damage}\n\ndef gen_floor(rooms=10):\n    floor = []\n    for i in range(rooms):\n        floor.append(gen_room())\n    return floor\n\ndef main():\n    floors = [gen_floor() for _ in range(5)]\n    print(f"{len(floors)} floors")\n\nif __name__ == "__main__":\n    main()',
    },
    '0287_zt_top': {
        "description": 'zt Scroll to Top',
        "keys": '15Gztzzzt',
        "initial": '# Quest System\nclass Quest:\n    def __init__(self, name):\n        self.name = name\n        self.steps = []\n        self.done = False\n\n    def add_step(self, step):\n        self.steps.append(step)\n\n    def complete(self):\n        self.done = True\n        return f"{self.name} done!"\n\n    def progress(self):\n        total = len(self.steps)\n        finished = sum(1 for s in self.steps\n                       if s.get("done"))\n        return f"{finished}/{total}"\n\n    def reset(self):\n        self.done = False\n        for s in self.steps:\n            s["done"] = False\n\ndef load_quests(path):\n    quests = []\n    print(f"Loading from {path}")\n    return quests',
    },
    '0288_zb_bottom': {
        "description": 'zb Scroll to Bottom',
        "keys": 'G34Gzb',
        "initial": '# Tower Defense\n# Small example for the VimFu zb demo.\nimport math\nimport random\n\n\nclass Enemy:\n    def __init__(self, x, y, hp):\n        self.x = x\n        self.y = y\n        self.hp = hp\n        self.alive = True\n\n    def take_damage(self, amount):\n        self.hp -= amount\n        if self.hp <= 0:\n            self.alive = False\n        return self.alive\n\n    def step(self, dx, dy):\n        self.x += dx\n        self.y += dy\n\n\nclass Tower:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n        self.range = 5\n        self.damage = 10\n        self.cooldown = 1.0\n        self.level = 1\n\n    def upgrade(self):\n        self.level += 1\n        self.damage *= 1.5\n        self.range += 1\n\n    def in_range(self, enemy):\n        dx = self.x - enemy.x\n        dy = self.y - enemy.y\n        dist = math.sqrt(dx*dx + dy*dy)\n        return dist <= self.range\n\n    def fire(self, enemy):\n        if self.in_range(enemy):\n            enemy.hp -= self.damage\n            return True\n        return False',
    },
    '0289_z_scroll_variants': {
        "description": 'z. z+ z- z^ Scroll Variants',
        "keys": '15G$z.z+z^',
        "initial": '# Game Engine\nclass Engine:\n    def __init__(self):\n        self.running = False\n        self.fps = 60\n        self.frame = 0\n\n    def start(self):\n        self.running = True\n        self.loop()\n\n    def loop(self):\n        while self.running:\n            self.update()\n            self.render()\n            self.frame += 1\n\n    def update(self):\n        pass\n\n    def render(self):\n        pass\n\n    def stop(self):\n        self.running = False\n        print(f"Stopped at {self.frame}")\n\n    def reset(self):\n        self.frame = 0\n        self.running = False',
    },
    '0290_zs_ze': {
        "description": 'zs ze Horizontal Scroll',
        "keys": '2G/critical\rzsze',
        "initial": '# Wide Lines\nresult = calculate_damage(base_attack, defense_rating, critical_multiplier, elemental_bonus, armor_penetration)\nplayer_stats = {"health": 100, "mana": 50, "stamina": 75, "strength": 20, "dexterity": 15, "intelligence": 18}\nshort = 1',
    },
    '0291_zh_zl': {
        "description": 'zh zl Scroll Characters',
        "keys": 'j20zl20zhzlzlzl',
        "initial": '# Spell Engine\ncast(fireball, target=dragon, power=9001, element="fire", cooldown=3, mana_cost=50, area=True)\nstats = {"hp": 100, "mp": 50, "str": 20, "dex": 15, "int": 18, "wis": 12, "cha": 8, "luk": 7}\nx = 1',
    },
    '0292_zH_zL': {
        "description": 'zH zL Scroll Half-Screen',
        "keys": 'jzLzLzHzH',
        "initial": '# Inventory Database\nweapons = ["flame_sword", "ice_dagger", "thunder_bow", "shadow_staff", "holy_mace", "venom_whip", "storm_axe"]\narmor_sets = {"plate": 90, "chain": 60, "leather": 30, "cloth": 10, "dragon_scale": 120, "mithril": 100}\nshort = True',
    },
    '0293_zo': {
        "description": 'zo Open Fold',
        "keys": 'jjzo8jzo',
        "initial": '# Dungeon Loot\ndef roll_dice(sides):\n    import random\n    result = random.randint(1, sides)\n    return result\n\ndef open_chest(level):\n    gold = level * 100\n    gems = level // 3\n    return gold, gems\n\ndef sell_item(item):\n    price = item.value // 2\n    return price\n\ndef craft(herbs):\n    power = len(herbs) * 10\n    return power',
    },
    '0294_zc': {
        "description": 'zc Close Fold',
        "keys": '3Gzc4jzc',
        "initial": '# Combat System\ndef attack(target):\n    damage = 50\n    target.hp -= damage\n    return damage\n\ndef defend(shield):\n    block = shield * 2\n    absorbed = min(block, 100)\n    return absorbed\n\ndef heal(potion):\n    restore = potion.power\n    bonus = restore // 5\n    return restore + bonus\n\ndef flee(speed):\n    chance = speed / 100\n    return chance > 0.5',
    },
    '0295_za': {
        "description": 'za Toggle Fold',
        "keys": '2GjzazaGza',
        "initial": '# Pet Simulator\ndef feed(pet):\n    pet.hunger -= 20\n    pet.happy += 10\n    return pet.happy\n\ndef play(pet):\n    pet.energy -= 15\n    pet.happy += 25\n    return pet.happy\n\ndef sleep(pet):\n    pet.energy = 100\n    pet.hunger += 5\n    return pet.energy',
    },
    '0296_zO_zC_zA': {
        "description": 'zO zC zA Recursive Folds',
        "keys": 'jzOzCzAzA',
        "initial": 'class Wizard:\n    def cast(self):\n        mana = 100\n        spell = "fireball"\n        return spell\n    def rest(self):\n        regen = 10\n        return regen\n\nclass Rogue:\n    def hide(self):\n        stealth = True\n        return stealth\n    def stab(self):\n        crit = 200\n        return crit',
    },
    '0297_zv': {
        "description": 'zv View Cursor Line',
        "keys": '3Gzv15Gzv',
        "initial": 'class Quest:\n    def start(self):\n        print("Adventure begins!")\n        self.active = True\n        return self.active\n    def reward(self):\n        gold = 500\n        xp = 1000\n        return gold, xp\n\nclass Tavern:\n    def enter(self):\n        print("Welcome, hero!")\n        self.visited = True\n    def rest(self):\n        heal = 100\n        return heal',
    },
    '0298_zr_zm': {
        "description": 'zr zm Fold Level',
        "keys": 'zrzrzmzm',
        "initial": 'class Fighter:\n    def slash(self):\n        damage = 40\n        return damage\n    def block(self):\n        armor = 60\n        return armor\n\nclass Healer:\n    def cure(self):\n        restore = 50\n        return restore\n    def buff(self):\n        boost = 20\n        return boost',
    },
    '0299_zR_zM': {
        "description": 'zR zM All Folds',
        "keys": 'zMzRzMzR',
        "initial": 'class Dragon:\n    def breathe(self):\n        element = "fire"\n        damage = 200\n        return damage\n    def fly(self):\n        altitude = 9000\n        return altitude\n\nclass Lich:\n    def curse(self):\n        debuff = "slow"\n        duration = 10\n        return debuff\n    def summon(self):\n        minions = 5\n        return minions',
    },
    '0300_zx_zX': {
        "description": 'zx zX Reapply Folds',
        "keys": '2Gjzo8jzozxzoggzX',
        "initial": '# Item Shop\ndef buy(item, gold):\n    if gold >= item.price:\n        gold -= item.price\n        return True\n    return False\n\ndef sell(item):\n    refund = item.price // 2\n    return refund\n\ndef browse(stock):\n    for item in stock:\n        print(item.name)\n    return len(stock)',
    },
}

SKIPPED = {
    '0234_ctrl_z': ['shell escape (:!)'],
}
