"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0001_what_is_vim': {
        "description": 'What Is Vim?',
        "keys": 'lllljjjhhhkki# Vim is modal!\x1b',
        "initial": 'import sys\n\ndef greet(name):\n    print(f"Hello, {name}!")\n    return True\n\ngreet("world")',
    },
    '0002_opening_a_file': {
        "description": 'Opening a File',
        "keys": 'vim\x01n\x05 notes.txt\riHello, Vim!\x1b:q\r:q!\r',
        "initial": 'import sys\n\ndef greet(name):\n    print(f"Hello, {name}!")\n    return True\n\ngreet("world")',
    },
    '0003_normal_mode': {
        "description": 'Normal Mode',
        "keys": 'jjjjwwwwggO# task list\x1b:set number\r:quit\x1b',
        "initial": 'tasks = [\n    "learn vim",\n    "practice daily",\n    "build something",\n]\n\nfor task in tasks:\n    print(task)',
    },
    '0004_insert_mode': {
        "description": 'Insert Mode',
        "keys": 'jkiname = "world"\rprint(name)\x1bi, "!"\x1b',
        "initial": '',
    },
    '0005_typing_text': {
        "description": 'Typing Text',
        "keys": 'iShopping list\reggs\rmilk\rbread\x7f\x7f\x7f\x7futter\r\tsalted\x1b',
        "initial": '',
    },
    '0006_back_to_normal': {
        "description": 'Back to Normal Mode',
        "keys": 'i# my todo list\r\x1b\x1b\x1bjjjA  # show tasks\x1bggO# vim practice\x1b',
        "initial": 'tasks = []\nprint(tasks)',
    },
    '0007_saving_your_file': {
        "description": 'Saving Your File',
        "keys": 'iprint("hello world")\x1b:w\roprint("saved!")\x1b:w\r',
        "initial": '',
    },
    '0008_quitting_vim': {
        "description": 'Quitting Vim',
        "keys": ':q\rihello\x1b:q\r',
        "initial": '',
    },
    '0009_save_and_quit': {
        "description": 'Save and Quit',
        "keys": 'iprint("hello")\x1b:wq\rA\rprint("world")\x1b:x\roprint("done")\x1bZZ',
        "initial": '',
    },
    '0010_quit_without_saving': {
        "description": 'Quit Without Saving',
        "keys": 'iXXXXXXX\x1bdd:q\r:q!\riOOPS\x1bZQ',
        "initial": 'print("hello world")',
    },
    '0011_undo': {
        "description": 'Undo',
        "keys": 'dddduuothis is a mistake\x1bu',
        "initial": 'print("hello")\nprint("world")\nprint("done")',
    },
    '0012_redo': {
        "description": 'Redo',
        "keys": 'oprint("new line")\x1bu\x12u\x12u\x12',
        "initial": 'print("hello")\nprint("world")',
    },
    '0013_moving_hjkl': {
        "description": 'Moving: h j k l',
        "keys": 'jjjkklllllhhhjjlllkhj',
        "initial": 'apples = 10\nbananas = 20\ncherries = 30\ndates = 40\nelderberries = 50',
    },
    '0014_why_not_arrow_keys': {
        "description": 'Why Not Arrow Keys?',
        "keys": '\x1b[B\x1b[B\x1b[C\x1b[C\x1b[Ajjllk',
        "initial": 'apples = 10\nbananas = 20\ncherries = 30\ndates = 40',
    },
    '0015_the_escape_habit': {
        "description": 'The Escape Habit',
        "keys": 'i# my todo list\x1bobuy milk\x1bowalk dog\x1bolearn vim\x1b',
        "initial": '',
    },
    '0016_append_after_cursor': {
        "description": 'Append After Cursor',
        "keys": 'fllio\x1buao\x1bj0fga2\x1b',
        "initial": 'msg = "hell"\nprint(msg)',
    },
    '0017_insert_at_start_of_line': {
        "description": 'Insert at Start of Line',
        "keys": 'flI# \x1bjj$I# \x1bjI# \x1b',
        "initial": 'host = "localhost"\nport = 8080\ndebug = True\nname = "app"',
    },
    '0018_append_at_end_of_line': {
        "description": 'Append at End of Line',
        "keys": 'A  # width\x1bj0A  # height\x1bj0wA  # depth\x1bj0A + z\x1b',
        "initial": 'x = 1\ny = 2\nz = 3\ntotal = x + y',
    },
    '0019_open_line_below': {
        "description": 'Open Line Below',
        "keys": 'ostep2 = "eat breakfast"\x1bGostep5 = "repeat"\x1bostep6 = "profit"\x1b',
        "initial": 'step1 = "wake up"\nstep3 = "code"\nstep4 = "sleep"',
    },
    '0020_open_line_above': {
        "description": 'Open Line Above',
        "keys": 'O# cake recipe\x1bjjjO# wet ingredients\x1bGO# instructions\x1b',
        "initial": 'flour = "2 cups"\nsugar = "1 cup"\neggs = 3\nbake = "350F for 30 min"',
    },
    '0021_word_forward': {
        "description": 'Word Forward',
        "keys": 'wwwwwwwwgg0wwwwwwwwww',
        "initial": 'name = "vim master"\nlevel = 42\nprint(name, level)',
    },
    '0022_word_backward': {
        "description": 'Word Backward',
        "keys": 'G$bbbbbbbbG$bbbbbbbbbbbbbb',
        "initial": 'name = "vim master"\nlevel = 42\nprint(name, level)',
    },
    '0023_end_of_word': {
        "description": 'End of Word',
        "keys": 'eeeeeeeegg0eeeeeeeeee',
        "initial": 'name = "vim master"\nlevel = 42\nprint(name, level)',
    },
    '0024_back_to_end_of_word': {
        "description": 'Back to End of Word',
        "keys": 'G$gegegegegegege',
        "initial": 'name = "vim master"\nlevel = 42\nprint(name, level)',
    },
    '0025_start_of_line': {
        "description": 'Start of Line',
        "keys": 'www0j$0j$0',
        "initial": 'def greet(name):\n    msg = f"Hello {name}"\n    print(msg)',
    },
    '0026_first_non_blank': {
        "description": 'First Non-Blank',
        "keys": 'j$0$^j$^gg$^',
        "initial": 'def greet(name):\n    msg = f"Hello {name}"\n    print(msg)',
    },
    '0027_end_of_line': {
        "description": 'End of Line',
        "keys": '$j0$j0$gg$0$0',
        "initial": 'def greet(name):\n    msg = f"Hello {name}"\n    print(msg)',
    },
    '0028_go_to_top_of_file': {
        "description": 'Go to Top of File',
        "keys": 'GggGgg',
        "initial": 'import os\nimport sys\n\ndef setup():\n    path = os.getcwd()\n    return path\n\ndef main():\n    base = setup()\n    name = "vimfu"\n    print(f"Running {name}")\n    print(f"Path: {base}")\n    return 0\n\nif __name__ == "__main__":\n    sys.exit(main())',
    },
    '0029_go_to_bottom_of_file': {
        "description": 'Go to Bottom of File',
        "keys": 'GggGggG',
        "initial": 'import os\nimport sys\n\ndef setup():\n    path = os.getcwd()\n    return path\n\ndef main():\n    base = setup()\n    name = "vimfu"\n    print(f"Running {name}")\n    print(f"Path: {base}")\n    return 0\n\nif __name__ == "__main__":\n    sys.exit(main())',
    },
    '0030_go_to_line_n': {
        "description": 'Go to Line N',
        "keys": ':set number\r:8\r:12\r1G5G',
        "initial": 'import os\nimport sys\n\ndef setup():\n    path = os.getcwd()\n    return path\n\ndef main():\n    base = setup()\n    name = "vimfu"\n    print(f"Running {name}")\n    print(f"Path: {base}")\n    return 0\n\nif __name__ == "__main__":\n    sys.exit(main())',
    },
    '0031_delete_character': {
        "description": 'Delete Character',
        "keys": 'falxj0filxgg$xxxuuu',
        "initial": 'messaage = "hello"\npriint("done")',
    },
    '0032_delete_char_before': {
        "description": 'Delete Character Before',
        "keys": 'frlXj0fxlXgg$XXXuuu',
        "initial": 'prrint("hello")\ntexxt = "data"',
    },
    '0033_delete_word': {
        "description": 'Delete Word',
        "keys": 'fddwjdwjdwuuu',
        "initial": 'color = "dark blue"\nshape = "very large"\ntitle = "old legacy"',
    },
    '0034_delete_to_end': {
        "description": 'Delete to End of Line',
        "keys": 'f#Dj0f#Dj0f#Duuu',
        "initial": 'name = "vim"  # TODO fix\nport = 8080  # remove this\nhost = "local"  # old note',
    },
    '0035_delete_line': {
        "description": 'Delete Entire Line',
        "keys": 'jjddddgg3dduuu',
        "initial": 'import os\nimport sys\nimport debug  # remove\nimport log  # remove\n\ndef main():\n    run()',
    },
    '0036_change_word': {
        "description": 'Change Word',
        "keys": 'frcwblue\x1bj0fscwlarge\x1bj0focwnew\x1b',
        "initial": 'theme = "red"\nwidth = "small"\nlabel = "old"',
    },
    '0037_change_to_end': {
        "description": 'Change to End of Line',
        "keys": 'fhChttps://new-server"\x1bj0f9C8080"\x1bj0f/C/api/v2/new"\x1b',
        "initial": 'host = "http://old-server"\nport = "9999"\npath = "/api/v1/old"',
    },
    '0038_change_line': {
        "description": 'Change Entire Line',
        "keys": 'ccname = "vim"\x1bjccversion = 2\x1bjSactive = True\x1b',
        "initial": 'x = 1\ny = 2\nz = 3',
    },
    '0039_substitute_char': {
        "description": 'Substitute Character',
        "keys": 'sl\x1bjlsa\x1bj0sl\x1b',
        "initial": 'het = "vim"\ncot = 42\nfog = "data"',
    },
    '0040_yank_line': {
        "description": 'Yank a Line',
        "keys": 'yyppuujyypu',
        "initial": 'name = "vim"\nversion = 2',
    },
    '0041_put_after': {
        "description": 'Put After',
        "keys": 'yypuddpuuxp',
        "initial": 'alpha = 1\ngamma = 3',
    },
    '0042_put_before': {
        "description": 'Put Before',
        "keys": 'jyyPuddPuuggxP',
        "initial": 'alpha = 1\ngamma = 3',
    },
    '0043_yank_motion': {
        "description": 'Yank a Motion',
        "keys": 'ywjPuggy$j$pu',
        "initial": 'name = "vim"\nkind = "editor"',
    },
    '0044_ddp_swap': {
        "description": 'The dd-p Swap Trick',
        "keys": 'ddpuujjjlxp',
        "initial": 'beta = 2\nalpha = 1\ndelta = 3\ntset = 4',
    },
    '0045_replace_char': {
        "description": 'Replace a Character',
        "keys": 'forajr8llr8jre',
        "initial": 'tag = "dork"\ncount = 9090\nflag = Trua',
    },
    '0046_search_forward': {
        "description": 'Search Forward',
        "keys": '/mode\r/flag\r/local\r',
        "initial": 'host = "local"\nport = 8080\nmode = "debug"\nflag = True\nhost = "cloud"\nport = 9090\nmode = "live"\nflag = False',
    },
    '0047_search_backward': {
        "description": 'Search Backward',
        "keys": 'G?mode\r?port\r?live\r',
        "initial": 'host = "local"\nport = 8080\nmode = "debug"\nflag = True\nhost = "cloud"\nport = 9090\nmode = "live"\nflag = False',
    },
    '0048_next_match': {
        "description": 'Next Match',
        "keys": '/cat\rnn',
        "initial": 'cat = "meow"\ndog = "woof"\ncat = "purr"\ndog = "bark"\ncat = "hiss"\ndog = "howl"',
    },
    '0049_previous_match': {
        "description": 'Previous Match',
        "keys": '/dog\rnnNN',
        "initial": 'cat = "meow"\ndog = "woof"\ncat = "purr"\ndog = "bark"\ncat = "hiss"\ndog = "howl"',
    },
    '0050_search_word': {
        "description": 'Search Word Under Cursor',
        "keys": '**j*',
        "initial": 'name = "vim"\nkind = "tool"\nname = "nano"\nkind = "tool"\nname = "code"\nkind = "app"',
    },
    '0051_search_word_backward': {
        "description": 'Search Word Backward',
        "keys": 'G####k#',
        "initial": 'mood = "hungry"\nnaps = 5\nmood = "playful"\nnaps = 2\nmood = "grumpy"\nnaps = 9\nmood = "zoomies"\nnaps = 0\nmood = "sleepy"\nnaps = 12',
    },
    '0052_find_char_forward': {
        "description": 'Find Character Forward',
        "keys": 'fwf9j0fbjf-',
        "initial": 'cat = summon("whiskers", 9)\ndog = summon("barkley", 3)\nbug = summon("glitch", -1)\nnpc = summon("bob", 99)',
    },
    '0053_find_char_backward': {
        "description": 'Find Character Backward',
        "keys": '$FmFrj$FlFl',
        "initial": 'heal = mix("ruby", "moss", 3)\nburn = mix("lava", "coal", 7)\ncure = mix("sage", "mint", 2)\nzap  = mix("bolt", "dust", 5)',
    },
    '0054_till_char_forward': {
        "description": 'Till Character Forward',
        "keys": 'f(0t(j0t,j0dt)u',
        "initial": 'hero = fight("dragon", 50)\nsage = fight("goblin", 10)\nking = fight("troll", 30)',
    },
    '0055_till_char_backward': {
        "description": 'Till Character Backward',
        "keys": '$F($T(j$T,j$T(',
        "initial": 'buy = shop("wand", 50, "rare")\nbuy = shop("cape", 30, "epic")\nbuy = shop("ring", 99, "myth")',
    },
    '0056_repeat_find': {
        "description": 'Repeat Find',
        "keys": 'f,;;;j0f:;;;j0t,;;',
        "initial": 'items = "axe, bow, cup, gem, orb"\nstats = "hp:5, mp:3, xp:0, gp:9"\nspells = "fire, ice, bolt, heal"',
    },
    '0057_repeat_find_reverse': {
        "description": 'Repeat Find Reverse',
        "keys": 'f/;;;,,j0f/;;,',
        "initial": 'path = "/usr/bin/vim/share/doc"\nhome = "/home/user/.config/nvim"',
    },
    '0058_counted_motions': {
        "description": 'Counted Motions',
        "keys": '10l4j3w6j8k',
        "initial": '# dungeon: rooms, traps, loot\nroom = "entry"\ntrap = False\nloot = "key"\nboss = None\nroom = "vault"\ntrap = True\nloot = "gold"\nboss = "dragon"\nroom = "exit"\ntrap = False\nloot = "gem"\nboss = None',
    },
    '0059_counted_deletes': {
        "description": 'Counted Deletes',
        "keys": '2j3ddj2dduuggj2dwu',
        "initial": '# robot config\npower = 100\nbug = "glitch"\nbug = "crash"\nbug = "lag"\nspeed = 50\njunk = None\njunk = None\narmor = 75',
    },
    '0060_counted_inserts': {
        "description": 'Counted Inserts',
        "keys": 'j20i-\x1buG3ofuel = 0\x1buggj5i*\x1bu',
        "initial": '# spaceship parts\n\nengine = 1\nshield = 1\nlaser = 1',
    },
    '0061_go_to_line_by_count': {
        "description": 'Go to Line by Count',
        "keys": '7G12G:5\r1G',
        "initial": '# tower defense config\nwave_1 = "goblins"\nwave_2 = "orcs"\nwave_3 = "trolls"\nwave_4 = "dragons"\nwave_5 = "demons"\ngold = 500\ntower_a = "archer"\ntower_b = "mage"\ntower_c = "cannon"\ntower_d = "frost"\nboss = "lich king"\nhp = 9999\nloot = "legendary sword"',
    },
    '0062_jump_to_percentage': {
        "description": 'Jump to Percentage',
        "keys": '50%100%75%1%',
        "initial": '# quest log\nquest_1 = "find the lost sword"\nquest_2 = "rescue the princess"\nquest_3 = "defeat the goblin king"\nquest_4 = "collect ten mushrooms"\nquest_5 = "explore the dark cave"\nquest_6 = "brew a healing potion"\nquest_7 = "forge the magic ring"\nquest_8 = "tame the wild dragon"\nquest_9 = "unlock the secret door"\nquest_10 = "steal the golden egg"\nquest_11 = "cross the lava bridge"\nquest_12 = "befriend the ghost"\nquest_13 = "decode the ancient map"\nquest_14 = "survive the sandstorm"\nquest_15 = "climb the frozen peak"\nquest_16 = "outsmart the sphinx"\nquest_17 = "raid the pirate ship"\nquest_18 = "tame the sea serpent"\nquest_19 = "find the hidden temple"\nquest_20 = "light the dark beacon"\nquest_21 = "calm the thunder wolf"\nquest_22 = "mend the broken crown"\nquest_23 = "open the void portal"\nquest_24 = "charm the stone giant"\nquest_25 = "ride the sky whale"\nquest_26 = "wake the sleeping god"\nquest_27 = "seal the demon rift"\nquest_28 = "win the dragon race"\nquest_29 = "trick the shadow fox"\nquest_30 = "map the crystal maze"\nquest_31 = "free the cursed knight"\nquest_32 = "brew the time elixir"\nquest_33 = "sink the ghost ship"\nquest_34 = "tame the fire hawk"\nquest_35 = "solve the moon riddle"\nquest_36 = "break the ice throne"\nquest_37 = "clear the poison swamp"\nquest_38 = "unite the lost tribes"\nquest_39 = "face the final boss"',
    },
    '0063_go_to_column': {
        "description": 'Go to Column',
        "keys": 'j10|1|j20|30|',
        "initial": '# pixel art colors\nrow = "..##..##..##..##.."\nsky = "bbbbbbbbbbbbbbbbbb"\ngnd = "gggggggggggggggggg"',
    },
    '0064_char_visual_mode': {
        "description": 'Character Visual Mode',
        "keys": 'jve\x1bjvww\x1bjv$\x1b',
        "initial": '# spell book\nfire = "fireball"\nice = "blizzard"\nheal = "restoration"\ndark = "shadow bolt"',
    },
    '0065_line_visual_mode': {
        "description": 'Line Visual Mode',
        "keys": 'jV\x1bVjjduGVkk\x1b',
        "initial": '# crew roster\npilot = "Nova"\nmedic = "Patch"\nhacker = "Glitch"\ngunner = "Boom"\ncook = "Pepper"',
    },
    '0066_block_visual_mode': {
        "description": 'Block Visual Mode',
        "keys": 'j\x16jjjje\x1bggj$\x16jjjjdu',
        "initial": '# score board\nalice  = 100\nbob    = 200\ncarol  = 300\ndave   = 400\neve    = 500',
    },
    '0067_switching_visual_modes': {
        "description": 'Switching Visual Modes',
        "keys": 'jveV\x16jjV\x1b',
        "initial": '# pet stats\ncat  = 9\ndog  = 7\nfish = 3\nbird = 5',
    },
    '0068_actions_on_selection': {
        "description": 'Actions on Selection',
        "keys": 'jVjdu2jVjj>uggjveyGobest = \x1bpuu',
        "initial": '# loot table\nsword = 10\nshield = 5\npotion = 20\nscroll = 8\ngem = 50',
    },
    '0069_other_corner': {
        "description": 'Other Corner',
        "keys": 'jv$oo\x1bjVjjok\x1bggj0\x16jjeO\x1b',
        "initial": '# farm inventory\nwheat = 100\ncorn  = 200\nrice  = 300\noats  = 400\nhay   = 500',
    },
    '0070_reselect_last_selection': {
        "description": 'Reselect Last Selection',
        "keys": '2jVjj>gvduuggjve\x1b3jgv\x1b',
        "initial": '# pizza menu\ncheese = 8\npepperoni = 10\nveggie = 9\nsupreme = 12\nhawaiian = 11',
    },
    '0072_dot_with_counts': {
        "description": 'Dot with Counts',
        "keys": 'dd3.uuuuggJ3.',
        "initial": 'hp = 10\nmp = 10\nxp = 10\natk = 10\ndef_ = 10\nspd = 10\nluck = 10\n\ndef level_up(hero):\n    hero.hp += 5\n    hero.mp += 5\n    hero.xp += 5\n    hero.atk += 5',
    },
    '0073_dot_patterns': {
        "description": 'Dot Patterns',
        "keys": '/goblin\rcwdragon\x1bn.n.n.n.uuuuu/kind\rcwname\x1bn.nn.',
        "initial": 'goblin = 10\nhero = quest("goblin", 5)\nloot = defeat("goblin")\nprint(f"the goblin drops gold")\nprint(f"no more goblin")\n\ndef spawn(kind, level):\n    mob = {"kind": kind, "hp": 10}\n    mob["kind"] = kind.upper()\n    print(f"{kind} spawned")\n    return mob',
    },
    '0074_inner_word_a_word': {
        "description": 'Inner Word / A Word',
        "keys": 'ciwplayer\x1bujwdawuggf-lviw\x1bviW\x1bjf.ciW"begin-quest"\x1bu',
        "initial": 'hero = "dark-knight"\nquest = hero + ".save-realm"\nhp = 100\nweapon = "flame-sword"\npath = "/dungeon/boss-lair"',
    },
    '0075_inner_around_quotes': {
        "description": 'Inner/Around Quotes',
        "keys": 'vi"\x1bci"inferno\x1buj0ci"frostbite\x1buj0da"u',
        "initial": 'fire = cast("fireball", 50)\nice  = cast("blizzard", 30)\nbolt = cast("lightning", 70)',
    },
    '0076_inner_around_single_quotes': {
        "description": 'Inner/Around Single Quotes',
        "keys": "vi'\x1bci'regeneration\x1buj0ci'arcane\x1bujj0da'u",
        "initial": "red = brew('healing', 25)\nblu = brew('mana', 40)\ngrn = brew('speed', 60)\ngld = brew('luck', 99)",
    },
    '0077_inner_around_backticks': {
        "description": 'Inner/Around Backticks',
        "keys": 'f`vi`\x1bci`uname -n\x1buj0da`u',
        "initial": 'host=`hostname`\ndate=`date +%Y`\nuser=`whoami`\necho "$host: $user ($date)"',
    },
    '0078_inner_around_parentheses': {
        "description": 'Inner/Around Parentheses',
        "keys": 'f(vi(\x1bci("inferno", 99\x1buj0di(uj0dibu',
        "initial": 'fire = cast("fireball", 50)\nice  = cast("blizzard", 30)\nbolt = cast("lightning", 70)',
    },
    '0079_inner_around_braces': {
        "description": 'Inner/Around Braces',
        "keys": 'jvi{\x1bci{    "app": "VimFu",\n    "level": 99\x1bujdiBuda{u',
        "initial": '{\n    "name": "VimFu",\n    "version": 42,\n    "debug": true\n}',
    },
    '0080_inner_around_brackets': {
        "description": 'Inner/Around Brackets',
        "keys": 'f[vi[\x1bci["sword", "shield"\x1buj0di[uj0da[u',
        "initial": 'bag = ["axe", "bow", "cup"]\ngem = ["ruby", "opal", "jade"]\nkey = ["gold", "iron", "bone"]',
    },
    '0081_inner_around_angle_brackets': {
        "description": 'Inner/Around Angle Brackets',
        "keys": 'f<vi<\x1bci<number\x1buj0f<ci<number, string\x1buj0f<da<u',
        "initial": 'let bag: Array<string> = []\nlet hp: Map<string, number> = {}\nlet cb: Promise<boolean> = ok()',
    },
    '0082_inner_around_sentence': {
        "description": 'Inner/Around Sentence',
        "keys": 'vis\x1b)dasugg0cisA wyvern nests on the peak.\x1bu',
        "initial": 'The dragon sleeps in the cave.  It\nguards a pile of gold.  No hero has\nsurvived the attempt.\n\nLegend says a silver sword can slay\nit.  The sword was lost long ago.',
    },
    '0083_inner_around_paragraph': {
        "description": 'Inner/Around Paragraph',
        "keys": 'vip\x1bdapu}jdapuggyipGpu',
        "initial": 'The dragon sleeps in the cave.\nIt guards a pile of gold.\nNo hero has survived.\n\nLegend says a silver sword\ncan slay it.  The sword\nwas lost long ago.\n\nA new hero has arrived.\nThe quest begins at dawn.',
    },
    '0084_inner_around_tag': {
        "description": 'Inner/Around Tag',
        "keys": 'j0vit\x1bcitWyvern Hoard\x1buj0citGems and ancient scrolls.\x1buj0datu',
        "initial": '<div class="card">\n  <h2>Dragon Loot</h2>\n  <p>A pile of gold coins.</p>\n  <span>rare drop</span>\n</div>',
    },
    '0085_the_vim_grammar': {
        "description": 'The Vim Grammar',
        "keys": 'ci"wyvern\x1bujf[di[ugg0f(yi(gg>ip',
        "initial": 'hero = quest("dragon", 99)\nloot = chest["gold"] + 50\nmsg  = f"Level {hero.xp}"',
    },
    '0086_scroll_down_half_page': {
        "description": 'Scroll Down Half Page',
        "keys": '\x04\x04\x04gg5\x04\x04',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}\n\ndef spawn_monster(room, difficulty):\n    hp = roll_dice(difficulty, 8)\n    atk = roll_dice(difficulty, 6)\n    return {"hp": hp, "atk": atk, "room": room["id"]}\n\ndef connect_rooms(a, b):\n    mid_x = (a["x"] + b["x"]) // 2\n    mid_y = (a["y"] + b["y"]) // 2\n    return {"from": a["id"], "to": b["id"]}\n\ndef generate_dungeon():\n    rooms = [gen_room(i) for i in range(ROOMS)]\n    for room in rooms:\n        place_treasure(room)\n        spawn_monster(room, difficulty=3)\n    return rooms',
    },
    '0087_scroll_up_half_page': {
        "description": 'Scroll Up Half Page',
        "keys": 'G\x15\x15\x15\x04\x04\x15\x15',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}\n\ndef spawn_monster(room, difficulty):\n    hp = roll_dice(difficulty, 8)\n    atk = roll_dice(difficulty, 6)\n    return {"hp": hp, "atk": atk, "room": room["id"]}\n\ndef connect_rooms(a, b):\n    mid_x = (a["x"] + b["x"]) // 2\n    mid_y = (a["y"] + b["y"]) // 2\n    return {"from": a["id"], "to": b["id"]}\n\ndef generate_dungeon():\n    rooms = [gen_room(i) for i in range(ROOMS)]\n    for room in rooms:\n        place_treasure(room)\n        spawn_monster(room, difficulty=3)\n    return rooms',
    },
    '0088_scroll_full_page_forward': {
        "description": 'Scroll Full Page Forward',
        "keys": '\x06\x06gg\x04gg\x06',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}\n\ndef spawn_monster(room, difficulty):\n    hp = roll_dice(difficulty, 8)\n    atk = roll_dice(difficulty, 6)\n    return {"hp": hp, "atk": atk, "room": room["id"]}\n\ndef connect_rooms(a, b):\n    mid_x = (a["x"] + b["x"]) // 2\n    mid_y = (a["y"] + b["y"]) // 2\n    return {"from": a["id"], "to": b["id"]}\n\ndef generate_dungeon():\n    rooms = [gen_room(i) for i in range(ROOMS)]\n    for room in rooms:\n        place_treasure(room)\n        spawn_monster(room, difficulty=3)\n    return rooms',
    },
    '0089_scroll_full_page_backward': {
        "description": 'Scroll Full Page Backward',
        "keys": 'G\x02\x02\x06\x06\x02\x02',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}\n\ndef spawn_monster(room, difficulty):\n    hp = roll_dice(difficulty, 8)\n    atk = roll_dice(difficulty, 6)\n    return {"hp": hp, "atk": atk, "room": room["id"]}\n\ndef connect_rooms(a, b):\n    mid_x = (a["x"] + b["x"]) // 2\n    mid_y = (a["y"] + b["y"]) // 2\n    return {"from": a["id"], "to": b["id"]}\n\ndef generate_dungeon():\n    rooms = [gen_room(i) for i in range(ROOMS)]\n    for room in rooms:\n        place_treasure(room)\n        spawn_monster(room, difficulty=3)\n    return rooms',
    },
    '0090_center_top_bottom': {
        "description": 'Center / Top / Bottom',
        "keys": '\x04\x04zzztzbzz',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}\n\ndef spawn_monster(room, difficulty):\n    hp = roll_dice(difficulty, 8)\n    atk = roll_dice(difficulty, 6)\n    return {"hp": hp, "atk": atk, "room": room["id"]}\n\ndef connect_rooms(a, b):\n    mid_x = (a["x"] + b["x"]) // 2\n    mid_y = (a["y"] + b["y"]) // 2\n    return {"from": a["id"], "to": b["id"]}\n\ndef generate_dungeon():\n    rooms = [gen_room(i) for i in range(ROOMS)]\n    for room in rooms:\n        place_treasure(room)\n        spawn_monster(room, difficulty=3)\n    return rooms',
    },
    '0091_sentence_forward_backward': {
        "description": 'Sentence Forward/Backward',
        "keys": ')))((d)u',
        "initial": '# The dragon guards the gate. No one\n# has passed in a thousand years. Many\n# have tried. All have failed.\n\ndef enter_gate(hero):\n    """Attempt to pass the gate. Returns\n    True if the hero survives. The gate\n    tests courage first. Then it tests\n    strength. Finally it tests wisdom."""\n    if hero.courage < 50:\n        return False\n    if hero.strength < 30:\n        return False\n    return True',
    },
    '0092_paragraph_forward_backward': {
        "description": 'Paragraph Forward/Backward',
        "keys": '}}}{{{d}u',
        "initial": 'name = "Kira"\nhp = 100\nmp = 40\n\ndef attack(target):\n    dmg = roll(1, 8) + 3\n    target.hp -= dmg\n    return dmg\n\ndef heal(target):\n    amt = roll(1, 6) + 2\n    target.hp += amt\n    return amt\n\ndef level_up(hero):\n    hero.hp += 10\n    hero.mp += 5\n    hero.atk += 2',
    },
    '0093_matching_bracket': {
        "description": 'Matching Bracket',
        "keys": '%%3G0%%l%gg0d%u',
        "initial": 'def cast(spell, power):\n    dmg = calc(roll(2, 6) + power)\n    opts = {"buffs": [1, 2, 3]}\n    return (dmg, opts)',
    },
    '0094_screen_top_middle_bottom': {
        "description": 'Screen Top / Middle / Bottom',
        "keys": 'LHM3H4L',
        "initial": '# Dungeon Generator\nimport random\n\nROOMS = 25\nMIN_SIZE = 4\nMAX_SIZE = 12\n\ndef roll_dice(n, sides):\n    return sum(random.randint(1, sides) for _ in range(n))\n\ndef gen_room(room_id):\n    w = random.randint(MIN_SIZE, MAX_SIZE)\n    h = random.randint(MIN_SIZE, MAX_SIZE)\n    x = random.randint(0, 80 - w)\n    y = random.randint(0, 50 - h)\n    return {"id": room_id, "x": x, "y": y, "w": w, "h": h}\n\ndef place_treasure(room):\n    gold = roll_dice(3, 6) * 10\n    gems = roll_dice(1, 4)\n    return {"gold": gold, "gems": gems}',
    },
    '0095_next_previous_line_start': {
        "description": 'Next/Previous Line Start',
        "keys": '+++--\r\rgg3+',
        "initial": 'class Robot:\n    name = "Bolt"\n    speed = 10\n    battery = 100\n\n    def move(self, dist):\n        self.battery -= dist\n        return self.speed * dist\n\n    def charge(self):\n        self.battery = 100\n        return "fully charged"',
    },
    '0096_word_motions': {
        "description": 'WORD Motions',
        "keys": 'f"wwww0f"Wj$BBj0EEE',
        "initial": 'base_url = "https://api.game.io/v2"\napi_key = "sk-abc-123-xyz-789"\nmax_retry = self.config["retries"]\npath = "/usr/local/bin/launcher"',
    },
    '0097_setting_a_mark': {
        "description": 'Setting a Mark',
        "keys": "maG'a5jmb'a'b",
        "initial": 'hero = "Kira"\nhp = 100\nmp = 40\nweapon = "staff"\n\ndef attack(target):\n    dmg = roll(2, 8)\n    target.hp -= dmg\n    return dmg\n\ndef heal(ally):\n    amt = roll(1, 6) + 5\n    ally.hp += amt\n    return amt',
    },
    '0098_jumping_to_mark_line': {
        "description": 'Jumping to a Mark (Line)',
        "keys": 'f"maGmb\'a\'bd\'au',
        "initial": 'hero = "Kira"\nhp = 100\nmp = 40\nweapon = "staff"\n\ndef attack(target):\n    dmg = roll(2, 8)\n    target.hp -= dmg\n    return dmg\n\ndef heal(ally):\n    amt = roll(1, 6) + 5\n    ally.hp += amt\n    return amt',
    },
    '0099_jumping_to_mark_exact': {
        "description": 'Jumping to a Mark (Exact)',
        "keys": 'f"lmaG\'aG`a6Gjfrmbgg`b',
        "initial": 'hero = "Kira"\nhp = 100\nmp = 40\nweapon = "staff"\n\ndef attack(target):\n    dmg = roll(2, 8)\n    target.hp -= dmg\n    return dmg\n\ndef heal(ally):\n    amt = roll(1, 6) + 5\n    ally.hp += amt\n    return amt',
    },
    '0100_global_marks': {
        "description": 'Global Marks',
        "keys": "mA:e enemy.py\rmB'A'B",
        "initial": 'name = "Goblin"\nhp = 30\natk = 5\nloot = "gold coin"\n\ndef take_hit(dmg):\n    global hp\n    hp -= dmg\n    return hp > 0',
    },
}

SKIPPED = {
    '0071_repeat_last_change': ['shell escape (:!)'],
}
