"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0301_zn_zN_zi': {
        "description": 'zn zN zi Enable Disable Folds',
        "keys": 'znzNzizi',
        "initial": '# Robot AI\ndef think(data):\n    result = analyze(data)\n    plan = strategize(result)\n    return plan\n\ndef act(plan):\n    for step in plan:\n        execute(step)\n    return True\n\ndef learn(outcome):\n    memory = store(outcome)\n    adapt(memory)\n    return memory',
    },
    '0302_zf': {
        "description": 'zf Create Manual Fold',
        "keys": '2Gzf2j5Gzf3jzo',
        "initial": '# Quest Log\ntask_1 = "Defeat the dragon"\ntask_2 = "Find the treasure"\ntask_3 = "Return the crown"\n# Shopping List\nbuy_sword = True\nbuy_armor = True\nbuy_potions = True\n# Party Members\nhero = "Knight"\nsidekick = "Mage"\npet = "Wolf"',
    },
    '0303_zF': {
        "description": 'zF Create Fold N Lines',
        "keys": '2G4zF6G4zF',
        "initial": '# High Scores\nplayer_1 = 9500\nplayer_2 = 8700\nplayer_3 = 7200\nplayer_4 = 6100\n# Achievements\nbadge_1 = "Dragon Slayer"\nbadge_2 = "Speed Runner"\nbadge_3 = "Pacifist"\n# Settings\ndifficulty = "hard"\nsound = True\nmusic = True',
    },
    '0304_zd_zD': {
        "description": 'zd zD Delete Fold',
        "keys": '2Gzf3jzd6Gzf3jzd',
        "initial": '# Inventory\nsword = "Excalibur"\nshield = "Aegis"\npotion = "Elixir"\nscroll = "Fireball"\nring = "Invisibility"\namulet = "Protection"\ngem = "Ruby"\nwand = "Lightning"',
    },
    '0305_zE': {
        "description": 'zE Eliminate All Folds',
        "keys": ':2,3fold\r:5,6fold\r:8,9fold\rzE',
        "initial": '# Spell Book\nfire = "Fireball"\nice = "Blizzard"\nwind = "Tornado"\nearth = "Earthquake"\nholy = "Smite"\ndark = "Shadow Bolt"\narcane = "Magic Missile"\nnature = "Vine Whip"',
    },
    '0306_zj_zk': {
        "description": 'zj zk Navigate Folds',
        "keys": 'ggzjzjzjzjzkzk',
        "initial": '# Dungeon Generator\ndef gen_room(size):\n    width = size * 2\n    height = size\n    return width, height\n\ndef gen_monster(level):\n    hp = level * 50\n    attack = level * 10\n    return hp, attack\n\ndef gen_treasure(rarity):\n    gold = rarity * 100\n    item = pick_item(rarity)\n    return gold, item\n\ndef gen_trap(danger):\n    damage = danger * 25\n    return damage',
    },
    '0307_bracket_z': {
        "description": '[z ]z Fold Start End',
        "keys": '8G[z]z[z',
        "initial": 'class Castle:\n    def gate(self):\n        locked = True\n        key = "golden"\n        return locked\n    def tower(self):\n        height = 50\n        guards = 3\n        return guards\n    def dungeon(self):\n        prisoners = 5\n        escape = False\n        return escape\n    def throne(self):\n        king = "Arthur"\n        crown = True\n        return crown',
    },
    '0308_z_equals': {
        "description": 'z= Spelling Suggestions',
        "keys": 'wz=1\rj1z=',
        "initial": 'The brav knight rode into\nthe darkk forest. His sowrd\nglowed with enchantd light.\nVictory was certan.',
    },
    '0309_zg': {
        "description": 'zg Mark Word Correct',
        "keys": '2wzgj0wzgj0wzg',
        "initial": 'Run the kubectl command often.\nThis vimfu trick is handy.\nUse shellpilot to record demos.\nThe dropdown renders on hover.',
    },
    '0310_zw': {
        "description": 'zw Mark Word Incorrect',
        "keys": 'wzwj02wzw',
        "initial": 'We really need to ship this.\nIt was very easy to fix.\nNever hardcode passwords here.\nAlways sanitize form data.',
    },
    '0311_zug_zuw': {
        "description": 'zug zuw Undo Spelling Mark',
        "keys": 'j04wzgzugj04wzwzuw',
        "initial": 'The mage cast a fireball spell.\nThe rogue used a katana blade.\nThe healer brewed a potion mix.\nThe paladin wore shiny armor.',
    },
    '0312_zG_zW': {
        "description": 'zG zW Temporary Spelling',
        "keys": 'wzGj$bzW',
        "initial": 'Server recv the webhook data.\nThe parser handled the response.\nRetry after a backoff delay.\nClose the socket on errors.',
    },
    '0313_zuG_zuW': {
        "description": 'zuG zuW Undo Temp Spelling',
        "keys": '2wzGzuGj$bzWzuW',
        "initial": 'Deploy the hotfix to staging.\nThe plugin handles errors.\nRefactor the navbar component.\nEnable autosave for the workspace.',
    },
    '0314_bracket_s': {
        "description": '[s ]s Navigate Misspelled',
        "keys": 'gg]s]s]s[s[s',
        "initial": 'The sofware update is redy.\nPlease verifiy all the changes.\nThe performace looks gret now.\nEverything passd the final test.',
    },
    '0315_zp_zy': {
        "description": 'zp zP zy Block Paste',
        "keys": '2G\x162j$zy5G0zPuP',
        "initial": '# Tags\nA\nBCD\nE\nfoo\nbar\nbaz\n# End',
    },
    '0316_z_equals_practice': {
        "description": 'z= in Practice',
        "keys": ']s1z=]s1z=]s1z=',
        "initial": 'The missle launch was a succss.\nAll systms are operatonal now.\nThe engne passed every tst.\nFinal reivew is complet.',
    },
    '0317_bracket_paren': {
        "description": '[( ]) Unmatched Parens',
        "keys": '4G[([(])])',
        "initial": '# Damage Calculator\nresult = max(\n    base_attack * (\n        1 + crit_bonus\n    ),\n    min_damage\n)',
    },
    '0318_bracket_brace': {
        "description": '[{ ]} Unmatched Braces',
        "keys": '5G[{[{[{]}',
        "initial": 'void battle() {\n    if (hp > 0) {\n        attack();\n        if (crit) {\n            damage *= 2;\n        }\n    }\n}',
    },
    '0319_bracket_bracket': {
        "description": '[[ ]] Sections',
        "keys": ']]]]]]]][[[[',
        "initial": 'void init()\n{\n    hp = 100;\n    mp = 50;\n}\n\nvoid attack()\n{\n    damage = 25;\n    apply(damage);\n}\n\nvoid defend()\n{\n    shield = 40;\n    block(shield);\n}\n\nvoid heal()\n{\n    restore = 30;\n    apply(restore);\n}',
    },
    '0320_bracket_section': {
        "description": '[] ][ Section Ends',
        "keys": 'gg][][][[][]',
        "initial": 'void update()\n{\n    tick++;\n    physics();\n}\n\nvoid render()\n{\n    clear();\n    draw();\n}\n\nvoid cleanup()\n{\n    free(mem);\n    close(fd);\n}',
    },
    '0321_bracket_m': {
        "description": '[m ]m Methods',
        "keys": 'gg]m]m]m]m2G]M]M]M',
        "initial": 'class Player {\n  attack() {\n    this.power = 50;\n    return this.power;\n  }\n  defend() {\n    this.shield = 30;\n    return this.shield;\n  }\n  heal() {\n    this.hp += 25;\n    return this.hp;\n  }\n}',
    },
    '0322_bracket_c': {
        "description": '[c ]c Diff Changes',
        "keys": ']c]c[c[c',
        "initial": 'hp = 150\nmp = 50\nspeed = 15\narmor = 30\nluck = 5\ngold = 500',
    },
    '0323_bracket_s_spell': {
        "description": '[s ]s Spelling Navigation',
        "keys": '1z=]s1z=]s1z=[s',
        "initial": 'Fixd the login buton issue.\nThe pasword field now validates.\nImproved erro handling logic.\nAll tets pass successfuly.',
    },
    '0324_bracket_hash': {
        "description": '[# ]# Preprocessor',
        "keys": '5G[#j]#',
        "initial": '#ifndef CONFIG_H\n#define CONFIG_H\n\n#ifdef DEBUG\n  int log_level = 3;\n  int verbose = 1;\n  int trace = 1;\n#endif\n\nint max_hp = 100;\n\n#endif',
    },
    '0325_bracket_star': {
        "description": '[* ]* Comment Blocks',
        "keys": '5G[*3j]*6j[*',
        "initial": 'int mana = 100;\n\n/*\n * Cast a fireball spell.\n * Costs 25 mana per cast.\n * Deals area damage.\n */\nvoid fireball() {\n    mana -= 25;\n}\n\n/*\n * Heal the entire party.\n * Costs 50 mana.\n */\nvoid heal() {\n    mana -= 50;\n}',
    },
    '0326_bracket_quote': {
        "description": "[' ]' Navigate Marks",
        "keys": "3Gma5Gmb7Gmcgg]']']'['['",
        "initial": '# World Map\nforest = "Dark Woods"\nvillage = "Haven"\nmountain = "Peak"\ncastle = "Stronghold"\ndesert = "Dunes"\nocean = "Deep Blue"\nswamp = "Bog"\ncave = "Shadow"',
    },
    '0327_bracket_p': {
        "description": '[p ]p Put with Indent',
        "keys": '7Gyy3G]pup',
        "initial": 'def outer():\n    x = 10\n    y = 20\n    def inner():\n        a = 1\n        b = 2\n        return a + b\n    return x + y',
    },
    '0328_bracket_z_fold': {
        "description": '[z ]z Fold Boundaries',
        "keys": '7G[z]z',
        "initial": 'class Tower:\n    def floor_one(self):\n        goblins = 5\n        loot = "bronze"\n        return goblins\n    def floor_two(self):\n        orcs = 3\n        loot = "silver"\n        return orcs\n    def boss_floor(self):\n        dragon = 1\n        loot = "gold"\n        return dragon',
    },
    '0329_bracket_d': {
        "description": '[d ]d Show Define',
        "keys": '6G3w[d8G03w[d',
        "initial": '#define MAX_HP 100\n#define MAX_MP 50\n#define CRIT_RATE 15\n#define BASE_DMG 25\n\nint hp = MAX_HP;\nint mp = MAX_MP;\nint damage = BASE_DMG * CRIT_RATE;',
    },
    '0330_bracket_D': {
        "description": '[D ]D List Defines',
        "keys": '7G3w[D\r[d',
        "initial": '#define SIZE 10\n#define MAX 100\n#define SIZE 20\n#define MIN 1\n#define SIZE 30\n\nint buf[SIZE];\nint cap = MAX;',
    },
    '0331_bracket_i': {
        "description": '[i ]i Show Include',
        "keys": '5Gw[i\r6G3w[i\r',
        "initial": '#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    printf("Hello dungeon!");\n    int *loot = malloc(100);\n    free(loot);\n    return 0;\n}',
    },
    '0332_bracket_I': {
        "description": '[I ]I List Includes',
        "keys": '2G[I\r7G2w]I\r',
        "initial": '# Battle Engine\nhp = 100\nmax_hp = 200\ndef heal():\n    global hp\n    hp += 50\n    if hp > max_hp:\n        hp = max_hp\ndef damage(amt):\n    global hp\n    hp -= amt\n    if hp < 0:\n        hp = 0',
    },
    '0333_bracket_f': {
        "description": '[f ]f Go to File',
        "keys": '2Gwgf\x0f[f',
        "initial": '# Main Entry Point\nimport utils\n\nresult = utils.add(10, 20)\nprint(result)',
    },
    '0334_ctrl_w_s': {
        "description": 'Ctrl-W s Horizontal Split',
        "keys": '\x17s\x17jG\x17q',
        "initial": '# Hero Stats\nname = "Arthur"\nhp = 100\nmp = 50\nspeed = 12\narmor = 40\nluck = 7\nlevel = 15\nxp = 4200\ngold = 800',
    },
    '0335_ctrl_w_v': {
        "description": 'Ctrl-W v Vertical Split',
        "keys": '\x17v\x17lG\x17q',
        "initial": '# Player Stats\nstr = 18\ndex = 14\ncon = 16\nint_stat = 12\nwis = 10\ncha = 8\nhp = 120\nmp = 45\nstamina = 80\narmor = 25\nspeed = 12\nluck = 7\ncrit = 15\ndodge = 9\nblock = 11\nresist = 6\nattack = 22\ndefense = 18\nmagic = 14\nrange = 10\naccuracy = 85\nstealth = 12\nfocus = 19\nrage = 4\nmana_regen = 3\nhp_regen = 2',
    },
    '0336_ctrl_w_n': {
        "description": 'Ctrl-W n New Window',
        "keys": '\x17ni# Scratch pad\x1b\x17j',
        "initial": '# Active Quests\nquest_1 = "Slay the dragon"\nquest_2 = "Find the gem"\nquest_3 = "Save the village"',
    },
    '0337_ctrl_w_hjkl': {
        "description": 'Ctrl-W hjkl Navigate Splits',
        "keys": '\x17l\x17j\x17k\x17h',
        "initial": '# South Kingdom\ncastle = "Stonehold"\nlord = "Stone Lord"\narmy = 2000',
    },
    '0338_ctrl_w_w': {
        "description": 'Ctrl-W w Cycle Windows',
        "keys": '\x17w\x17w\x17w\x17W\x17W',
        "initial": '# File C\nwind = 300',
    },
    '0339_ctrl_w_tb': {
        "description": 'Ctrl-W t b Top and Bottom',
        "keys": '\x17b\x17t\x17b\x17t',
        "initial": '# Bottom Floor\nloot = "Gold"',
    },
    '0340_ctrl_w_p': {
        "description": 'Ctrl-W p Previous Window',
        "keys": '\x17j\x17p\x17p\x17p',
        "initial": '# Test File\nassert add(2, 3) == 5\nassert mul(4, 5) == 20\nprint("All tests pass!")',
    },
    '0341_ctrl_w_c': {
        "description": 'Ctrl-W c Close Window',
        "keys": '\x17j\x17c:b stats\r\x17s\x17c',
        "initial": '# Stats Module\nhp = 100\nmp = 50\nspeed = 12\narmor = 8',
    },
    '0342_ctrl_w_q': {
        "description": 'Ctrl-W q Quit Window',
        "keys": '\x17j\x17q\x17s\x17q',
        "initial": '# Loot Table\nsword = 50\nshield = 30\npotion = 10',
    },
    '0343_ctrl_w_o': {
        "description": 'Ctrl-W o Only Window',
        "keys": '\x17j\x17o\x17s\x17v\x17o',
        "initial": '# File C — Tests\nassert 1 + 1 == 2',
    },
    '0344_ctrl_w_HJKL': {
        "description": 'Ctrl-W H/J/K/L Move Window',
        "keys": '\x17H\x17K\x17J',
        "initial": '# Map Data\nmap_size = 64\ntiles = ["grass", "stone"]',
    },
    '0345_ctrl_w_r': {
        "description": 'Ctrl-W r/R Rotate Windows',
        "keys": '\x17r\x17r\x17R',
        "initial": '# File C — Blue\ncolor = "blue"',
    },
    '0346_ctrl_w_x': {
        "description": 'Ctrl-W x Exchange Windows',
        "keys": '\x17x\x17x',
        "initial": '# Villain\nname = "Dragon"\nhp = 500\nweapon = "fire breath"',
    },
    '0347_ctrl_w_T': {
        "description": 'Ctrl-W T Window to Tab',
        "keys": '\x17j\x17Tgtgt',
        "initial": '# Tests\nassert greet("Vim") == "Hello Vim"\nassert bye("Vim") == "Bye Vim"',
    },
    '0348_ctrl_w_plus_minus': {
        "description": 'Ctrl-W +/- Resize Height',
        "keys": '3\x17+2\x17-5\x17+',
        "initial": '# Log\nprint("OK")',
    },
    '0349_ctrl_w_angle': {
        "description": 'Ctrl-W >/< Resize Width',
        "keys": '5\x17>5\x17<\x17l5\x17>',
        "initial": '# Right\na = 30\nb = 40',
    },
    '0350_ctrl_w_equal': {
        "description": 'Ctrl-W = Equalize Windows',
        "keys": '5\x17+\x17=5\x17-\x17=',
        "initial": '# Gamma\nz = 3',
    },
    '0351_ctrl_w_underscore': {
        "description": 'Ctrl-W _ Max Height',
        "keys": '\x17_\x17=\x17j\x17_\x17=5\x17_',
        "initial": '# Small\nx = 0',
    },
    '0352_ctrl_w_pipe': {
        "description": 'Ctrl-W | Max Width',
        "keys": '\x17|\x17=\x17l\x17|',
        "initial": '# West\nsun = "sets"\ntime = "dusk"',
    },
    '0353_ctrl_w_d': {
        "description": 'Ctrl-W d Split Definition',
        "keys": '2G3w\x17d\x17c3G03w\x17d',
        "initial": '// Game Engine\nint result = ATTACK * 2;\nint block = DEFEND + 5;\nint hp = HP_MAX;\nint base_dmg = 10;\nint base_def = 5;\n\nvoid swing(void) {\n    base_dmg += 1;\n}\n\nvoid parry(void) {\n    base_def += 1;\n}\n\nvoid rest(void) {\n    hp = HP_MAX;\n}\n\nvoid step(void) {\n    swing();\n    parry();\n}\n\nint main(void) {\n    step();\n    rest();\n    return 0;\n}\n\n#define ATTACK 25\n#define DEFEND 10\n#define HP_MAX 100',
    },
    '0354_ctrl_w_f': {
        "description": 'Ctrl-W f Split File',
        "keys": 'jw\x17f',
        "initial": '# Main Script\nimport utils\n\nresult = utils.double(5)\nprint(result)',
    },
    '0355_ctrl_w_F': {
        "description": 'Ctrl-W F Split File at Line',
        "keys": 'ww:sp +4 app.py\r',
        "initial": 'ERROR in app.py:4\nTraceback:\n  File app.py line 4\n  connect() failed',
    },
    '0356_ctrl_w_i': {
        "description": 'Ctrl-W i Split Declaration',
        "keys": '6G$b\x17i\x17c',
        "initial": '# RPG System\nMAX_LEVEL = 99\nBASE_HP = 100\n\ndef level_up(hero):\n    if hero.level < MAX_LEVEL:\n        hero.hp += BASE_HP\n        hero.level += 1\n\nhero_hp = BASE_HP * 2',
    },
    '0357_ctrl_w_bracket': {
        "description": 'Ctrl-W ] Split Tag',
        "keys": '9Gww\x17\x1d\x17c',
        "initial": '# Spell System\ndef fireball(target):\n    return target - 40\n\ndef icebolt(target):\n    return target - 25\n\n# Cast spells\ndmg1 = fireball(100)\ndmg2 = icebolt(100)',
    },
    '0358_ctrl_w_preview': {
        "description": 'Ctrl-W } Preview Tag',
        "keys": '3Gww\x17}\r\x17z',
        "initial": '# Battle System\n# Combat resolution\nhit = slash(15)\ndef_val = block(8)\n\n# Stats tracking\nhp = 100\nmp = 50\nstamina = 75\narmor = 12\nattack = 18\ndefense = 9\nspeed = 14\nluck = 7\n\n# Status flags\npoisoned = False\nstunned = False\nburning = False\nfrozen = False\n\n# Definitions\ndef slash(power):\n    return power * 2\n\ndef block(armor):\n    return armor + 10\n',
    },
    '0359_ctrl_w_P': {
        "description": 'Ctrl-W P Preview Window',
        "keys": '9Gww\x17}\r\x17P\x17p\x17z',
        "initial": '# Crafting\ndef forge(ore):\n    return ore + 50\n\ndef brew(herbs):\n    return herbs * 3\n\n# Workshop\nsword = forge(10)\npotion = brew(5)',
    },
    '0360_ctrl_w_z': {
        "description": 'Ctrl-W z Close Preview',
        "keys": '9Gww\x17}\r\x17zjww\x17}\r\x17z',
        "initial": '# Item Shop\ndef buy(item, gold):\n    return gold - item.price\n\ndef sell(item, gold):\n    return gold + item.price // 2\n\n# Transaction\ncost = buy(sword, 100)\nearned = sell(potion, 50)',
    },
    '0361_ctrl_w_gf': {
        "description": 'Ctrl-W gf File in New Tab',
        "keys": 'jw\x17gfgt',
        "initial": '# Main App\nimport config\n\nif config.DEBUG:\n    print("Debug mode")',
    },
    '0362_ctrl_w_gF': {
        "description": 'Ctrl-W gF File in Tab at Line',
        "keys": 'WW\x17gF',
        "initial": 'TODO: fix app.py:6\nThe cleanup function needs\nproper error handling',
    },
    '0363_ctrl_w_gt': {
        "description": 'Ctrl-W gt/gT Tabs',
        "keys": '\x17gt\x17gt\x17gt\x17gT\x17gT',
        "initial": '# Green Team\npower = 85',
    },
    '0364_ctrl_w_gtab': {
        "description": 'Ctrl-W g<Tab> Last Tab',
        "keys": 'gtg\tg\tg\tg\tg\t',
        "initial": '# Tests\nassert double(5) == 10\nassert double(0) == 0',
    },
    '0365_ctrl_w_caret': {
        "description": 'Ctrl-W ^ Alternate File Split',
        "keys": ':e second.py\r\x17\x1e',
        "initial": '# Second File\nname = "beta"\nvalue = 2',
    },
    '0366_escape': {
        "description": 'Escape / Ctrl-[ Leave Insert',
        "keys": 'i\x1bi\x1b',
        "initial": '# Demo\nname = "vim"\nprint(name)',
    },
    '0367_ctrl_c': {
        "description": 'Ctrl-C Quick Leave Insert',
        "keys": 'Goabc\x03A = 40\x03',
        "initial": '# Demo\nx = 10\ny = 20\nz = 30',
    },
    '0368_ctrl_o': {
        "description": 'Ctrl-O One Normal Command',
        "keys": 'jIdef \x0f$:\x1bj$F"i world\x0fj\x0fdd\x1b',
        "initial": '# Demo File\ngreet()\n    print("hello")\n    print("world")\n    return True\n',
    },
    '0369_ctrl_h': {
        "description": 'Ctrl-H Backspace in Insert',
        "keys": 'jA\x08\x08mm\x08\x1b',
        "initial": '# Demo\nname = "vimm"\ncount = 42',
    },
    '0370_ctrl_w_insert': {
        "description": 'Ctrl-W Delete Word in Insert',
        "keys": 'ototal = calculate_result\x17compute_sum\x17\x17\x1b',
        "initial": '# Demo\nresult = 0',
    },
    '0371_ctrl_u_insert': {
        "description": 'Ctrl-U Delete Line in Insert',
        "keys": 'othis is the wrong text\x15total = 100\x1b',
        "initial": '# Demo\nresult = 0',
    },
    '0372_ctrl_t_insert': {
        "description": 'Ctrl-T Indent in Insert',
        "keys": '2jI\x14\x14\x1b',
        "initial": '# Demo\ndef run():\npass',
    },
    '0373_ctrl_d_insert': {
        "description": 'Ctrl-D Unindent in Insert',
        "keys": '2jI\x04\x1bjI\x04\x1b',
        "initial": '# Demo\ndef run():\n        pass\n        return',
    },
    '0374_ctrl_r_insert': {
        "description": 'Ctrl-R Insert Register',
        "keys": 'jf"l"ayiw3GjA\x12a\x1b',
        "initial": '# Demo\nfirst_name = "Alice"\nlast_name = "Smith"\nfull = ',
    },
    '0375_ctrl_a_insert': {
        "description": 'Ctrl-A Insert Previous Text',
        "keys": 'jA"hello"\x1bjA\x01\x1b',
        "initial": '# Demo\nline1 = \nline2 = ',
    },
    '0376_ctrl_at': {
        "description": 'Ctrl-@ Insert Previous + Leave',
        "keys": 'jA42\x1bjA\x00',
        "initial": '# Demo\na = \nb = \nc = ',
    },
    '0377_ctrl_e_insert': {
        "description": 'Ctrl-E Copy from Below',
        "keys": 'ji\x05\x05\x05\x05\x05\x05\x1b',
        "initial": '# Demo\n\nresult = 100',
    },
    '0378_ctrl_y_insert': {
        "description": 'Ctrl-Y Copy from Above',
        "keys": 'jo\x19\x19\x19\x19\x19\x1b',
        "initial": '# Demo\nfirst = 100\n',
    },
    '0379_ctrl_n': {
        "description": 'Ctrl-N Autocomplete Next',
        "keys": '3jAcal\x0e\x0e\x1b',
        "initial": '# Demo\ncalculate_total = 0\ncalculate_average = 0\nresult = ',
    },
    '0380_ctrl_p': {
        "description": 'Ctrl-P Autocomplete Prev',
        "keys": '4jApro\x10\x10\x1b',
        "initial": '# Demo\nprocess_data = 1\nprocess_file = 2\nprocess_text = 3\nx = ',
    },
    '0381_ctrl_k': {
        "description": 'Ctrl-K Digraph',
        "keys": 'jA\x0bCo \x0bDG \x0b+-\x1b',
        "initial": 'Special Characters:\n',
    },
    '0382_ctrl_v_insert': {
        "description": 'Ctrl-V Literal Character',
        "keys": 'jA\x16\t \x16065\x1b',
        "initial": 'Literal chars:\n',
    },
    '0383_ctrl_g_u': {
        "description": 'Ctrl-G u Break Undo',
        "keys": 'ofirst line\x07u\rsecond line\x1buu',
        "initial": '# Demo\n',
    },
    '0384_ctrl_g_U': {
        "description": "Ctrl-G U Don't Break Undo",
        "keys": 'j$iabc\x07U\x1b[DX\x1bu',
        "initial": '# Demo\ntext = ""',
    },
    '0385_ctrl_g_jk': {
        "description": 'Ctrl-G j/k Move in Insert',
        "keys": 'A\x07j\x07j\x07k\x1b',
        "initial": '# Row 1\n# Row 2\n# Row 3\n# Row 4\n# Row 5',
    },
    '0386_ctrl_x_ctrl_l': {
        "description": 'Ctrl-X Ctrl-L Line Completion',
        "keys": 'Gopri\x18\x0c\x0c\x1b',
        "initial": '# Demo\nprint("hello world")\nprint("goodbye world")\nresult = 42\n',
    },
    '0387_ctrl_x_ctrl_f': {
        "description": 'Ctrl-X Ctrl-F File Completion',
        "keys": 'jA con\x18\x06\x1b',
        "initial": '# Demo\nimport ',
    },
    '0388_ctrl_x_ctrl_k': {
        "description": 'Ctrl-X Ctrl-K Dictionary Complete',
        "keys": ':set dictionary=words.txt\rjAal\x18\x0b\x1b',
        "initial": 'Project notes:\n',
    },
    '0389_ctrl_x_ctrl_t': {
        "description": 'Ctrl-X Ctrl-T Thesaurus',
        "keys": ':set thesaurus=thes.txt\rjAfast\x18\x14\x1b',
        "initial": 'The program is:\n',
    },
    '0390_ctrl_x_ctrl_i': {
        "description": 'Ctrl-X Ctrl-I Identifier Complete',
        "keys": '4jAfi\x18\t\x1b',
        "initial": '# Demo\nfirst_value = 10\nfinal_result = 20\nfigure_out = 30\nx = ',
    },
    '0391_ctrl_x_ctrl_d': {
        "description": 'Ctrl-X Ctrl-D Define Complete',
        "keys": '3jf;iMAX\x18\x04\x1b',
        "initial": '#define MAX_SIZE 100\n#define MIN_SIZE 10\n#define MAX_COUNT 50\nint x = ;',
    },
    '0392_ctrl_x_ctrl_bracket': {
        "description": 'Ctrl-X Ctrl-] Tag Completion',
        "keys": 'G$a cal\x18\x1d\x0e\x19\x1b',
        "initial": '# Demo\ndef calculate_sum(a, b):\n    return a + b\ndef calculate_avg(a, b):\n    return (a + b) / 2\nx =',
    },
    '0393_ctrl_x_ctrl_o': {
        "description": 'Ctrl-X Ctrl-O Omni Completion',
        "keys": '3j$a\x18\x0f\x19\x1b',
        "initial": '<!doctype html>\n<html>\n<body>\n<a h\n</body>\n</html>',
    },
    '0394_ctrl_x_ctrl_s': {
        "description": 'Ctrl-X Ctrl-S Spelling',
        "keys": ':set spell\rjArecieve\x18\x13\x1b',
        "initial": 'Project Notes:\n',
    },
    '0395_ctrl_x_ctrl_v': {
        "description": 'Ctrl-X Ctrl-V Vim Command Complete',
        "keys": 'Gosetl\x18\x16 number\x1b',
        "initial": 'let g:loaded = 1\n',
    },
    '0396_write': {
        "description": ':w Write (Save)',
        "keys": 'jA\nprint("world")\x1b::w\r',
        "initial": '# Demo\nprint("hello")',
    },
    '0397_write_as': {
        "description": ':w {file} Write As',
        "keys": '::w backup.py\r',
        "initial": '# Demo\nresult = 42\nprint(result)',
    },
    '0399_force_quit': {
        "description": ':q! Force Quit',
        "keys": 'ggdG::q!\r',
        "initial": '# Good Code\nprint("works")',
    },
}

SKIPPED = {
    '0398_quit': ['shell escape (:!)'],
    '0400_wq': ['shell escape (:!)'],
}
