"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0876_set_cursorline': {
        "description": ':set cursorline',
        "keys": ':set cursorline\r5j3j2k',
        "initial": 'import json\nimport os\nimport sys\n\ndef load_config():\n    with open("config.json") as f:\n        return json.load(f)\n\ndef main():\n    config = load_config()\n    print(config)',
    },
    '0877_toggle_settings': {
        "description": 'Toggling Settings with no Prefix',
        "keys": ':set number\r:set nonumber\r:set number!\r:set number!\r',
        "initial": 'def one():\n    return 1\n\ndef two():\n    return 2\n\ndef three():\n    return 3',
    },
    '0878_query_settings': {
        "description": 'Querying Settings with ?',
        "keys": ':set number?\r\r:set number\r:set number?\r\r:set tabstop?\r\r',
        "initial": 'Hello world\nThis is a demo\nFor querying settings',
    },
    '0879_set_numeric_values': {
        "description": 'Setting Numeric Values with =',
        "keys": ':set scrolloff=3\r:set scrolloff?\r\r:set tabstop=2\r:set ts?\r\r',
        "initial": 'Line 1\nLine 2\nLine 3\nLine 4\nLine 5\nLine 6\nLine 7\nLine 8\nLine 9\nLine 10',
    },
    '0879a_set_wrap': {
        "description": ':set wrap / nowrap',
        "keys": ':set nowrap\r:set wrap\r',
        "initial": 'Short line\nThis is a very long line that goes on and on and should extend well beyond the visible width of the terminal window to demonstrate wrapping behavior\nAnother short line\nEnd of file',
    },
    '0879b_set_list': {
        "description": ':set list / nolist',
        "keys": ':set list\r:set nolist\r',
        "initial": 'hello world   \n\tindented with tab\n  indented with spaces\nno trailing',
    },
    '0879c_set_splitbelow': {
        "description": ':set splitbelow',
        "keys": ':set splitbelow\r:split\r',
        "initial": 'def main():\n    print("hello")\n    return 0\n\nmain()',
    },
    '0879d_set_splitright': {
        "description": ':set splitright',
        "keys": ':set splitright\r:vsplit\r',
        "initial": 'def main():\n    print("hi")\n    return 0\n\nmain()',
    },
    '0879e_set_spell': {
        "description": ':set spell / nospell',
        "keys": ':set spell\r:set nospell\r',
        "initial": 'Meeting notes for today\nThe proejct is on schedul\nWe need to refator the code\nEverything else looks good',
    },
    '0879f_set_fileformat': {
        "description": ':set fileformat',
        "keys": ':set fileformat?\r\r:set fileformat=dos\r:set ff?\r\r:set ff=unix\r',
        "initial": 'Line one\nLine two\nLine three',
    },
    '0880aa_captured_groups': {
        "description": ':s Captured Groups',
        "keys": ':%s/\\(\\w\\+\\) \\(\\w\\+\\)/\\2, \\1/\r',
        "initial": 'John Smith\nJane Doe\nBob Jones\nAlice Lee',
    },
    '0880ab_vim_regex': {
        "description": 'Vim Regex Syntax',
        "keys": ':set hlsearch\r/\\w\\+\r/\\<cat\\>\r/cat\\|dog\r',
        "initial": 'cat cats\ndog dogs\nthe bat batted\nhat hats hatted',
    },
    '0880b_list_buffers': {
        "description": ':ls / :buffers',
        "keys": ':ls\r\r:buffers\r\r',
        "initial": 'print("three")',
    },
    '0880c_cycle_buffers': {
        "description": ':bn / :bp — Cycle Buffers',
        "keys": ':bn\r:bn\r:bp\r',
        "initial": '# Gamma file\nprint("gamma")',
    },
    '0880d_switch_buffer': {
        "description": ':b N / :b name — Switch Buffer',
        "keys": ':ls\r\r:b 3\r:b util\r',
        "initial": '# Configuration\nDEBUG = True',
    },
    '0880e_delete_buffer': {
        "description": ':bd — Delete Buffer',
        "keys": ':ls\r\r:bd\r:ls\r\r',
        "initial": 'print("three")',
    },
    '0880f_enew_buffer': {
        "description": ':enew — New Unnamed Buffer',
        "keys": ':enew\ri# scratch notes\x1b:ls\r\r',
        "initial": 'print("hello")',
    },
    '0880g_alternate_buffer': {
        "description": 'Ctrl-^ — Alternate Buffer',
        "keys": ':bn\r\x1e\x1e',
        "initial": '# Test code\ndef test_run():\n    assert run()',
    },
    '0880h_new_tab': {
        "description": ':tabnew / :tabe — New Tab',
        "keys": ':tabnew\r:tabe utils.py\r',
        "initial": '# Utilities\ndef helper():\n    return 42',
    },
    '0880i_cycle_tabs': {
        "description": ':tabn / :tabp — Cycle Tabs',
        "keys": ':tabn\r:tabn\r:tabp\rgtgT',
        "initial": '# File C',
    },
    '0880j_close_tab': {
        "description": ':tabc — Close Tab',
        "keys": 'gt:tabc\r',
        "initial": '# File C',
    },
    '0880k_only_tab': {
        "description": ':tabo — Only Tab',
        "keys": 'gt:tabo\r',
        "initial": '# File D',
    },
    '0880l_window_to_tab': {
        "description": 'Ctrl-W T — Window to Tab',
        "keys": '\x17Tgt',
        "initial": '# Bottom window\ndef bottom():\n    pass',
    },
    '0880m_horizontal_split': {
        "description": ':sp — Horizontal Split',
        "keys": ':sp\r:sp other.py\r',
        "initial": '# Another file\nx = 42',
    },
    '0880n_vertical_split': {
        "description": ':vs — Vertical Split',
        "keys": ':vs right.py\r\x17h\x17l',
        "initial": '# Right file\ndef right():\n    return 2',
    },
    '0880o_new_window': {
        "description": ':new — New Window',
        "keys": ':new\ri# notes\x1b',
        "initial": 'def main():\n    print("hello")\n\nmain()',
    },
    '0880p_close_only': {
        "description": ':close / :only',
        "keys": ':close\r:only\r',
        "initial": '# File C',
    },
    '0880q_quit_all': {
        "description": ':qa — Quit All',
        "keys": 'o# changed\x1b:qa\r:qa!\x1b',
        "initial": '# File B\nprint("b")',
    },
    '0880r_write_all': {
        "description": ':wa — Write All',
        "keys": 'o# edited\x1b\x17jo# also edited\x1b:wa\r',
        "initial": 'print("two")',
    },
    '0880s_write_quit_all': {
        "description": ':wqa / :xa — Write All + Quit',
        "keys": 'o# done\x1b:xa\x1b',
        "initial": 'print("b")',
    },
    '0880t_retab': {
        "description": ':retab — Fix Tabs',
        "keys": ':set list listchars=tab:>-,space:·\r:set expandtab tabstop=4\r:retab\r:set nolist\r',
        "initial": 'def hello():\n\tprint("hi")\n\treturn True\n\ndef world():\n\tprint("world")',
    },
    '0880u_delmarks': {
        "description": ':delmarks — Delete Marks',
        "keys": 'ma2jmb2jmc:marks abc\r\r:delm a\r:delm!\r',
        "initial": 'line one\nline two\nline three\nline four\nline five\nline six',
    },
    '0880v_undolist': {
        "description": ':undolist — Undo Info',
        "keys": 'ochange one\x1bochange two\x1bochange three\x1b:undolist\r\r',
        "initial": 'start',
    },
    '0880w_pwd': {
        "description": ':pwd — Current Directory',
        "keys": ':pwd\r:cd /tmp\r:pwd\r',
        "initial": 'hello world',
    },
    '0880x_file_info': {
        "description": ':file — File Info',
        "keys": ':file\r5jo# modified\x1b:file\r',
        "initial": 'import os\nimport sys\n\ndef main():\n    print("hello")\n    return 0\n\nif __name__ == "__main__":\n    main()',
    },
    '0880y_alternate_delimiters': {
        "description": ':s Alternate Delimiters',
        "keys": ':%s#/usr/local#/opt#g\ru:%s!/usr/local!/opt!g\r',
        "initial": '/usr/local/bin/python\n/usr/local/lib/libfoo.so\n/usr/local/share/docs',
    },
    '0880z_backreference': {
        "description": ':s Backreference &',
        "keys": ':%s/\\w\\+/[&]/g\ru:%s/.*/ - &/\r',
        "initial": 'apple\nbanana\ncherry\ndate\nelderberry',
    },
    '0881_recipe_delete_block': {
        "description": 'Recipe: Delete a Block of Lines',
        "keys": ':set number\r:5,15d\r',
        "initial": 'Buy groceries\nClean kitchen\nFix the porch\nWash the car\nOld task one\nOld task two\nOld task three\nOld task four\nOld task five\nOld task six\nOld task seven\nOld task eight\nOld task nine\nOld task ten\nOld task eleven\nPlan vacation\nCall dentist\nRead a book',
    },
    '0882_recipe_duplicate': {
        "description": 'Recipe: Duplicate a Section',
        "keys": ':set number\r:1,3t 11\r',
        "initial": '[server]\nhost = localhost\nport = 8080\n\n[database]\nhost = db.local\nport = 5432\n\n[cache]\nhost = redis.local\nport = 6379',
    },
    '0883_recipe_move_code': {
        "description": 'Recipe: Move Code Around',
        "keys": ':set number\r:10,12m 0\r',
        "initial": 'def cleanup():\n    remove_temp()\n    close_logs()\n\ndef process():\n    load_data()\n    transform()\n    save_results()\n\ndef setup():\n    init_config()\n    open_logs()',
    },
    '0884_recipe_mass_rename': {
        "description": 'Recipe: Mass Rename',
        "keys": ':%s/price/cost/g\r',
        "initial": 'price = 10\ntax = price * 0.08\ndiscount = price * 0.1\nfinal = price + tax - discount\nprint("Price:", price)\nprint("Final:", final)',
    },
    '0885_recipe_delete_comments': {
        "description": 'Recipe: Delete All Comments',
        "keys": ':g/^#/d\r',
        "initial": '# Server settings\nhost = "localhost"\nport = 8080\n# Database config\ndb_name = "myapp"\n# Enable debug mode\ndebug = True\n# Timeout value\ntimeout = 30\nuser = "admin"',
    },
    '0886_recipe_add_to_every_line': {
        "description": 'Recipe: Add to Every Line',
        "keys": ':%norm A;\r',
        "initial": 'let x = 1\nlet y = 2\nlet z = x + y\nconsole.log(x)\nconsole.log(y)\nconsole.log(z)',
    },
    '0887_recipe_number_lines': {
        "description": 'Recipe: Number All Lines',
        "keys": ":%s/^/\\=line('.').' '/\r",
        "initial": 'apple\nbanana\ncherry\ndate\nelderberry\nfig\ngrape',
    },
    '0888_recipe_sort_dedup': {
        "description": 'Recipe: Sort and Deduplicate',
        "keys": ':%sort u\r',
        "initial": 'banana\napple\ncherry\napple\ndate\nbanana\ncherry\nfig\napple\ndate',
    },
    '0889_recipe_reverse_file': {
        "description": 'Recipe: Reverse File Order',
        "keys": ':g/^/m 0\r',
        "initial": '1. First\n2. Second\n3. Third\n4. Fourth\n5. Fifth\n6. Sixth\n7. Seventh\n8. Eighth',
    },
    '0890_recipe_extract_matching': {
        "description": 'Recipe: Extract Matching Lines',
        "keys": ':v/TODO/d\r',
        "initial": 'setup database\nTODO: fix login bug\nwrite tests\nTODO: add validation\ndeploy server\nTODO: update docs\nclean temp files\nrun benchmarks\nTODO: refactor API',
    },
    '0891_recipe_comment_range': {
        "description": 'Recipe: Comment Out a Range',
        "keys": ':set number\r:3,7norm I# \r',
        "initial": 'def process():\n    load_data()\n    validate()\n    transform()\n    save()\n    notify()\n    cleanup()\n    report()\n\ndef main():\n    process()',
    },
    '0892_recipe_indent_block': {
        "description": 'Recipe: Indent a Block',
        "keys": ':set number\r:set shiftwidth=4\r:2,5>\r',
        "initial": 'def greet():\nname = "World"\nmsg = "Hello, " + name\nprint(msg)\nreturn msg\n\ngreet()',
    },
    '0893_recipe_yank_register': {
        "description": 'Recipe: Yank to Named Register',
        "keys": ':set number\r:1,4y a\rG"ap',
        "initial": 'alpha()\nbravo()\ncharlie()\ndelta()\n\n# paste here:',
    },
    '0894_recipe_sort_imports': {
        "description": 'Recipe: Sort Imports',
        "keys": ':set number\r:1,6sort\r',
        "initial": 'import sys\nimport json\nimport os\nimport re\nimport math\nimport csv\n\ndef main():\n    pass',
    },
    '0895_recipe_clean_whitespace': {
        "description": 'Recipe: Clean Trailing Whitespace',
        "keys": ':set list listchars=tab:>-,trail:·,space:·\r:%s/\\s\\+$//g\r',
        "initial": 'name = "Alice"   \nage = 30         \ncity = "NYC"     \nscore = 95       \ngrade = "A"      ',
    },
}

SKIPPED = {
    '0880_shell_command': ['shell escape (:!)'],
    '0880a_filter_lines': ['shell escape (:!)'],
}
