"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0701_ds_quotes': {
        "description": 'Delete Surrounding Quotes',
        "keys": 'f"ds"ujf\'ds\'ujf`ds`',
        "initial": 'name = "Alice"\nlabel = \'hero\'\ncmd = `ls -la`',
    },
    '0702_ds_parens': {
        "description": 'Delete Surrounding Parentheses',
        "keys": 'f4ds)ujfxdsbu',
        "initial": 'result = (42)\nvalue = (x + y)\ndata = (a, b, c)',
    },
    '0703_ds_brackets': {
        "description": 'Delete Surrounding Brackets',
        "keys": 'f1ds]ujfadsr',
        "initial": 'items = [1, 2, 3]\nfirst = ["alpha"]\ncoord = [x, y]',
    },
    '0704_ds_braces': {
        "description": 'Delete Surrounding Braces',
        "keys": 'fnds}ujf1dsB',
        "initial": 'let obj = {name: "Kai"}\nlet set = {1, 2, 3}\nlet map = {a: 1}',
    },
    '0705_ds_angle_brackets': {
        "description": 'Delete Surrounding Angle Brackets',
        "keys": 'fsds>ujfidsa',
        "initial": 'type = <string>\nval  = <int>\nref  = <T>',
    },
    '0706_ds_tags': {
        "description": 'Delete Surrounding Tags',
        "keys": 'fhdstujfwdst',
        "initial": '<div>hello</div>\n<em>world</em>\n<p>content here</p>',
    },
    '0707_ds_opening_mark_trims_space': {
        "description": 'Delete — Opening Mark Trims Space',
        "keys": 'fxds)jfxds(',
        "initial": 'val = ( x + y )\ncopy = ( x + y )',
    },
    '0708_ds_arbitrary': {
        "description": 'Delete Arbitrary Surroundings',
        "keys": 'fbds*ujfids_ujfcds|',
        "initial": 'Use *bold* text\nUse _italic_ text\nUse |column| data',
    },
    '0709_ds_c_style_comments': {
        "description": 'Delete C-Style Comments',
        "keys": 'ftds/jfods/',
        "initial": 'x = /* temp */ 42;\ny = /* old */ 99;',
    },
    '0710_ds_with_count': {
        "description": 'Delete with Count',
        "keys": 'fxds)jfx2ds)jfhdstjfh2dst',
        "initial": 'one = ((x + y) * z)\ntwo = ((x + y) * z)\nhtml1 = <div><span>hi</span></div>\nhtml2 = <div><span>hi</span></div>',
    },
    '0711_cs_quotes': {
        "description": 'Change Quotes',
        "keys": 'fAcs"\'ujfHcs\'"ujfhcs"`',
        "initial": 'name = "Alice"\ntitle = \'Hero\'\npath = "home/user"',
    },
    '0712_cs_brackets_to_parens': {
        "description": 'Change Brackets to Parens',
        "keys": 'f1cs])ujjfacs}]',
        "initial": 'items = [1, 2, 3]\ncoord = [x, y]\ndata = {a: 1}',
    },
    '0713_cs_add_inner_space': {
        "description": 'Change — Add Inner Space',
        "keys": 'fxcs){ucs)}ujf1cs][',
        "initial": 'val = (x+y)\narr = [1,2,3]',
    },
    '0714_cs_trim_inner_space': {
        "description": 'Change — Trim Inner Space',
        "keys": 'fxcs(}ucs)}',
        "initial": 'val = ( x + y )\narr = [ 1, 2, 3 ]',
    },
    '0715_cs_to_html_tag': {
        "description": 'Change to HTML Tag',
        "keys": 'fHcs"tem>\rjfCcs"th1>\r',
        "initial": 'title = "Hello World"\nlabel = "Click Me"',
    },
    '0716_cs_tag_to_tag': {
        "description": 'Change Tag to Tag',
        "keys": 'fHcstdiv>\rjfCcststrong>\r',
        "initial": '<p>Hello World</p>\n<span>Click Me</span>\n<em>important</em>',
    },
    '0717_cs_tag_to_quote': {
        "description": 'Tag to Quote in Two Steps',
        "keys": 'fhdstysiw"j0fwdstysiw\'',
        "initial": '<em>hello</em>\n<strong>world</strong>',
    },
    '0718_cs_separate_lines': {
        "description": 'Change on Separate Lines',
        "keys": 'fxcS"(u',
        "initial": 'val = "x + y + z"',
    },
    '0719_cs_word_target': {
        "description": 'Change with Target Aliases',
        "keys": 'fhcsq)jf[llcsr}',
        "initial": 'name = "hello"\nitems = [alpha beta]',
    },
    '0720_ys_word': {
        "description": 'Surround a Word',
        "keys": 'fhysiw)uysiw"ujfwysiw]',
        "initial": 'name = hello\nval = world\nkey = data',
    },
    '0721_ys_with_space': {
        "description": 'Surround with Space',
        "keys": 'fhysiw)uysiw(ujfwysiw{',
        "initial": 'name = hello\nval = world',
    },
    '0722_ys_big_word': {
        "description": 'Surround a WORD',
        "keys": 'f/ysaW}ufhysiw}',
        "initial": 'path = /home/user\nurl = http://example.com',
    },
    '0723_ys_with_motion': {
        "description": 'Surround with Motion',
        "keys": 'fhys$"ujfcysf."',
        "initial": 'msg = hello world\npath = config.yaml',
    },
    '0724_yss_whole_line': {
        "description": 'Surround the Whole Line',
        "keys": 'yss)ujyss)u',
        "initial": 'hello world\n    return x + y\nprint result',
    },
    '0725_ys_with_tag': {
        "description": 'Surround with Tag',
        "keys": 'ysiwtem>\rjysstp>\r',
        "initial": 'Hello World\nClick Here\nRead More',
    },
    '0728_ys_function_call': {
        "description": 'Surround with Function Call',
        "keys": 'fvysiwfprint\rujfnysiwflen\r',
        "initial": 'result = value\noutput = name\ndata = items',
    },
    '0729_ys_function_extra_space': {
        "description": 'Change Function Name',
        "keys": 'fvcsfdebug\rjfncsfstr\r',
        "initial": 'result = print(value)\noutput = len(name)',
    },
    '0730_ys_function_inside_parens': {
        "description": 'Delete Function Call',
        "keys": 'fvdsfjfndsf',
        "initial": 'result = print(value)\noutput = len(name)',
    },
    '0731_ys_arbitrary_char': {
        "description": 'Surround with Arbitrary Character',
        "keys": 'ysiw*ujfiysiw_ujfcysiw`',
        "initial": 'bold text here\nitalic text here\ncode text here',
    },
    '0732_ys_code_block': {
        "description": 'Surround with Code Block',
        "keys": 'ySS{',
        "initial": 'return x + y',
    },
    '0734_ys_leading_space': {
        "description": 'Delete with s Alias',
        "keys": 'fhdssjfwdss',
        "initial": 'one = (hello)\ntwo = "world"',
    },
    '0735_ys_separate_lines': {
        "description": 'Surround on Separate Lines',
        "keys": 'fvySiw(u',
        "initial": 'result = value\ndata = items',
    },
    '0736_yss_separate_lines': {
        "description": 'Surround Entire Line on Separate Lines',
        "keys": 'ySS{u',
        "initial": 'return x + y',
    },
    '0737_visual_surround_charwise': {
        "description": 'Visual Surround — Characterwise',
        "keys": 'fgv11lS]j0f/v6lS"',
        "initial": 'total = red + green + blue + alpha\nroute = /api/v1/users',
    },
    '0738_visual_surround_linewise': {
        "description": 'Visual Surround — Linewise',
        "keys": 'VjjS{',
        "initial": 'First line\nSecond line\nThird line',
    },
    '0739_visual_surround_blockwise': {
        "description": 'Visual Surround — Blockwise',
        "keys": 'f1\x16jjS"u',
        "initial": 'alpha = 1\nbeta  = 2\ngamma = 3',
    },
    '0740_visual_gs': {
        "description": 'Visual gS',
        "keys": 'fvviwS}ugvgS}',
        "initial": 'const total = value;\nconsole.log(total);',
    },
    '0741_insert_mode_surround': {
        "description": 'Insert Mode Surround',
        "keys": 'A\x07s"hello\x1bu',
        "initial": 'val = ',
    },
    '0742_insert_mode_surround_lines': {
        "description": 'Insert Mode Surround on Separate Lines',
        "keys": 'A\x07S{return true;\x1b',
        "initial": 'function run() ',
    },
    '0800_what_is_command_line': {
        "description": 'What Is the Command Line?',
        "keys": ':\x1b:set number\r',
        "initial": '# Greeting App\n\ndef hello(name):\n    return f"Hello, {name}!"\n\ndef goodbye(name):\n    return f"Goodbye, {name}!"\n\nprint(hello("world"))\nprint(goodbye("world"))',
    },
}
