"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0801_running_command': {
        "description": 'Running a Command',
        "keys": ':set number\r:set cursorline\r',
        "initial": '# Counter\n\ncount = 0\n\ndef increment():\n    global count\n    count += 1\n    return count\n\ndef reset():\n    global count\n    count = 0',
    },
    '0802_canceling_command': {
        "description": 'Canceling a Command',
        "keys": ':delete\x1b:q\x1b',
        "initial": '# Config\n\nDEBUG = True\nVERBOSE = False\nMAX_RETRIES = 3\nTIMEOUT = 30\n\ndef load():\n    print("Config loaded")',
    },
    '0803_command_history': {
        "description": 'Command History',
        "keys": ':set number\r:set cursorline\r:set relativenumber\r:\x1b[A\x1b[A\x1b[B\x1b',
        "initial": '# Settings\n\ntheme = "dark"\nfont_size = 14\ntab_width = 4\nauto_save = True\nwrap_lines = False\nshow_hidden = False',
    },
    '0804_go_to_line_number': {
        "description": 'Go to a Line Number',
        "keys": ':5\r:10\r:1\r',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0805_current_line_dot': {
        "description": 'The Current Line .',
        "keys": ':5\r:.d\ru:.,.+3d\ru',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0806_last_line_dollar': {
        "description": 'The Last Line $',
        "keys": ':$\r:1\r:10,$d\ru',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0807_range_of_lines': {
        "description": 'A Range of Lines',
        "keys": ':3,7d\ru:1,3d\ru',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0808_entire_file_percent': {
        "description": 'The Entire File %',
        "keys": ':%d\ru',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0809_visual_range': {
        "description": "Visual Range '<,'>",
        "keys": ':3\rVjjj:d\ru',
        "initial": '# Colors\nred = "#ff0000"\ngreen = "#00ff00"\nblue = "#0000ff"\nyellow = "#ffff00"\ncyan = "#00ffff"\nmagenta = "#ff00ff"\nwhite = "#ffffff"\nblack = "#000000"\norange = "#ffa500"',
    },
    '0810_mark_based_ranges': {
        "description": 'Mark-Based Ranges',
        "keys": ":3\rma:7\rmb:'a,'bd\ru",
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0811_offsets_in_ranges': {
        "description": 'Offsets in Ranges',
        "keys": ':3\r:.,.+4d\ru:.+2\r',
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0812_combining_range_forms': {
        "description": 'Combining Range Forms',
        "keys": ":5\rma:'a,$d\ru:1,.d\ru",
        "initial": 'line 1 — alpha\nline 2 — bravo\nline 3 — charlie\nline 4 — delta\nline 5 — echo\nline 6 — foxtrot\nline 7 — golf\nline 8 — hotel\nline 9 — india\nline 10 — juliet\nline 11 — kilo\nline 12 — lima',
    },
    '0813_write_save': {
        "description": ':w — Write (Save)',
        "keys": 'GoOwner: Team Alpha\x1b:w\r',
        "initial": 'Project Notes\n\nDeadline: Friday\nStatus: In Progress\nPriority: High',
    },
    '0815_write_and_quit': {
        "description": ':wq — Write and Quit',
        "keys": 'GoStatus: started\x1b:wq\r',
        "initial": 'First draft\n\nIdea: learn Vim\nGoal: be faster\nPlan: practice daily',
    },
    '0816_write_and_quit_smart': {
        "description": ':x — Write and Quit (Smart)',
        "keys": 'Gotimeout = 30\x1b:x\r',
        "initial": 'host = localhost\nport = 8080\ndebug = true\nlog_level = info',
    },
    '0817_quit': {
        "description": ':q — Quit',
        "keys": ':q\r',
        "initial": 'README\n\nThis is a sample project.\nVersion 1.0\nLicense: MIT',
    },
    '0818_force_quit': {
        "description": ':q! — Force Quit',
        "keys": 'GoIMPORTANT DATA\x1b:q\r:q!\r',
        "initial": 'Scratch pad\n\nTemporary notes here\nDelete when done\nNothing important',
    },
    '0819_edit_file': {
        "description": ':e {file} — Edit a File',
        "keys": ':e utils.py\r:e main.py\r',
        "initial": '# Utilities\n\ndef helper():\n    return "I am helping!"\n\ndef format(text):\n    return text.strip().upper()',
    },
    '0820_revert_to_saved': {
        "description": ':e! — Revert to Saved',
        "keys": 'dddddd:e!\r',
        "initial": 'TODO List\n\n- Learn Vim basics\n- Practice motions\n- Master Ex commands\n- Build muscle memory',
    },
    '0821_save_as': {
        "description": ':sav {file} — Save As',
        "keys": ':sav report_v2.txt\r',
        "initial": 'Status Report\n\nDate: March 2026\nTeam: Alpha\nProgress: On track',
    },
    '0822_read_file': {
        "description": ':r {file} — Read a File',
        "keys": 'G:r sig.txt\r',
        "initial": '-- \nJane Smith\nSenior Developer\njane@example.com',
    },
    '0823_read_shell_output': {
        "description": ':r !{cmd} — Read Shell Output',
        "keys": 'G:r !date\r:r !ls\r',
        "initial": 'Build Log\n\nTimestamp:',
    },
    '0824_delete_lines': {
        "description": ':[range]d — Delete Lines',
        "keys": ':3d\ru:5,8d\ru',
        "initial": 'line 1 — buy apples\nline 2 — fix the bug\nline 3 — call Mom\nline 4 — send invoice\nline 5 — water plants\nline 6 — clean kitchen\nline 7 — read chapter 5\nline 8 — update resume\nline 9 — walk the dog\nline 10 — write tests',
    },
    '0825_delete_into_register': {
        "description": ':[range]d {reg} — Delete into Register',
        "keys": ':3d a\rG"ap',
        "initial": 'line 1 — header\nline 2 — intro\nline 3 — IMPORTANT\nline 4 — details\nline 5 — summary\nline 6 — footer',
    },
    '0826_yank_lines': {
        "description": ':[range]y — Yank Lines',
        "keys": ':2,4y\rGpu',
        "initial": 'line 1 — Alice\nline 2 — Bob\nline 3 — Charlie\nline 4 — Diana\nline 5 — Eve\nline 6 — Frank\nline 7 — Grace\nline 8 — Hank',
    },
    '0827_yank_into_register': {
        "description": ':[range]y {reg} — Yank into Register',
        "keys": ':2,3y a\r:6,7y b\rG"ap"bp',
        "initial": 'line 1 — apple\nline 2 — banana\nline 3 — cherry\nline 4 — date\nline 5 — elderberry\nline 6 — fig\nline 7 — grape\nline 8 — honeydew',
    },
    '0828_move_lines': {
        "description": ':[range]m {address} — Move Lines',
        "keys": ':2m 6\ru:5,6m $\ru',
        "initial": 'line 1 — gather tools\nline 2 — read manual\nline 3 — install app\nline 4 — configure\nline 5 — run tests\nline 6 — deploy\nline 7 — monitor\nline 8 — celebrate',
    },
    '0829_copy_lines': {
        "description": ':[range]co {address} — Copy Lines',
        "keys": ':1co 7\ru:1,3co $\ru',
        "initial": 'line 1 — Monday\nline 2 — Tuesday\nline 3 — Wednesday\nline 4 — Thursday\nline 5 — Friday\nline 6 — Saturday\nline 7 — Sunday',
    },
    '0830_copy_synonym': {
        "description": ':[range]t {address} — Copy (Synonym)',
        "keys": ':4t 7\ru:3\r:t$\ru',
        "initial": 'line 1 — preheat oven\nline 2 — mix flour\nline 3 — add eggs\nline 4 — stir well\nline 5 — pour batter\nline 6 — bake 30 min\nline 7 — let cool',
    },
    '0831_join_lines': {
        "description": ':[range]j — Join Lines',
        "keys": ':2,3j\r:3,4j\ruu:2,3j!\ru',
        "initial": 'Jane Smith\n123 Main Street\nApartment 4B\nNew York\nNY 10001\nUSA',
    },
    '0832_put_register': {
        "description": ':pu {reg} — Put Register',
        "keys": ':1y a\r:3\r:pu a\ru:3\r:pu! a\ru',
        "initial": 'line 1 — header\nline 2 — navigation\nline 3 — sidebar\nline 4 — content\nline 5 — footer',
    },
    '0833_sort_lines': {
        "description": ':[range]sort — Sort Lines',
        "keys": ':%sort\ru:1,4sort\ru',
        "initial": 'banana\ncherry\napple\nfig\ndate\nelderberry\ngrape\nkiwi',
    },
    '0834_reverse_sort': {
        "description": ':[range]sort! — Reverse Sort',
        "keys": ':%sort\ru:%sort!\ru',
        "initial": 'Paris\nTokyo\nBerlin\nSydney\nCairo\nLondon\nRome\nNew York',
    },
    '0835_sort_options': {
        "description": ':[range]sort Options',
        "keys": ':%sort\r:%sort n\r:%sort nu\r:%sort iu\r',
        "initial": 'item 10\nitem 2\nApple\napple\nitem 30\nBanana\nbanana\nitem 1\nApple\nitem 20',
    },
    '0836_substitute_on_line': {
        "description": ':s/old/new/ Substitute on Line',
        "keys": ':s/cat/dog/\r2j:s/fox/cat/\r',
        "initial": 'the cat sat on the mat\nthe dog ran to the park\nthe fox fox jumped over',
    },
    '0837_substitute_g': {
        "description": ':s Flag g — All on Line',
        "keys": ':s/foo/NEW/\rj:s/old/new/g\r',
        "initial": 'foo bar foo baz foo\nold old old old old\nno repeats here',
    },
    '0838_substitute_i': {
        "description": ':s Flag i — Case Insensitive',
        "keys": ':s/hello/HI/g\r2j:s/foo/bar/gi\r',
        "initial": 'Hello hello HELLO hElLo\nWorld WORLD world\nfoo Foo FOO',
    },
    '0839_substitute_c': {
        "description": ':s Flag c — Confirm Each',
        "keys": ':%s/fix/done/gc\rynyq',
        "initial": 'fix the bug here\nfix this later\ndo not fix this one\nfix everything else',
    },
    '0840_substitute_n': {
        "description": ':s Flag n — Count Only',
        "keys": ':%s/error//gn\r:%s/warning//gn\r',
        "initial": 'error in module A\nwarning from parser\nerror in module B\nall good here\nerror in module C\nwarning from linter',
    },
    '0841_substitute_whole_file': {
        "description": ':%s/old/new/g Whole File',
        "keys": ':%s/foo/bar/g\r',
        "initial": 'name = "foo"\nprint(name)\nif name == "foo":\n    greet(name)\n# name is foo',
    },
    '0842_substitute_selection': {
        "description": ":'<,'>s Substitute in Selection",
        "keys": 'jV2j:s/item/fruit/g\r',
        "initial": 'item: apple\nitem: banana\nitem: cherry\nitem: date\nitem: elderberry\nitem: fig',
    },
    '0843_substitute_range': {
        "description": ':[range]s Substitute in Range',
        "keys": ':3,6s/x/y/g\r6G:.,$s/y/z/g\r',
        "initial": 'x = 1\nx = 2\nx = 3\nx = 4\nx = 5\nx = 6\nx = 7\nx = 8',
    },
    '0844_noh': {
        "description": ':noh Clear Search Highlighting',
        "keys": '/hello\r:noh\r',
        "initial": 'def hello():\n    print("hello")\n    return "hello"\n\ndef world():\n    print("world")',
    },
    '0845_marks': {
        "description": ':marks Show All Marks',
        "keys": 'jma3jmb:marks\rq',
        "initial": '# header\ndef alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass',
    },
    '0846_reg': {
        "description": ':reg Show All Registers',
        "keys": '"ayyj"byyj"cyy:reg abc\rq',
        "initial": 'alpha\nbeta\ngamma\ndelta',
    },
    '0847_print_lines': {
        "description": ':[range]p Print Lines',
        "keys": ':3p\r:5,8p\r\r',
        "initial": 'one\ntwo\nthree\nfour\nfive\nsix\nseven\neight',
    },
    '0848_print_with_numbers': {
        "description": ':[range]nu Print with Numbers',
        "keys": ':4nu\r:2,5nu\r\r',
        "initial": 'apple\nbanana\ncherry\ndate\nelderberry\nfig\ngrape\nhoneydew',
    },
    '0849_line_count': {
        "description": ':= Show Line Count',
        "keys": ':=\rGoline eight\x1b:=\r',
        "initial": 'line one\nline two\nline three\nline four\nline five\nline six\nline seven',
    },
    '0850_show_line_number': {
        "description": ':{range}= Show Line Number',
        "keys": '4j:.=\r:$=\r',
        "initial": 'alpha\nbeta\ngamma\ndelta\nepsilon\nzeta\neta\ntheta\niota\nkappa',
    },
    '0851_jumps': {
        "description": ':jumps Show Jump List',
        "keys": ':clearjumps\rG6Ggg:jumps\rq',
        "initial": '# config\nhost = "localhost"\nport = 8080\n\n# logic\ndef run():\n    pass\n\n# main\nif __name__ == "__main__":\n    run()',
    },
    '0852_changes': {
        "description": ':changes Show Change List',
        "keys": 'A edit\x1b3jA edit\x1b2jA edit\x1b:changes\rq',
        "initial": 'first\nsecond\nthird\nfourth\nfifth\nsixth',
    },
    '0853_indent_lines': {
        "description": ':[range]> Indent Lines',
        "keys": ':2>\r:3,4>\r',
        "initial": 'def greet():\nprint("hello")\nprint("world")\nreturn True\n\nx = greet()',
    },
    '0854_dedent_lines': {
        "description": ':[range]< Dedent Lines',
        "keys": ':2,4<\r',
        "initial": 'def run():\n        x = 1\n        y = 2\n        return x + y\n\nresult = run()',
    },
    '0855_visual_indent': {
        "description": 'Visual + :> :< Indent Selection',
        "keys": 'jV2j:>\rgvgv:<\r',
        "initial": 'if True:\nprint("a")\nprint("b")\nprint("c")\nprint("done")',
    },
    '0856_multiple_shifts': {
        "description": 'Multiple Shifts :>> :<<<',
        "keys": ':3,5>>\r:3<<<\r',
        "initial": 'class Game:\n    def run(self):\nstart()\nupdate()\nrender()\n    def stop(self):\n        pass',
    },
    '0857_norm_keys': {
        "description": ':%norm Append to Every Line',
        "keys": ':%norm A;\r',
        "initial": 'let x = 1\nlet y = 2\nlet z = 3\nlet w = 4\nlet v = 5',
    },
    '0858_norm_insert': {
        "description": ':norm with Insert Mode',
        "keys": ':%norm I# \r',
        "initial": 'start server\nload config\ncheck database\nopen ports\nbegin listening',
    },
    '0859_norm_range': {
        "description": ':norm on a Range',
        "keys": ':3,5norm A!\r',
        "initial": 'first\nsecond\nthird\nfourth\nfifth\nsixth\nseventh',
    },
    '0860_global': {
        "description": ':g/{pattern}/{cmd} Global Command',
        "keys": ':g/TODO/d\r',
        "initial": '# TODO: fix login\ndef login():\n    pass\n# TODO: add logging\ndef process():\n    pass\n# TODO: write tests\ndef test():\n    pass',
    },
    '0861_global_delete': {
        "description": ':g with :d — Delete Blank Lines',
        "keys": ':g/^$/d\r',
        "initial": 'header\n\nfirst item\n\n\nsecond item\n\nthird item\n\n\n\nfooter',
    },
    '0862_global_move': {
        "description": ':g with :m — Collect Matches',
        "keys": ':g/^import/m 0\r',
        "initial": 'import os\nx = 1\nimport sys\ny = 2\nimport json\nz = 3\nimport re',
    },
    '0863_global_norm': {
        "description": ':g with :norm',
        "keys": ':g/TODO/norm 0x\r',
        "initial": '# TODO fix auth\ndef auth():\n    pass\n# TODO add cache\ndef cache():\n    pass\n# DONE logging\ndef log():\n    pass',
    },
    '0864_global_substitute': {
        "description": ':g with :s — Substitute on Matches',
        "keys": ':g/class/+1s/old/new/g\r',
        "initial": 'class Dog(Animal):\n    name = "old"\nclass Cat(Animal):\n    name = "old"\ndef helper():\n    name = "old"',
    },
    '0865_inverse_global': {
        "description": ':v/{pattern}/{cmd} Inverse Global',
        "keys": ':v/keep/d\r',
        "initial": 'keep: apple\nremove this\nkeep: banana\njunk line\nkeep: cherry\nmore junk\nkeep: date',
    },
    '0866_v_keep_matches': {
        "description": ':v with :d — Keep Only Matches',
        "keys": ':v/ERROR/d\r',
        "initial": 'INFO: server started\nDEBUG: loading config\nERROR: disk full\nINFO: request received\nDEBUG: parsing input\nERROR: timeout\nINFO: response sent\nDEBUG: cleanup done',
    },
    '0867_set_number': {
        "description": ':set number',
        "keys": ':set number\r:set nonumber\r:set nu\r',
        "initial": 'import os\nimport sys\n\ndef greet(name):\n    print(f"Hello {name}")\n\ndef main():\n    greet("world")\n    return 0\n\nif __name__ == "__main__":\n    main()',
    },
    '0868_set_relativenumber': {
        "description": ':set relativenumber',
        "keys": ':set relativenumber\r5j:set number\r',
        "initial": 'import os\nimport sys\n\ndef add(a, b):\n    return a + b\n\ndef subtract(a, b):\n    return a - b\n\ndef multiply(a, b):\n    return a * b\n\ndef main():\n    print(add(2, 3))\n    print(subtract(5, 1))',
    },
    '0869_set_hlsearch': {
        "description": ':set hlsearch',
        "keys": ':set hlsearch\r/name\r:nohlsearch\r',
        "initial": 'def get_name():\n    name = input("Name: ")\n    return name\n\ndef greet(name):\n    print(f"Hi {name}")\n\nname = get_name()\ngreet(name)',
    },
    '0870_set_incsearch': {
        "description": ':set incsearch',
        "keys": ':set incsearch\r/trans\r',
        "initial": 'def process_data():\n    data = load()\n    result = transform(data)\n    save(result)\n\ndef transform(data):\n    return [x * 2 for x in data]\n\ndef load():\n    return [1, 2, 3]',
    },
    '0871_set_ignorecase': {
        "description": ':set ignorecase',
        "keys": ':set hlsearch\r/hello\r:set ignorecase\r/hello\r',
        "initial": 'Hello World\nhello there\nHELLO AGAIN\nSay hello\nGoodbye World',
    },
    '0872_set_smartcase': {
        "description": ':set smartcase',
        "keys": ':set ignorecase smartcase hlsearch\r/error\r/Error\r',
        "initial": 'Error: file not found\nerror in config\nERROR: disk full\nNo error here\nFatal Error detected',
    },
    '0873_set_scrolloff': {
        "description": ':set scrolloff',
        "keys": ':set scrolloff=5\r:15\rjjjjj8kkkkkk',
        "initial": 'Line 01\nLine 02\nLine 03\nLine 04\nLine 05\nLine 06\nLine 07\nLine 08\nLine 09\nLine 10\nLine 11\nLine 12\nLine 13\nLine 14\nLine 15\nLine 16\nLine 17\nLine 18\nLine 19\nLine 20\nLine 21\nLine 22\nLine 23\nLine 24\nLine 25\nLine 26\nLine 27\nLine 28\nLine 29\nLine 30',
    },
    '0874_set_expandtab': {
        "description": ':set expandtab / tabstop / shiftwidth',
        "keys": ':set expandtab tabstop=4 shiftwidth=4\rGo\tx = 42\x1b:set et? ts? sw?\r\r',
        "initial": 'def hello():\n    print("hi")\n    return True',
    },
    '0875_set_autoindent': {
        "description": ':set autoindent',
        "keys": ':set autoindent\rGostep_three()\x1b',
        "initial": 'def build():\n    step_one()\n    step_two()',
    },
}

SKIPPED = {
    '0814_write_to_file': ['shell escape (:!)'],
}
