"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0101_special_marks': {
        "description": 'Special Marks',
        "keys": 'jf"lcwcurious\x1bG\'.6jA  # welcome\x1bgg\'^u',
        "initial": 'name = "Bolt"\nmood = "happy"\nspeed = 5\nvolume = 7\n\ndef greet(human):\n    wave()\n    say("Hello!")\n    return smile()\n\ndef recharge():\n    find_outlet()\n    plug_in()\n    nap(hours=2)',
    },
    '0102_jump_back': {
        "description": 'Jump Back',
        "keys": '/fight\rG\x0f\x0f',
        "initial": 'level = 1\nboss = "Dragon"\ngems = 12\n\ndef explore(room):\n    if room.dark:\n        light_torch()\n    return room.loot\n\ndef fight(enemy):\n    while enemy.hp > 0:\n        swing(sword)\n    return "victory"\n\ndef rest():\n    heal(50)\n    save()',
    },
    '0103_jump_forward': {
        "description": 'Jump Forward',
        "keys": '/heal\rGgg\x0f\x0f\t\t',
        "initial": 'hero = "Kira"\nhp = 100\nmp = 40\n\ndef attack(target):\n    dmg = roll(2, 8)\n    target.hp -= dmg\n    return dmg\n\ndef heal(ally):\n    amt = roll(1, 6) + 5\n    ally.hp += amt\n    return amt\n\ndef flee():\n    speed = roll(1, 20)\n    return speed > 10',
    },
    '0104_last_jump_position': {
        "description": 'Last Jump Position',
        "keys": "/alert\r''''''''Gf(/fuel\r``/fuel\r''",
        "initial": 'crew = ["Kira", "Bolt"]\nfuel = 9001\ncourse = "Mars"\n\ndef navigate():\n    plot_course()\n    adjust_heading()\n    return "on course"\n\ndef alert(msg):\n    flash_lights()\n    play_alarm()\n    broadcast(msg)',
    },
    '0105_replace_mode': {
        "description": 'Replace Mode',
        "keys": 'fuRcu\x1bj0frRar\x1bjfERLE\x1b',
        "initial": 'hero = "resuce ops"\ndest = "Mras base"\nmode = "IDEL"\n\ndef launch():\n    countdown(3)\n    ignite("rockets")\n    yell("To the stars!")',
    },
    '0106_single_replace': {
        "description": 'Single Replace',
        "keys": 'frrl2j0fOr0jf r\r',
        "initial": 'shade = "brue"\ngems = 3\nhp = 1O0\nmix("herbs") heat(350)\n\ndef brew():\n    return "potion"',
    },
    '0107_indent_lines': {
        "description": 'Indent Lines',
        "keys": 'j>>j>>j2>>4j3>>',
        "initial": 'def cast_fireball():\ndamage = 50\ntarget = find_enemy()\ntarget.hp -= damage\nreturn "boom!"\n\ndef heal_ally(friend):\namount = 30\nfriend.hp += amount\nreturn "healed!"',
    },
    '0108_unindent_lines': {
        "description": 'Unindent Lines',
        "keys": 'j<<j<<j2<<4j3<<',
        "initial": 'def show_menu():\n        title = "Main Menu"\n        play = "Start"\n        quit = "Exit"\n        print(title)\n\ndef pick_option(n):\n        item = menu[n]\n        print(item)\n        return item',
    },
    '0109_indent_with_motion': {
        "description": 'Indent with Motion',
        "keys": 'j>j4j>2j5j>G',
        "initial": 'def attack(enemy):\ndamage = roll(2, 8)\nreturn "hit!"\n\ndef defend(shield):\nblock = shield.power\nprint("Blocked!")\nreturn block\n\ndef flee():\nspeed = roll(1, 20)\nreturn speed > 10',
    },
    '0110_auto_indent': {
        "description": 'Auto-Indent',
        "keys": 'j==2j==uugg=G',
        "initial": 'void cast_spell() {\nint mana = 50;\n    if (mana > 0) {\nprintf("Fireball!");\n        mana -= 25;\n}\nprintf("Done.");\n}',
    },
    '0111_visual_indent': {
        "description": 'Visual Indent',
        "keys": 'jV2j>5jV2j>V2j<u',
        "initial": 'def wake_up():\nprint("Booting...")\npower = 100\nmood = "happy"\n\ndef shutdown():\nprint("Goodnight.")\npower = 0\nmood = "sleepy"',
    },
    '0112_toggle_case': {
        "description": 'Toggle Case',
        "keys": '~~~~~~fF~~~~4u',
        "initial": 'health = "FULL"\nmana = "low"\nshield = "active"\nweapon = "SWORD"\narmor = "leather"',
    },
    '0113_uppercase_motion': {
        "description": 'Uppercase Motion',
        "keys": 'gUiwjgUiwjgU$ugUGu',
        "initial": 'max_mana = 200\nfire_damage = 50\nice_shield = True\ncrit_chance = 0.15\nboss_name = "dragon"',
    },
    '0114_lowercase_motion': {
        "description": 'Lowercase Motion',
        "keys": 'guiwjgu$jguGu',
        "initial": 'NAME = "WIZARD"\nTITLE = "GRAND"\nPOWER = 9001\nMOOD = "ANGRY"\nPET = "DRAGON"',
    },
    '0115_toggle_case_motion': {
        "description": 'Toggle Case Motion',
        "keys": 'g~iwjg~$jg~Gu',
        "initial": 'hero = "Knight"\nfoe = "GOBLIN"\nloot = "gold coin"\ntrap = "Spike Pit"\nquest = "RESCUE"',
    },
    '0116_visual_case': {
        "description": 'Visual Case',
        "keys": 'fkviwU2jviwu2jV~u',
        "initial": 'captain = "kirk"\nengineer = "scotty"\npilot = "SULU"\ndoctor = "bones"\nscience = "SPOCK"',
    },
    '0117_join_lines': {
        "description": 'Join Lines',
        "keys": '6jJ2jJJF xuuuu3j3J',
        "initial": 'toppings = [\n    "pepperoni",\n    "mushroom",\n    "olive",\n]\n\norder =\n    "large"\n\nprint(\n    toppings\n)',
    },
    '0118_join_without_space': {
        "description": 'Join Without Space',
        "keys": 'jJugJ3jgJ',
        "initial": '# Endpoint\nhttps://api.examp\nle.com/v2/users\n\n# Token\na1b2c3d4e5f6g7\nh8i9j0k1l2m3n4',
    },
    '0119_named_registers': {
        "description": 'Named Registers',
        "keys": '"ayyj"byy4j"ap"bp',
        "initial": 'sword = "Excalibur"\nshield = "Aegis"\npotion = "Elixir"\n\n# Loadout:\nweapon = ""\narmor = ""\nheal = ""',
    },
    '0120_append_to_register': {
        "description": 'Append to Register',
        "keys": '"ayy2j"Ayy2j"Ayy2j"ap',
        "initial": 'warrior = "Thorin"\nhealer = "Elrond"\nrogue = "Bilbo"\nmage = "Gandalf"\nranger = "Strider"\n\n# Party:\n',
    },
    '0121_the_unnamed_register': {
        "description": 'The Unnamed Register',
        "keys": 'yy4jpuggjddGpu""p',
        "initial": 'chips = "salty"\ncookie = "sweet"\ncarrot = "crunchy"\n\nfavorite = ""',
    },
    '0122_the_system_clipboard': {
        "description": 'The System Clipboard',
        "keys": '"+yy"+yiw5jf""+p',
        "initial": 'fireball = 50\nice_blast = 35\nlightning = 45\n\n# Copy to share:\npower = ""',
    },
    '0123_small_delete_register': {
        "description": 'Small Delete Register',
        "keys": 'f"di"4jf""-Puggdd',
        "initial": 'cat_name = "Whiskers"\ndog_name = "Buddy"\nfish_name = "Nemo"\n\nbest_pet = ""',
    },
    '0124_numbered_registers': {
        "description": 'Numbered Registers',
        "keys": 'yyjddddddG"0p"2p',
        "initial": 'sword = 1\nbow = 2\nstaff = 3\nwand = 4\n\n# Recover:',
    },
    '0124a_the_black_hole_register': {
        "description": 'The Black Hole Register',
        "keys": 'yyjddpuuggyyj"_ddp',
        "initial": 'keep = "gold"\njunk = "trash"\ncopy = "none"',
    },
    '0125_view_registers': {
        "description": 'View Registers',
        "keys": 'yyjdd"ayy:reg\r\r:reg a\r\r',
        "initial": 'cheese = "mozzarella"\nsauce = "marinara"\ncrust = "thin"\ntopping = "pepperoni"\n\norder = ""',
    },
    '0126_record_a_macro': {
        "description": 'Record a Macro',
        "keys": 'qacwDONE\x1bj0q@a@a@a',
        "initial": 'TODO buy milk\nTODO fix bug\nTODO call mom\nTODO ship feature\nTODO water plants',
    },
    '0127_stop_recording': {
        "description": 'Stop Recording',
        "keys": 'qbI# \x1bjjqqcq',
        "initial": 'name: goblin\nhp: 30\nname: troll\nhp: 80\nname: dragon\nhp: 500',
    },
    '0128_play_a_macro': {
        "description": 'Play a Macro',
        "keys": 'qaf=wi"\x1bA"\x1bj0q@a@a',
        "initial": 'item = apple\nitem = bread\nitem = candy\nitem = donut\nitem = egg',
    },
    '0129_repeat_last_macro': {
        "description": 'Repeat Last Macro',
        "keys": 'qacwlog\x1bj0q@a@@@@',
        "initial": 'print(msg1)\nprint(msg2)\nprint(msg3)\nprint(msg4)\nprint(msg5)',
    },
    '0130_counted_macros': {
        "description": 'Counted Macros',
        "keys": 'qaI"\x1bA"\x1bjq7@a99uggqaI"\x1bA"\x1bjq100@a',
        "initial": 'red 100\nblue 200\ngreen 300\nyellow 400\npink 500\norange 600\npurple 700\nwhite 800',
    },
    '0131_horizontal_split': {
        "description": 'Horizontal Split',
        "keys": '\x17sG\x17c:sp\r',
        "initial": 'name = "Zara"\nhealth = 100\nattack = 25\ndefense = 18\nspeed = 12\n\ndef heal(amount):\n    global health\n    health += amount\n    return health\n\ndef strike(target):\n    damage = attack - 5\n    target.health -= damage\n    return damage',
    },
    '0132_vertical_split': {
        "description": 'Vertical Split',
        "keys": '\x17vG\x17c:vs\r',
        "initial": 'name = "Falcon"\ncrew = 4\nfuel = 100\nspeed = 9\nshields = True\narmed = False\n\ndef launch():\n    ignite()\n    lift_off()\n\ndef cruise():\n    hold_course()\n    scan_ahead()\n\ndef engage():\n    shields_up()\n    lock_target()\n    fire()\n\ndef land():\n    slow_down()\n    deploy_gear()\n    touch_down()\n\ndef dock():\n    align()\n    clamp()\n    power_down()',
    },
    '0133_navigate_windows': {
        "description": 'Navigate Windows',
        "keys": '\x17j\x17k\x17l\x17h',
        "initial": 'north = "ice"\nsouth = "sand"\neast = "forest"\nwest = "ocean"\ncenter = "castle"',
    },
    '0134_close_window': {
        "description": 'Close Window',
        "keys": '\x17c:close\r:sp\r\x17c',
        "initial": 'boss = "Dragon King"\nhp = 9999\nweak_to = "ice"\nphase = 1\n\ndef roar():\n    shake_screen()\n    scare_party()',
    },
    '0135_only_window': {
        "description": 'Only Window',
        "keys": '\x17j\x17o:sp\r:vs\r:only\r',
        "initial": 'rooms = 42\ntraps = 7\nkeys = 3\nboss = "Minotaur"\nexit = "north"\n\ndef solve():\n    find_key()\n    dodge_trap()\n    fight_boss()\n    escape()',
    },
    '0136_the_a_key': {
        "description": 'The a Key',
        "keys": 'fkaers\x1b+feao\x1b+foas\x1b',
        "initial": 'name = "Whisk"\ncall = "mew"\nkind = "hot"\ntoy = "yarn"',
    },
    '0137_the_b_key': {
        "description": 'The b Key',
        "keys": '$bbbj$bb$2b',
        "initial": 'hero = "brave knight"\nquest = "find the lost crown"\nreward = "gold and glory"\nboss = "shadow dragon"',
    },
    '0138_the_c_key': {
        "description": 'The c Key',
        "keys": 'f"lcwTurbo\x1bjci"racing\x1bj0f"c$"turbo"\x1b',
        "initial": 'name = "Sparky"\njob = "cleaning"\nspeed = "slow"\nmood = "bored"\n\ndef work():\n    sweep("kitchen")',
    },
    '0139_the_d_key': {
        "description": 'The d Key',
        "keys": 'jdwudduf=d$u2jf"ldiw',
        "initial": 'keep = "treasure"\ntoss = "garbage"\nsave = "gold"\nburn = "trash"\n\ndef clean(bag):\n    for item in bag:\n        check(item)',
    },
    '0140_the_e_key': {
        "description": 'The e Key',
        "keys": 'eeeeeej03e',
        "initial": 'title = "midnight rain"\ngenre = "synth pop"\ntempo = 120\nkey = "A minor"',
    },
    '0141_the_f_key': {
        "description": 'The f Key',
        "keys": 'f=0f13j0fa;;j0df8',
        "initial": 'pizza = 12\nburger = 9\ntaco = 7\nbanana = 15\nsalad = 8',
    },
    '0142_the_g_key': {
        "description": 'The g Key',
        "keys": 'Gggj$ge0gUiwu',
        "initial": 'level = 1\nboss = "slime"\nloot = "potion"\ntrap = "spikes"\n\ndef explore():\n    walk()\n    fight()\n    collect()\n\ndef rest():\n    heal()\n    save()',
    },
    '0143_the_h_key': {
        "description": 'The h Key',
        "keys": '$hhhj$5h0h',
        "initial": 'direction = "left"\nsteps = 5\nspeed = "slow"\npath = "straight"',
    },
    '0144_the_i_key': {
        "description": 'The i Key',
        "keys": 'imy_\x1bjf"lisuper \x1bji\x1b',
        "initial": 'msg = "hello"\ntone = "friendly"\nurgent = False\nsent = False',
    },
    '0145_the_j_key': {
        "description": 'The j Key',
        "keys": 'jjjgg3j5GfHjj',
        "initial": 'level = 1\nhealth = 100\narmor = "iron"\nweapon = "sword"\ntitle = "The Hero Arrives at Dawn"\nhp = 5\nquest = "The Quest Begins at Dawn"',
    },
    '0146_the_k_key': {
        "description": 'The k Key',
        "keys": 'GkkkG2kGfCkk',
        "initial": 'floor = 5\nview = "sky"\nwind = "strong"\nbirds = 3\nquest = "Climb the Ancient Tower"\nlv = 2\ntitle = "Guardian of Crystal Spire"',
    },
    '0147_the_l_key': {
        "description": 'The l Key',
        "keys": 'lllj5l$l',
        "initial": 'name = "river"\ndepth = 4\nflow = "east"\nfish = "trout"',
    },
    '0148_the_m_key': {
        "description": 'The m Key',
        "keys": "maG'a5jmbgg'b",
        "initial": 'city = "tokyo"\npop = 14000000\narea = 2194\nrail = "metro"\npark = "ueno"\nhero = "samurai"\nquest = "find"\nboss = "dragon"',
    },
    '0149_the_n_key': {
        "description": 'The n Key',
        "keys": '/err\rnnN',
        "initial": 'info = "starting"\nerr = "disk full"\nwarn = "low mem"\nerr = "timeout"\ninfo = "all clear"\nerr = "not found"',
    },
    '0150_the_o_key': {
        "description": 'The o Key',
        "keys": 'onote = "urgent"\x1bu2jotag = "work"\x1bu',
        "initial": 'task = "clean"\ndone = False\nprio = "high"\ndue = "friday"',
    },
    '0151_the_p_key': {
        "description": 'The p Key',
        "keys": 'ddjpuuyypu',
        "initial": 'ace = 11\nking = 10\nqueen = 10\njack = 10',
    },
    '0152_the_q_key': {
        "description": 'The q Key',
        "keys": 'qacwval\x1bj0q@a@@',
        "initial": 'x = 1\nx = 2\nx = 3\nx = 4',
    },
    '0153_the_r_key': {
        "description": 'The r Key',
        "keys": 'rFjrI2j3rxu',
        "initial": 'fire = 10\nice = 8\nwind = 12\nrock = 6',
    },
    '0154_the_s_key': {
        "description": 'The s Key',
        "keys": 'spi\x1bu+f9s10\x1bu+fo3snew\x1b',
        "initial": 'x = 5\nhp = 9\ntag = "old"',
    },
    '0155_the_t_key': {
        "description": 'The t Key',
        "keys": 't=0f=j0dt=u',
        "initial": 'path = "paris"\ndest = "rome"\ndist = 690\nmode = "train"',
    },
    '0156_the_u_key': {
        "description": 'The u Key',
        "keys": 'ddujxudddduu',
        "initial": 'title = "sunrise"\nmood = "calm"\ntempo = "slow"\nkey = "C major"',
    },
    '0157_the_v_key': {
        "description": 'The v Key',
        "keys": 'veduv2wy3jveU',
        "initial": 'sword = "iron"\nshield = "oak"\npotion = "red"\ngold = 50',
    },
    '0158_the_w_key': {
        "description": 'The w Key',
        "keys": 'wwj03wj0dwu',
        "initial": 'name = "fireball"\ndmg = 40\nrange = "long"\ncost = 5',
    },
    '0159_the_x_key': {
        "description": 'The x Key',
        "keys": 'fgxjfoxj0fexp',
        "initial": 'hero = "knigght"\nquest = "slay the dragoon"\nwho = "teh knight"',
    },
    '0160_the_y_key': {
        "description": 'The y Key',
        "keys": 'yypujf"lyw2j0y$',
        "initial": 'pilot = "Zara"\nnav = "Rex"\ngunner = "Koda"\ncook = "Pip"',
    },
    '0161_the_z_key': {
        "description": 'The z Key',
        "keys": '24jzzztzb',
        "initial": 'floor_1 = "entrance"\nfloor_2 = "guard room"\nfloor_3 = "armory"\nfloor_4 = "kitchen"\nfloor_5 = "mess hall"\nfloor_6 = "barracks"\nfloor_7 = "training yard"\nfloor_8 = "stables"\nfloor_9 = "storage"\nfloor_10 = "workshop"\nfloor_11 = "forge"\nfloor_12 = "library"\nfloor_13 = "study"\nfloor_14 = "gallery"\nfloor_15 = "chapel"\nfloor_16 = "map room"\nfloor_17 = "war room"\nfloor_18 = "great hall"\nfloor_19 = "treasury"\nfloor_20 = "prison"\nfloor_21 = "dungeon"\nfloor_22 = "vault"\nfloor_23 = "lab"\nfloor_24 = "alchemy"\nfloor_25 = "throne room"\nfloor_26 = "balcony"\nfloor_27 = "clock tower"\nfloor_28 = "bell tower"\nfloor_29 = "archive"\nfloor_30 = "observatory"\nfloor_31 = "rooftop"\nfloor_32 = "sky dock"\nfloor_33 = "cloud walk"\nfloor_34 = "wind spire"\nfloor_35 = "star deck"\nfloor_36 = "portal"\nfloor_37 = "void"\nfloor_38 = "nexus"\nfloor_39 = "apex"\nfloor_40 = "summit"',
    },
    '0162_the_A_key': {
        "description": 'The A Key',
        "keys": 'A  # melee\x1buj0A  # gold\x1bujA;\x1bj.',
        "initial": 'item = "sword"\nprice = 100\nstock = 5\nnote = "sharp"',
    },
    '0163_the_B_key': {
        "description": 'The B Key',
        "keys": '$bbb$B2j$B',
        "initial": 'src = "/usr/local/bin"\ndst = "~/back-up/old"\nlog = "err.2024-01.txt"',
    },
    '0164_the_C_key': {
        "description": 'The C Key',
        "keys": 'f"C"dragon lord"\x1buj0f5C9001\x1bu2j0f"C"thunder"\x1b',
        "initial": 'name = "goblin king"\nhp = 500\natk = "fireball"\nweak = "ice"',
    },
    '0165_the_D_key': {
        "description": 'The D Key',
        "keys": 'f#Dujf#Du2jf#D',
        "initial": 'msg = "ok"  # old comment\nerr = "timeout"  # remove this\nwarn = "slow"  # and this too',
    },
    '0166_the_E_key': {
        "description": 'The E Key',
        "keys": 'f"leee0f"lEjf"lE',
        "initial": 'url = "https://api.game.io/v2"\nkey = "abc-123-xyz"\nttl = 3600',
    },
    '0167_the_F_key': {
        "description": 'The F Key',
        "keys": '$FkF[$dF,u',
        "initial": 'hand = ["ace", "king", "queen"]\nbet = 50\npot = 200',
    },
    '0168_the_G_key': {
        "description": 'The G Key',
        "keys": 'Ggg5G',
        "initial": 'room_1 = "entrance"\nroom_2 = "corridor"\nroom_3 = "trap"\nroom_4 = "armory"\nroom_5 = "vault"\nroom_6 = "boss"\nroom_7 = "treasure"\nroom_8 = "exit"',
    },
    '0169_the_H_key': {
        "description": 'The H Key',
        "keys": 'GHLHM5H3L',
        "initial": 'f01 = "lobby"\nf02 = "cafe"\nf03 = "gym"\nf04 = "pool"\nf05 = "spa"\nf06 = "shop"\nf07 = "bar"\nf08 = "club"\nf09 = "lab"\nf10 = "den"\nf11 = "loft"\nf12 = "roof"\nf13 = "deck"\nf14 = "dome"\nf15 = "nest"\nf16 = "peak"\nf17 = "core"\nf18 = "hub"',
    },
    '0170_the_I_key': {
        "description": 'The I Key',
        "keys": 'j$Imax_\x1buj$Imax_\x1buj$Imax_\x1b',
        "initial": 'def run():\n    speed = 10\n    fuel = 100\n    cargo = 50',
    },
    '0171_the_J_key': {
        "description": 'The J Key',
        "keys": 'Ju3JuV4jJ',
        "initial": 'the\nquick\nbrown\nfox\njumps',
    },
    '0172_the_K_key': {
        "description": 'The K Key',
        "keys": 'jwKq\rgg0wKq\r',
        "initial": "import os\nimport json\npath = os.getcwd()\ndata = json.loads('{}')",
    },
    '0173_the_L_key': {
        "description": 'The L Key',
        "keys": 'LH3L',
        "initial": 'lv01 = "start"\nlv02 = "forest"\nlv03 = "cave"\nlv04 = "river"\nlv05 = "mountain"\nlv06 = "desert"\nlv07 = "swamp"\nlv08 = "ruins"\nlv09 = "castle"\nlv10 = "tower"\nlv11 = "abyss"\nlv12 = "throne"\nlv13 = "lair"\nlv14 = "summit"\nlv15 = "void"\nlv16 = "nexus"\nlv17 = "omega"\nlv18 = "beyond"',
    },
    '0174_the_M_key': {
        "description": 'The M Key',
        "keys": 'MHLM',
        "initial": 'r01 = "bronze"\nr02 = "silver"\nr03 = "gold"\nr04 = "plat"\nr05 = "diamond"\nr06 = "master"\nr07 = "legend"\nr08 = "myth"\nr09 = "titan"\nr10 = "cosmic"\nr11 = "void"\nr12 = "omega"\nr13 = "apex"\nr14 = "prime"\nr15 = "ultra"\nr16 = "zenith"\nr17 = "astral"\nr18 = "eternal"',
    },
    '0175_the_N_key': {
        "description": 'The N Key',
        "keys": '/gem\rnNN',
        "initial": 'gem = "ruby"\nore = "iron"\ngem = "opal"\nore = "gold"\ngem = "jade"',
    },
    '0176_the_O_key': {
        "description": 'The O Key',
        "keys": 'jOprep = "wash"\x1buggO# cooking steps\x1bujostir = "mix"\x1b',
        "initial": 'step1 = "chop"\nstep2 = "boil"\nstep3 = "serve"',
    },
    '0177_the_P_key': {
        "description": 'The P Key',
        "keys": 'jyyggPuyawjwPu',
        "initial": 'alpha bravo\ncharlie delta\necho foxtrot\ngolf hotel',
    },
    '0178_the_Q_key': {
        "description": 'The Q Key',
        "keys": 'qaf"ci"done\x1bj0qQQ',
        "initial": 'tag = "wip"\ntag = "wip"\ntag = "wip"\ntag = "wip"',
    },
    '0179_the_R_key': {
        "description": 'The R Key',
        "keys": 'f"4lRXYZ\x1bu2j0f0R1337\x1bu',
        "initial": 'row = "ABCDEFGH"\ncol = "12345678"\npin = "0000"',
    },
    '0180_the_S_key': {
        "description": 'The S Key',
        "keys": 'jSmsg = "hey there"\x1bu2jSmood = "chill"\x1bu',
        "initial": 'def greet():\n    msg = "hello"\n    tone = "friendly"\n    return msg',
    },
    '0181_the_T_key': {
        "description": 'The T Key',
        "keys": '$T,j$dT,u2j$T(',
        "initial": 'cast = "fire(50,red)"\nheal = "cure(30,green)"\nbuff = "shield(99,blue)"',
    },
    '0182_the_U_key': {
        "description": 'The U Key',
        "keys": 'f"lveUu2jf"lvi"Uu',
        "initial": 'name = "hero"\nrank = "rookie"\nteam = "alpha squad"',
    },
    '0183_the_V_key': {
        "description": 'The V Key',
        "keys": 'jVjduGVdggPu',
        "initial": 'tank = "Grim"\nhealer = "Luna"\nscout = "Dash"\nmage = "Ember"\nrogue = "Shadow"',
    },
    '0184_the_W_key': {
        "description": 'The W Key',
        "keys": 'f"wwwwwF"Wj0f"wwwwF"W',
        "initial": 'host = "bob@dev-01.srv" # login\npath = "/var/log/app.db" # logs\nflag = "--no-cache" # fast',
    },
    '0185_the_X_key': {
        "description": 'The X Key',
        "keys": 'fKXujXujfk2X',
        "initial": 'player = " Kai"\nhp = 1009\nrank = "x_knight"',
    },
    '0186_the_Y_key': {
        "description": 'The Y Key',
        "keys": 'f1Yj$pujf4Yj$p',
        "initial": 'hp = 100\nmp = \nspeed = 42\nxp = \nlives = 3',
    },
    '0187_the_ZZ_ZQ_keys': {
        "description": 'ZZ and ZQ',
        "keys": 'f"ci"done\x1bZZjf"ci"ABORT\x1bZQ',
        "initial": 'status = "ready"\nmission = "go"',
    },
    '0188_the_0_key': {
        "description": 'The 0 Key',
        "keys": 'j$0j$^0j$d0u',
        "initial": 'def play():\n    hero = "knight"\n        hp = 100\n    attack()',
    },
    '0189_count_prefix': {
        "description": 'Count Prefix (1-9)',
        "keys": '5j4wgg12j',
        "initial": 'a = "sword"\nb = "bow"\nc = "spear"\nd = "axe"\ne = "mace"\nf = "staff"\ng = "shield"\nh = "lance"\ni = "dagger"\nj = "hammer"\nk = "flail"\nl = "pike"\nm = "whip"\nn = "sling"\no = "club"',
    },
    '0190_the_caret_key': {
        "description": 'The ^ Key',
        "keys": 'j$^2j$^k0d^u',
        "initial": 'def quest():\n    gold = 50\n        gem = 10\n            key = 1',
    },
    '0191_the_dollar_key': {
        "description": 'The $ Key',
        "keys": '$jwd$ugg2$',
        "initial": 'player = "ace"\npoints = 9999\nstreak = 42\nbonus = 100',
    },
    '0192_the_percent_key': {
        "description": 'The % Key',
        "keys": '%%j0%j%',
        "initial": 'total = sum(prices)\ndata = [1, [2, 3], 4]\nif (x > 0) {\n    print(x)\n}',
    },
    '0193_the_tilde_key': {
        "description": 'The ~ Key',
        "keys": 'f"l~j0f"l5~j0f"lvi"~',
        "initial": 'name = "link"\nboss = "GANON"\nworld = "hYrUlE"',
    },
    '0194_the_backtick_key': {
        "description": 'The ` Key (Backtick Mark)',
        "keys": 'jf"lmaG`a2jfvmbgg\'bgg`b',
        "initial": 'town = "haven"\nforest = "darkwood"\ncave = "crystal"\nriver = "silver"\npeak = "thunder"\nlake = "mirror"\nruins = "ancient"\nfort = "iron"',
    },
    '0195_the_apostrophe_key': {
        "description": "The ' Key (Apostrophe Mark)",
        "keys": "2jmaG'agg''Gd'au",
        "initial": 'biome1 = "plains"\nbiome2 = "jungle"\nbiome3 = "tundra"\nbiome4 = "desert"\nbiome5 = "ocean"\nbiome6 = "volcano"\nbiome7 = "swamp"\nbiome8 = "sky"',
    },
    '0197_the_at_key': {
        "description": 'The @ Key (Execute Macro)',
        "keys": 'qaIdone_\x1bjq@a@@2@a',
        "initial": 'task = "buy milk"\ntask = "fix bug"\ntask = "read book"\ntask = "run tests"\ntask = "clean desk"',
    },
    '0198_the_pound_key': {
        "description": 'The # Key',
        "keys": 'Gf"l###NNn',
        "initial": 'loot = "sword"\nrare = "gold"\nshield = "iron"\nhelm = "steel"\nring = "gold"\nboots = "leather"\nchest = "gold"\namulet = "ruby"\ngrail = "gold"',
    },
    '0199_the_star_key': {
        "description": 'The * Key',
        "keys": '**NN',
        "initial": 'cat = "whiskers"\ndog = "rex"\ncat = "mittens"\nbird = "tweety"\ncat = "shadow"\ndog = "spot"',
    },
    '0200_the_ampersand_key': {
        "description": 'The & Key',
        "keys": ':s/foo/bar\r2j&j&j&',
        "initial": 'old = "foo"\nold = "foo bar foo"\nold = "foo baz"\nold = "no match"\nold = "foo end"',
    },
}

SKIPPED = {
    '0196_the_bang_key': ['shell escape (:!)'],
}
