"""
AUTO-GENERATED by extract_video_cases.py. Do not edit by hand.
"""

CASES = {
    '0501_what_is_tmux': {
        "description": 'What Is tmux?',
        "keys": 'tmux\r\x02"\x02%\x02knvim hello.py\r\x02jpython3 hello.py\r',
        "initial": '',
    },
    '0502_starting_tmux': {
        "description": 'Starting tmux',
        "keys": 'tmux\rexit\rtmux\r',
        "initial": '',
    },
    '0503_the_prefix_key': {
        "description": 'The Prefix Key',
        "keys": '"\x15\x02"\x02%',
        "initial": '',
    },
    '0504_tmux_help': {
        "description": 'tmux Help',
        "keys": '\x02?\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B     \x1b',
        "initial": '',
    },
    '0505_split_horizontally': {
        "description": 'Split Horizontally',
        "keys": '\x02"echo \'bottom pane\'\r\x02"pwd\r',
        "initial": '',
    },
    '0506_split_vertically': {
        "description": 'Split Vertically',
        "keys": '\x02%echo \'right\'\r\x02"',
        "initial": '',
    },
    '0507_close_a_pane': {
        "description": 'Close a Pane',
        "keys": '\x02l\x02xy\x02xy',
        "initial": '',
    },
    '0508_navigate_panes': {
        "description": 'Navigate Panes',
        "keys": '\x02l\x02k\x02j\x02h',
        "initial": '',
    },
    '0509_cycle_panes': {
        "description": 'Cycle Panes',
        "keys": '\x02o\x02o\x02o\x02o\x02o\x02o',
        "initial": '',
    },
    '0510_last_active_pane': {
        "description": 'Last Active Pane',
        "keys": '\x02o\x02;\x02;\x02;\x02;\x02;',
        "initial": '',
    },
    '0511_zoom_a_pane': {
        "description": 'Zoom a Pane',
        "keys": '\x02z\x02z\x02o\x02z\x02z',
        "initial": 'def greet(name):\n    msg = f"Hello, {name}!"\n    return msg\n\nif __name__ == "__main__":\n    print(greet("world"))',
    },
    '0512_resize_panes': {
        "description": 'Resize Panes',
        "keys": '\x02\x1b[1;5C\x02\x1b[1;5C\x02\x1b[1;5C\x02\x1b[1;5D\x02\x1b[1;5D\x02\x1b[1;5D',
        "initial": "from flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return 'Hello!'\n\napp.run(port=5000)",
    },
    '0513_swap_panes': {
        "description": 'Swap Panes',
        "keys": '\x02{\x02}\x02}',
        "initial": '',
    },
    '0514_break_pane_to_window': {
        "description": 'Break Pane to Window',
        "keys": '\x02!\x020\x021',
        "initial": "from http.server import HTTPServer\n\ndef run(port=8080):\n    srv = HTTPServer(\n        ('', port), Handler\n    )\n    print(f'Listening :{port}')\n    srv.serve_forever()",
    },
    '0515_pane_numbers': {
        "description": 'Pane Numbers',
        "keys": '\x02q\x02q2\x02q0',
        "initial": 'PASS test_robot.py\n  ✓ battery starts full\n  ✓ speak returns beep\n',
    },
    '0516_create_a_window': {
        "description": 'Create a Window',
        "keys": '\x02c\x02c\x020',
        "initial": '12:00:01 INFO  build ok\n12:00:02 INFO  deploy staging\n12:00:03 WARN  cache miss\n',
    },
    '0517_next_previous_window': {
        "description": 'Next / Previous Window',
        "keys": '\x02n\x02n\x02p\x02p',
        "initial": '▸ Building image...     done\n▸ Pushing to registry... done\n▸ Rolling out pods...   2/3\n▸ Health check...       wait\n',
    },
    '0518_switch_to_window_n': {
        "description": 'Switch to Window N',
        "keys": '\x022\x023\x021\x020',
        "initial": '14:22:01 INFO  worker start\n14:22:02 INFO  fetch begin\n14:22:02 WARN  slow dns 210ms\n14:22:03 INFO  fetch done\n14:22:03 INFO  cache updated\n',
    },
    '0519_last_active_window': {
        "description": 'Last Active Window',
        "keys": '\x021\x02l\x02l\x02l',
        "initial": 'smtplib.SMTP\n\n  .starttls()  — upgrade to TLS\n  .login(u, p) — authenticate\n  .send_message(msg)\n\n  See also: email.mime\n',
    },
    '0520_rename_window': {
        "description": 'Rename Window',
        "keys": '\x02,\x01\x0bcode\r\x021\x02,\x01\x0btests\r',
        "initial": '',
    },
    '0521_close_a_window': {
        "description": 'Close a Window',
        "keys": '\x022\x02&y\x021\x02&y',
        "initial": '10:32 GET  /potions     200\n10:33 POST /brew        201\n10:33 GET  /inventory   200\n10:34 POST /brew        201\n10:35 GET  /health      200\n',
    },
    '0522_window_chooser': {
        "description": 'Window Chooser',
        "keys": '\x02wjj\r\x02wkk\r',
        "initial": '  Dungeon Map — Level 3\n  ──────────────────────\n  [START] → [CAVE]\n                ↓\n            [BRIDGE]\n                ↓\n         [BOSS CHAMBER]\n\n  Hero: Room 2 / 4\n',
    },
    '0523_cycle_layouts': {
        "description": 'Cycle Layouts',
        "keys": '\x02 \x02 \x02 \x02 \x02 ',
        "initial": '✓ boot sequence\n✓ motor check\n✓ sensor ping\n✗ wifi link\n3/4 passed\n',
    },
    '0524_detach_from_tmux': {
        "description": 'Detach from tmux',
        "keys": '\x02dtmux attach\r\x02d',
        "initial": '[deploy] Building image...    ✓\n[deploy] Running tests...     ✓\n[deploy] Pushing to registry  ✓\n[deploy] Rolling out v2.4.1\n[deploy] Pod 1/3 ready\n[deploy] Pod 2/3 ready\n[deploy] Waiting for pod 3...\n',
    },
    '0525_the_command_prompt': {
        "description": 'The Command Prompt',
        "keys": '\x02:split-window -h\r\x02:resize-pane -R 5\r\x02:list-commands\rjjjjjjq',
        "initial": 'class Pizza:\n    def __init__(self, size):\n        self.size = size\n        self.toppings = []\n\n    def add(self, topping):\n        self.toppings.append(topping)\n        return self\n\n    def bake(self):\n        return f"{self.size} pizza!"\n',
    },
    '0526_multiple_sessions': {
        "description": 'Multiple Sessions',
        "keys": '\x02:new-session -s api\r\x02:switch-client -t 0\r\x02:switch-client -t api\r',
        "initial": '  🌐 Pizza API v1.2\n  ───────────────────\n  Uptime: 14d 3h 22m\n  Reqs:   1,204/min\n  Errors: 0.02%\n  Status: healthy\n',
    },
    '0527_enter_copy_mode': {
        "description": 'Enter Copy Mode',
        "keys": '\x02[kkkgq',
        "initial": '',
    },
    '0528_copy_mode_navigation': {
        "description": 'Copy Mode Navigation',
        "keys": '\x02[kkkhh0www$Gggq',
        "initial": '',
    },
    '0529_copy_mode_visual_selection': {
        "description": 'Copy Mode Visual Selection',
        "keys": '\x02[kkkVjj\r\x02]',
        "initial": 'Mission Briefing — Op Starfall\n──────────────────────────────\nTarget: Orbital station Zeta-9\nObjective: retrieve data core\nExfil: pod bay C, deck 7\nTime limit: 12 minutes\n',
    },
    '0530_clock_mode': {
        "description": 'Clock Mode',
        "keys": '\x02tq\x02t ',
        "initial": '',
    },
    '0530a_send_literal_prefix': {
        "description": 'Send Literal Prefix',
        "keys": 'echo hello world\x02\x02',
        "initial": '',
    },
    '0530b_auto_unzoom': {
        "description": 'Auto-Unzoom',
        "keys": '\x02z\x02\x1b[A',
        "initial": '',
    },
    '0530c_pane_auto_close': {
        "description": 'Pane Auto-Close',
        "keys": '',
        "initial": '',
    },
    '0531_the_status_bar': {
        "description": 'The Status Bar',
        "keys": '\x02n\x02n\x020',
        "initial": '',
    },
    '0531a_split_window': {
        "description": 'split-window',
        "keys": '\x02:split-window\r\x02:split-window -h\r',
        "initial": '',
    },
    '0531b_new_window': {
        "description": 'new-window',
        "keys": '\x02:new-window\r',
        "initial": '',
    },
    '0531c_rename_window': {
        "description": 'rename-window',
        "keys": '\x02:rename-window editor\r',
        "initial": '',
    },
    '0531d_select_window': {
        "description": 'select-window',
        "keys": '\x02:select-window -t 0\r',
        "initial": '',
    },
    '0531e_select_pane': {
        "description": 'select-pane',
        "keys": '\x02:select-pane -t 0\r',
        "initial": '',
    },
    '0531f_resize_pane': {
        "description": 'resize-pane',
        "keys": '\x02:resize-pane -U 5\r',
        "initial": '',
    },
    '0531g_kill_pane': {
        "description": 'kill-pane / kill-window',
        "keys": '\x02:kill-pane\r',
        "initial": '',
    },
    '0531h_swap_pane': {
        "description": 'swap-pane',
        "keys": '\x02:swap-pane -U\r',
        "initial": '',
    },
    '0531i_next_layout': {
        "description": 'next-layout',
        "keys": '\x02:next-layout\r\x02:next-layout\r',
        "initial": '',
    },
    '0531j_display_panes': {
        "description": 'display-panes',
        "keys": '\x02:display-panes\r',
        "initial": '',
    },
    '0531k_list_keys': {
        "description": 'list-keys',
        "keys": '\x02:list-keys\rq',
        "initial": '',
    },
    '0532_the_shell_prompt': {
        "description": 'The Shell Prompt',
        "keys": 'date\rpwd\r\x1b[A\x1b[A\x1b[B\r',
        "initial": '',
    },
    '0533_file_management': {
        "description": 'File Management',
        "keys": "touch todo.txt\rls\recho 'buy milk' > todo.txt\rcat todo.txt\rcp todo.txt backup.txt\rls\rmv backup.txt notes.txt\rrm notes.txt\rls\r",
        "initial": '',
    },
    '0534_creating_files_with_content': {
        "description": 'Creating Files with Content',
        "keys": "echo 'eggs' > list.txt\rcat list.txt\recho 'bread' >> list.txt\recho 'coffee' >> list.txt\rcat list.txt\recho 'oops' > list.txt\rcat list.txt\r",
        "initial": '',
    },
    '0535_shell_utilities': {
        "description": 'Shell Utilities',
        "keys": 'wc log.txt\rgrep WARN log.txt\rsort log.txt\rdate\r',
        "initial": 'INFO  server started\nWARN  slow query\nINFO  request ok\nERROR timeout\nINFO  cache hit\nWARN  disk 90%\nINFO  request ok\n',
    },
    '0536_shell_shortcuts': {
        "description": 'Shell Shortcuts',
        "keys": "echo 'some output'\recho 'more output'\recho 'cluttered'\rclear\rhelp | head -5\r",
        "initial": '',
    },
    '0537_tab_completion': {
        "description": 'Tab Completion',
        "keys": 'cat space\t\rcat da\t\rwhic\t python3\r',
        "initial": "def connect():\n    return 'connected'\n",
    },
    '0538_shell_editing_keys': {
        "description": 'Shell Editing Keys',
        "keys": "echo hello world\x01\x05\x01\x0bpython3 app.py --debug\x15git commit -m 'oops'\x17\x17\x15",
        "initial": '',
    },
    '0539_cancel_and_clear': {
        "description": 'Cancel & Clear',
        "keys": "rm -rf /oops no wait\x03sleep 100\r\x03echo 'line one'\recho 'line two'\recho 'line three'\r\x0c",
        "initial": '',
    },
    '0540_opening_vim': {
        "description": 'Opening Vim',
        "keys": 'nvim rocket.py\r\x1b:q\rnvim newfile.py\r\x1b:q\r',
        "initial": "def launch():\n    print('3... 2... 1...')\n    print('Liftoff!')\n\nlaunch()\n",
    },
    '0541_vi_mode_in_the_shell': {
        "description": 'Vi-Mode in the Shell',
        "keys": 'set -o vi\recho hello world\x1bbb0i\x15set -o emacs\r',
        "initial": '',
    },
    '0542_vi_mode_editing': {
        "description": 'Vi-Mode Editing',
        "keys": 'git push origin main\x1bbbwbcwupstream\x1bbdwi\x15',
        "initial": '',
    },
    '0543_vi_mode_history_search': {
        "description": 'Vi-Mode History Search',
        "keys": '\x1b/echo\rnnNi\x15',
        "initial": '',
    },
    '0544_vim_plus_tmux_together': {
        "description": 'Vim + Tmux Together',
        "keys": "Gf'ci'VimFu\x1b:w\r\x02kpython3 hello.py\r\x02j",
        "initial": "def greet(name):\n    print(f'Hello {name}')\n\ngreet('world')\n",
    },
    '0600_edit_macro': {
        "description": 'Edit a Macro',
        "keys": 'qaI"\x1bA"\x1bqGo\x1b"ap',
        "initial": 'apple\nbanana\ncherry\ndate\nelderberry',
    },
}
